import "./ditto.css";
// Generated by clone-site. Do not edit by hand.
export default function Page() {
  return (
    <>
      <section className="block pt-55 pb-35 bg-color-001 max-lg:pt-[10.3125rem] max-lg:pb-[5.9375rem]" data-ditto-id="style-div-5">
        <div className="block max-w-407.5 px-[0.9375rem] mx-auto before:content-['_'] before:table before:w-0 before:h-0 before:text-foreground before:text-base before:leading-7 after:content-['_'] after:table after:w-0 after:h-0 after:text-foreground after:text-base after:leading-7" data-ditto-id="style-div-13">
          <div className="flex flex-col justify-start items-center gap-2.5 text-center">
            <h1 className="block text-background text-6xl font-semibold leading-[4rem] tracking-[-1.2px] max-md:text-[2.1875rem] max-md:leading-[2.3125rem] md:max-lg:text-[2.5rem] md:max-lg:leading-[2.625rem]" data-component="heading">
              Changelog
            </h1>
          </div>
        </div>
      </section>
      <section className="block pt-30 pb-[7.0625rem] max-lg:pt-15 max-lg:pb-[3.3125rem]">
        <div className="block max-w-407.5 px-[0.9375rem] mx-auto before:content-['_'] before:table before:w-0 before:h-0 before:text-foreground before:text-base before:leading-7 after:content-['_'] after:table after:w-0 after:h-0 after:text-foreground after:text-base after:leading-7">
          <div className="flex flex-col justify-start items-center text-center">
            <div className="block mb-[1.5625rem] max-lg:mb-[0.9375rem]">
              <img className="w-full h-8 block max-w-full overflow-clip object-cover aspect-[auto_108/32] align-middle" data-ditto-id="style-div" data-component="image" alt="" height="32" src="/assets/cloned/svg/06c57c8fa650.svg" width="108" />
            </div>
            <h2 className="block mb-[1.5625rem] text-color-001 text-[2.625rem] font-semibold leading-[3rem] tracking-[-0.84px] max-lg:mb-[0.9375rem] max-md:text-[1.5625rem] max-md:leading-[1.8125rem] md:max-lg:text-3xl md:max-lg:leading-[2.125rem]" data-component="heading">
              Template Version 1.0
            </h2>
            <div className="block mb-[1.5625rem] max-lg:mb-[0.9375rem]" data-ditto-id="style-pass">
              The Template Has Been Released!
            </div>
            <a className="h-[2.7125rem] border border-solid border-color-003 flex relative z-0 max-w-full pt-[0.5625rem] pb-2.5 px-5 rounded-[50px] justify-center items-center gap-2.5 overflow-hidden bg-color-003 cursor-pointer" data-component="link" href="/">
              <div className="h-[1.4rem] block relative z-1 overflow-hidden max-md:shrink-0" data-ditto-id="style-div-25">
                <div className="block text-background leading-6 whitespace-nowrap" data-ditto-id="style-button">
                  Back to home
                </div>
                <div className="block text-background leading-6 whitespace-nowrap" data-ditto-id="style-div-26">
                  Back to home
                </div>
              </div>
              <div className="w-[173.5px] h-[2.6375rem] flex absolute top-0 left-0 min-w-0 rounded-[50px] justify-center items-center bg-color-006 transform-[matrix(1,0,0,1,0,42.2031)] pointer-events-none" data-ditto-id="style-image" />
              <div className="w-[0.5875rem] h-[0.6rem] flex relative z-1 mt-0.5 justify-center items-center max-md:shrink-0" data-ditto-id="style-div-27">
                <img className="w-full h-2.5 block max-w-full overflow-clip object-cover aspect-[auto_9/9] align-middle" data-ditto-id="style-div-28" data-component="image" alt="button white arrow" height="9" src="/assets/cloned/svg/97bfaa7e2654.svg" width="9" />
              </div>
            </a>
          </div>
        </div>
      </section>
    </>
  );
}
