import "./ditto.css";
import Tile from "./components/tile";
import MediaTile from "./components/media-tile";
import MediaTile2 from "./components/media-tile2";
import Logo from "./components/logo";
import Logo2 from "./components/logo2";
// Generated by clone-site. Do not edit by hand.
const Tile_data = [
    { text: "Scar revision" },
    { text: "Pigmentation correction" },
    { text: "Wrinkle reduction" },
    { text: "Hair restoration" }
];
const Tile_data2 = [
    { text: "Skin renewal" },
    { text: "Scar revision" },
    { text: "Pigmentation correction" },
    { text: "Wrinkle reduction" },
    { text: "Hair restoration" }
];
const MediaTile_data = [
    { imgSrc: "/assets/cloned/images/ab487259cb09.webp", srcSet: "/assets/cloned/images/c0144bc71966.webp 500w, /assets/cloned/images/ab487259cb09.webp 600w", text: "Dr. Emily Carter", text2: "Board-Certified Dermatologist" },
    { imgSrc: "/assets/cloned/images/fdf3baa54f26.webp", srcSet: "/assets/cloned/images/cf675abfaff1.webp 500w, /assets/cloned/images/fdf3baa54f26.webp 600w", text: "Dr. Michael Reynolds", text2: "Cosmetic Dermatologist" },
    { imgSrc: "/assets/cloned/images/93956796b207.webp", srcSet: "/assets/cloned/images/942391a028b5.webp 500w, /assets/cloned/images/93956796b207.webp 600w", text: "Dr. Sarah Thompson", text2: "Medical Dermatology Specialist" },
    { imgSrc: "/assets/cloned/images/e9ded280210c.webp", srcSet: "/assets/cloned/images/f5fff1e7a0d7.webp 500w, /assets/cloned/images/e9ded280210c.webp 600w", text: "Dr. Jonathan Lee", text2: "Hair Restoration Specialist" },
    { imgSrc: "/assets/cloned/images/28337a6eae52.webp", srcSet: "/assets/cloned/images/0762f21aa1fd.webp 500w, /assets/cloned/images/28337a6eae52.webp 600w", text: "Dr. Daniel Harper", text2: "Acne and Pigmentation Specialist" },
    { imgSrc: "/assets/cloned/images/7cb64edef8cb.webp", srcSet: "/assets/cloned/images/6167d125cd6d.webp 500w, /assets/cloned/images/7cb64edef8cb.webp 600w", text: "Dr. Amanda Lewis", text2: "Senior Consultant Dermatologist" },
    { imgSrc: "/assets/cloned/images/de47e6ea27e8.webp", srcSet: "/assets/cloned/images/696039105ea1.webp 500w, /assets/cloned/images/de47e6ea27e8.webp 600w", text: "Dr. Andrew Collins", text2: "Anti-Aging Dermatologist" },
    { imgSrc: "/assets/cloned/images/f6996afa9c24.webp", srcSet: "/assets/cloned/images/b73f92a9c021.webp 500w, /assets/cloned/images/f6996afa9c24.webp 600w", text: "Dr. Natalie Foster", text2: "Medical Dermatology Consultant" }
];
const MediaTile2_data = [
    { ariacontrols: "w-dropdown-list-6", id: "w-dropdown-toggle-6", text: "What skin and hair conditions do you treat?" },
    { ariacontrols: "w-dropdown-list-7", id: "w-dropdown-toggle-7", text: "Are treatments safe and dermatologist-approved?" },
    { ariacontrols: "w-dropdown-list-8", id: "w-dropdown-toggle-8", text: "How many sessions are required to see results?" },
    { ariacontrols: "w-dropdown-list-9", id: "w-dropdown-toggle-9", text: "Do you offer personalized treatment plans?" }
];
const Logo_data = [
    { alt: "Instagram card image", imgSrc: "/assets/cloned/images/3a64c1d70e79.webp", srcSet: "/assets/cloned/images/71725079b07d.webp 500w, /assets/cloned/images/3a64c1d70e79.webp 600w" },
    { alt: "instagram-ticker-image", imgSrc: "/assets/cloned/images/b1bba367b88b.webp", srcSet: "/assets/cloned/images/96c5b7613678.webp 500w, /assets/cloned/images/b1bba367b88b.webp 600w" },
    { alt: "instagram-ticker-image-3", imgSrc: "/assets/cloned/images/1650f68d7e1e.webp", srcSet: "/assets/cloned/images/3a8531c13161.webp 500w, /assets/cloned/images/1650f68d7e1e.webp 600w" },
    { alt: "instagram-ticker-image-2", imgSrc: "/assets/cloned/images/c0c5228e2782.webp", srcSet: "/assets/cloned/images/0313207345a9.webp 500w, /assets/cloned/images/c0c5228e2782.webp 600w" }
];
const Logo2_data = [
    { alt: "Instagram image one", imgSrc: "/assets/cloned/images/b1e539bee6f4.webp", srcSet: "/assets/cloned/images/b7cdb78ef608.webp 500w, /assets/cloned/images/b1e539bee6f4.webp 600w" },
    { alt: "Instagram card image", imgSrc: "/assets/cloned/images/f982b31302c6.webp", srcSet: "/assets/cloned/images/0f47dfe60a3c.webp 500w, /assets/cloned/images/f982b31302c6.webp 600w" },
    { alt: "instagram card image", imgSrc: "/assets/cloned/images/29ff400e0696.webp", srcSet: "/assets/cloned/images/78be52a21c81.webp 500w, /assets/cloned/images/29ff400e0696.webp 600w" }
];
const Tile_meta: string[][] = [
    ["style-button", "style-div-26", "style-image", "style-div-27"],
    ["style-div-28", "style-div-29", "style-div-30", "style-image-2"],
    ["style-div-31", "style-div-32", "style-div-3", "style-div-33"],
    ["style-heading", "style-div-10", "style-heading-2", "style-div-4"]
];
const Tile_meta2: string[][] = [
    ["style-link", "style-image-3", "style-div-35", "style-div-36"],
    ["style-div-37", "style-div-38", "style-div-39", "style-div-40"],
    ["style-div-2", "style-div-41", "style-section", "style-div-42"],
    ["style-div-43", "n78", "n79", "style-div-6"],
    ["n81", "style-div-7", "n83", "style-div-8"]
];
const MediaTile_meta: string[][] = [
    ["style-div-48", "style-div-49", "style-div-50", "style-div-51", "style-div-9", "style-div-52"],
    ["style-div-53", "style-div-54", "style-div-55", "style-div-56", "style-div-57", "style-div-58"],
    ["style-div-59", "style-div-60", "style-div-61", "n111", "n112", "n113"],
    ["n114", "n115", "n116", "n117", "n118", "n119"],
    ["style-div-21", "n121", "n122", "n123", "n124", "n125"],
    ["style-div-62", "style-div-14", "n128", "n129", "n130", "n131"],
    ["n132", "n133", "n134", "n135", "n136", "n137"],
    ["n138", "n139", "n140", "n141", "n142", "n143"]
];
const MediaTile2_meta: string[][] = [
    ["style-div-71", "n311", "n312", "n313", "n314"],
    ["style-div-72", "n316", "n317", "n318", "n319"],
    ["n320", "n321", "n322", "n323", "n324"],
    ["n325", "n326", "n327", "n328", "n329"]
];
const Logo_meta: string[][] = [
    ["n338", "n339", "n340", "n341", "n342"],
    ["n343", "n344", "n345", "n346", "n347"],
    ["n348", "n349", "n350", "n351", "n352"],
    ["n353", "n354", "n355", "n356", "n357"]
];
const Logo2_meta: string[][] = [
    ["n360", "n361", "n362", "n363", "n364"],
    ["n365", "n366", "n367", "n368", "n369"],
    ["n370", "n371", "n372", "n373", "n374"]
];
const MediaTile_styles = [
    { className: "whitespace-nowrap" },
    {  },
    { className: "whitespace-nowrap" },
    { className: "whitespace-nowrap" },
    { className: "whitespace-nowrap" },
    { className: "whitespace-nowrap" },
    { className: "whitespace-nowrap" },
    { className: "whitespace-nowrap" }
];
const MediaTile2_styles = [
    { className: "max-md:h-1.5" },
    { className: "max-md:h-[0.3125rem] md:max-lg:h-1.5" },
    { className: "max-lg:h-1.5" },
    { className: "max-md:h-1.5" }
];
const Logo_styles = [
    { className2: "mt-10 rounded-[0.3px]" },
    { className: "md:max-lg:opacity-0", className2: "rounded-[0.6px]" },
    { className2: "mt-10 rounded-[0.3px]" },
    { className2: "rounded-[0.6px]" }
];
const Logo2_styles = [
    { className: "rounded-[0.6px]", className2: "max-lg:h-[2.3rem]" },
    { className: "mt-10 rounded-[0.3px]", className2: "max-lg:h-[2.3rem]" },
    { className: "rounded-[0.6px]" }
];

export default function Page() {
  return (
    <>
      <section className="h-[882.5px] min-h-screen block pt-132 pb-4 bg-color-004 [background-size:auto,_cover] [background-position:0px_0px,_50%_50%] [background-repeat:repeat,_no-repeat] [background-clip:border-box,_border-box] [background-origin:padding-box,_padding-box] [background-attachment:scroll,_scroll] [background-blend-mode:normal,_normal] [-webkit-background-clip:border-box,_border-box] max-md:h-[41.8625rem] max-md:pt-[18.4rem] max-md:px-[0.9375rem] max-md:[background-position:53%_50%,_53%_50%] max-md:min-h-0 md:max-lg:h-256 md:max-lg:pt-144 md:max-lg:[background-position:50%_50%,_50%_50%] 2xl:h-270" style={{ backgroundImage: "radial-gradient(circle, var(--clr-8), var(--clr-19)), url(\"/assets/cloned/images/98614b8fe7cf.avif\")" }} data-ditto-id="style-div-5">
        <div className="block max-w-407.5 px-[0.9375rem] mx-auto before:content-['_'] before:table before:w-0 before:h-0 before:text-foreground before:text-base before:leading-7 after:content-['_'] after:table after:w-0 after:h-0 after:text-foreground after:text-base after:leading-7" data-ditto-id="style-div-13">
          <div className="flex flex-col items-stretch gap-[11.4rem] max-md:gap-24 md:max-lg:gap-32">
            <div className="flex justify-between items-end gap-16 max-md:flex-col max-md:items-start max-md:gap-7.5">
              <div className="block max-w-[29.6875rem] max-md:max-w-80 max-md:justify-end md:max-lg:max-w-none">
                <h1 className="block text-background text-6xl font-semibold leading-[4rem] tracking-[-1.2px] max-md:text-[2.1875rem] max-md:leading-[2.3125rem] md:max-lg:text-[2.5rem] md:max-lg:leading-[2.625rem]" data-component="heading">
                  Meet our expert dermatologist
                </h1>
              </div>
              <div className="flex max-w-[22.5625rem] pr-[0.9375rem] flex-col items-start gap-9 max-md:max-w-none">
                <div className="w-7.5 h-0.5 block bg-color-012" />
                <div className="block text-background text-xl font-medium leading-6.5 tracking-[-0.4px] max-lg:text-lg max-lg:leading-[1.4375rem]" data-ditto-id="style-div">
                  Highly qualified expert specializing in comprehensive dermatology and aesthetic treatments
                </div>
              </div>
            </div>
            <div className="flex justify-start items-center overflow-hidden">
              <div className="flex items-start shrink-0 transform-[matrix(1,0,0,1,-242.505,0)] max-md:transform-[matrix(1,0,0,1,-372.978,0)] md:max-lg:transform-[matrix(1,0,0,1,-405.415,0)] 2xl:transform-[matrix(1,0,0,1,-1115.2,0)]" data-ditto-id="style-pass">
                <div className="flex pr-36 items-start shrink-0 gap-[0.5625rem] max-md:pr-8 md:max-lg:pr-16">
                  <div className="block justify-center items-center text-background text-lg font-medium leading-6 tracking-[-0.36px] max-lg:text-[1.0625rem] max-lg:leading-[1.4375rem]" data-ditto-id="style-div-25">
                    Skin renewal
                  </div>
                </div>
                {Tile_data.map((d, i) => <Tile key={i} d={d} />)}
              </div>
              <div className="flex items-start shrink-0 transform-[matrix(1,0,0,1,-242.505,0)] max-md:transform-[matrix(1,0,0,1,-372.978,0)] md:max-lg:transform-[matrix(1,0,0,1,-405.415,0)] 2xl:transform-[matrix(1,0,0,1,-1115.2,0)]" data-ditto-id="style-div-34">
                {Tile_data2.map((d, i) => <Tile key={i} d={d} />)}
              </div>
            </div>
          </div>
        </div>
      </section>
      <section className="block pt-[3.4375rem] pb-30 bg-surface max-lg:pb-15">
        <div className="block max-w-407.5 px-[0.9375rem] mx-auto before:content-['_'] before:table before:w-0 before:h-0 before:text-foreground before:text-base before:leading-7 after:content-['_'] after:table after:w-0 after:h-0 after:text-foreground after:text-base after:leading-7" data-ditto-id="style-p">
          <div className="block" data-ditto-id="style-div-24">
            <div className="flex flex-col justify-start items-center gap-12.5 max-md:items-stretch max-md:gap-8 md:max-lg:gap-7.5" data-ditto-id="style-div-11">
              <div className="flex max-w-120.5 flex-col justify-center items-center text-center">
                <div className="block mb-[1.5625rem] max-lg:mb-[0.9375rem]">
                  <div className="flex justify-start items-center gap-[0.4rem]" data-ditto-id="style-div-44">
                    <div className="w-[0.3125rem] h-[0.3125rem] block bg-color-004" data-ditto-id="style-div-45" />
                    <div className="block text-color-001 text-lg leading-[1.75rem] tracking-[-0.54px] max-md:leading-[1.5625rem] max-md:[font-size:inherit] md:max-lg:text-[1.0625rem] md:max-lg:leading-[1.625rem]" data-ditto-id="style-div-46">
                      Expert team
                    </div>
                  </div>
                </div>
                <h2 className="block text-color-001 text-[2.625rem] font-semibold leading-[3rem] tracking-[-0.84px] max-md:text-[1.5625rem] max-md:leading-[1.8125rem] md:max-lg:text-3xl md:max-lg:leading-[2.125rem]" data-ditto-id="style-div-12" data-component="heading">
                  Meet our dermatology experts
                </h2>
              </div>
              <div className="w-full grid gap-y-[3.3125rem] gap-x-7.5 [grid-auto-columns:1fr] grid-cols-[repeat(auto-fit,_minmax(289px,_1fr))] grid-rows-2 max-md:flex-col max-lg:self-stretch max-md:gap-6 max-md:grid-rows-8 md:max-lg:grid-rows-4 2xl:gap-12.5" data-ditto-id="style-div-47">
                {MediaTile_data.map((d, i) => <MediaTile key={i} d={d} styles={MediaTile_styles[i]} />)}
              </div>
            </div>
          </div>
        </div>
      </section>
      <section className="block py-30 max-lg:py-15">
        <div className="block max-w-407.5 px-[0.9375rem] mx-auto before:content-['_'] before:table before:w-0 before:h-0 before:text-foreground before:text-base before:leading-7 after:content-['_'] after:table after:w-0 after:h-0 after:text-foreground after:text-base after:leading-7">
          <div className="block">
            <div className="flex justify-between items-start gap-7.5 max-md:grid max-md:gap-[2.1rem] max-md:grid-cols-[345px] max-md:[grid-auto-columns:1fr] md:max-lg:pt-4" data-ditto-id="style-div-64">
              <div className="block max-w-[45.5625rem] rounded-md flex-1 overflow-hidden max-md:flex max-md:max-w-none">
                <img className="w-auto h-174.5 block max-w-full overflow-clip object-cover aspect-[auto_520/595] align-middle max-md:h-[24.6875rem] md:max-lg:h-[25.3125rem] 2xl:h-208.5" data-ditto-id="style-div-22" data-component="image" alt="faq-left-image-2" height="595" sizes="(max-width: 767px) 100vw, 520px" src="/assets/cloned/images/e1a60e9bb150.webp" srcSet="/assets/cloned/images/823e8e74a81f.webp 500w, /assets/cloned/images/884f48f1bec6.webp 800w, /assets/cloned/images/e1a60e9bb150.webp 1040w" width="520" />
              </div>
              <div className="block max-w-[45.4375rem] self-center flex-1 max-md:max-w-none">
                <div className="flex flex-col items-start">
                  <div className="block mb-[1.5625rem] max-lg:mb-[0.9375rem]">
                    <div className="flex justify-start items-center gap-[0.4rem]">
                      <div className="w-[0.3125rem] h-[0.3125rem] block bg-color-004" data-ditto-id="style-div-23" />
                      <div className="block text-color-001 text-lg leading-[1.75rem] tracking-[-0.54px] max-md:leading-[1.5625rem] max-md:[font-size:inherit] md:max-lg:text-[1.0625rem] md:max-lg:leading-[1.625rem]">
                        Why
                      </div>
                      <div className="block text-lg leading-[1.75rem] tracking-[-0.54px] max-md:leading-[1.5625rem] max-md:[font-size:inherit] md:max-lg:text-[1.0625rem] md:max-lg:leading-[1.625rem]">
                        choose us
                      </div>
                    </div>
                  </div>
                  <div className="w-full max-w-[42.2rem] block">
                    <h2 className="block mb-[1.5625rem] text-color-001 text-[2.625rem] font-semibold leading-[3rem] tracking-[-0.84px] max-lg:mb-[0.9375rem] max-md:text-[1.5625rem] max-md:leading-[1.8125rem] md:max-lg:text-3xl md:max-lg:leading-[2.125rem]" data-component="heading">
                      Why choose us for advanced dermatology
                    </h2>
                  </div>
                  <div className="block mb-[4.0625rem] max-lg:mb-7.5">
                    <p className="block">
                      We combine certified dermatologists, advanced technology, ethical practices, and personalized treatment plans to deliver safe, effective skin care results.
                    </p>
                  </div>
                </div>
                <div className="flex rounded-[15px] flex-col items-stretch gap-8.5 max-lg:gap-6">
                  <div className="border-b border-solid border-b-border flex relative z-900 pb-2.5 flex-col justify-between items-stretch text-left">
                    <div className="w-full flex relative mb-[1.5625rem] justify-between items-center gap-2.5 align-top text-color-002 whitespace-nowrap text-nowrap cursor-pointer max-md:mb-4 max-md:gap-8 md:max-lg:mb-[1.0625rem]" data-component="button" aria-controls="w-dropdown-list-2" aria-expanded="false" aria-haspopup="menu" id="w-dropdown-toggle-2" role="button">
                      <div className="block text-color-001 text-xl font-medium leading-6.5 tracking-[-0.4px] whitespace-normal max-lg:text-lg max-lg:leading-[1.4375rem]">
                        Advanced treatments with clinical excellence.
                      </div>
                      <div className="flex max-w-3 transform-[matrix(-1,0,0,-1,0,0)] origin-[6px_3.42188px] max-md:origin-[5.24219px_2.99219px] md:max-lg:origin-[5.76562px_3.28906px]">
                        <img className="w-full h-[0.4375rem] block max-w-full overflow-clip object-cover aspect-[auto_12/6] align-middle max-md:h-1.5" data-component="image" alt="" height="6" src="/assets/cloned/svg/a446313568d7.svg" width="12" />
                      </div>
                    </div>
                    <nav className="block min-w-full overflow-hidden bg-clr-15" data-component="nav" aria-labelledby="w-dropdown-toggle-2" id="w-dropdown-list-2">
                      <div className="w-full max-w-157.5 block pb-5.5 max-lg:pb-3.5">
                        <p className="block">
                          Structured treatment programs designed for precision, safety, and long-term wellbeing.
                        </p>
                      </div>
                    </nav>
                  </div>
                  <div className="w-full border-b border-solid border-b-border flex relative z-900 pb-2.5 flex-col justify-between items-stretch text-left">
                    <div className="w-full flex relative mb-[1.5625rem] justify-between items-center gap-2.5 align-top text-color-002 whitespace-nowrap text-nowrap cursor-pointer max-md:mb-4 max-md:gap-8 md:max-lg:mb-[1.0625rem]" data-component="button" aria-controls="w-dropdown-list-3" aria-expanded="false" aria-haspopup="menu" id="w-dropdown-toggle-3" role="button">
                      <div className="block text-color-001 text-xl font-medium leading-6.5 tracking-[-0.4px] whitespace-normal max-lg:text-lg max-lg:leading-[1.4375rem]">
                        Trusted experts delivering proven results.
                      </div>
                      <div className="flex max-w-3">
                        <img className="w-full h-[0.4375rem] block max-w-full overflow-clip object-cover aspect-[auto_12/6] align-middle" data-component="image" alt="" height="6" src="/assets/cloned/svg/a446313568d7.svg" width="12" />
                      </div>
                    </div>
                  </div>
                  <div className="w-full border-b border-solid border-b-border flex relative z-900 pb-2.5 flex-col justify-between items-stretch text-left">
                    <div className="w-full flex relative mb-[1.5625rem] justify-between items-center gap-2.5 align-top text-color-002 whitespace-nowrap text-nowrap cursor-pointer max-md:mb-4 max-md:gap-8 md:max-lg:mb-[1.0625rem]" data-component="button" aria-controls="w-dropdown-list-4" aria-expanded="false" aria-haspopup="menu" id="w-dropdown-toggle-4" role="button">
                      <div className="block text-color-001 text-xl font-medium leading-6.5 tracking-[-0.4px] whitespace-normal max-lg:text-lg max-lg:leading-[1.4375rem]">
                        Personalized care backed by expertise.
                      </div>
                      <div className="flex max-w-3">
                        <img className="w-full h-[0.4375rem] block max-w-full overflow-clip object-cover aspect-[auto_12/6] align-middle" data-component="image" alt="" height="6" src="/assets/cloned/svg/a446313568d7.svg" width="12" />
                      </div>
                    </div>
                  </div>
                </div>
              </div>
            </div>
          </div>
        </div>
      </section>
      <section className="block pb-[7.0625rem] bg-background max-lg:pb-[3.3125rem]">
        <div className="block max-w-407.5 px-[0.9375rem] mx-auto before:content-['_'] before:table before:w-0 before:h-0 before:text-foreground before:text-base before:leading-7 after:content-['_'] after:table after:w-0 after:h-0 after:text-foreground after:text-base after:leading-7">
          <div className="grid [grid-auto-columns:1fr] grid-cols-3 max-md:flex max-md:flex-col max-md:gap-[2.3rem] max-md:grid-cols-[repeat(auto-fit,_minmax(230px,_1fr))]" data-ditto-id="style-div-65">
            <div className="block max-w-[23.3125rem] max-md:max-w-none">
              <div className="border-b border-solid border-b-border flex pb-[1.8rem] justify-between items-center max-md:pb-2.5 max-md:items-start">
                <div className="flex items-start">
                  <div className="h-16 flex overflow-hidden max-md:h-[2.4rem] md:max-lg:h-[2.7rem]">
                    <div className="flex flex-col gap-2.5 max-lg:block max-lg:[flex-direction:initial] max-lg:gap-[initial]">
                      <div className="flex flex-col gap-2.5 transform-[matrix(1,0,0,1,0,-137.188)] max-lg:block max-md:transform-[matrix(1,0,0,1,0,-74.1875)] max-lg:[flex-direction:initial] max-lg:gap-[initial] md:max-lg:transform-[matrix(1,0,0,1,0,-84.8125)] 2xl:justify-center">
                        <div className="block text-color-001 text-6xl font-medium leading-[4rem] tracking-[-1.2px] max-md:text-[2.1875rem] max-md:leading-[2.3125rem] md:max-lg:text-[2.5rem] md:max-lg:leading-[2.625rem]">
                          0
                        </div>
                        <div className="block text-color-001 text-6xl font-medium leading-[4rem] tracking-[-1.2px] max-md:text-[2.1875rem] max-md:leading-[2.3125rem] md:max-lg:text-[2.5rem] md:max-lg:leading-[2.625rem]">
                          1
                        </div>
                      </div>
                      <div className="flex flex-col gap-2.5 transform-[matrix(1,0,0,1,0,-137.188)] max-lg:block max-md:transform-[matrix(1,0,0,1,0,-74.1875)] max-lg:[flex-direction:initial] max-lg:gap-[initial] md:max-lg:transform-[matrix(1,0,0,1,0,-84.8125)] 2xl:justify-center">
                        <div className="block text-color-001 text-6xl font-medium leading-[4rem] tracking-[-1.2px] max-md:text-[2.1875rem] max-md:leading-[2.3125rem] md:max-lg:text-[2.5rem] md:max-lg:leading-[2.625rem]">
                          2
                        </div>
                        <div className="block text-color-001 text-6xl font-medium leading-[4rem] tracking-[-1.2px] max-md:text-[2.1875rem] max-md:leading-[2.3125rem] md:max-lg:text-[2.5rem] md:max-lg:leading-[2.625rem]" data-ditto-id="style-div-66">
                          1
                        </div>
                      </div>
                    </div>
                    <div className="flex flex-col gap-2.5 max-lg:block max-lg:[flex-direction:initial] max-lg:gap-[initial]">
                      <div className="flex flex-col gap-2.5 transform-[matrix(1,0,0,1,0,-357.969)] max-lg:block max-md:transform-[matrix(1,0,0,1,0,-185.469)] max-lg:[flex-direction:initial] max-lg:gap-[initial] md:max-lg:transform-[matrix(1,0,0,1,0,-212.031)] 2xl:justify-center">
                        <div className="block text-color-001 text-6xl font-medium leading-[4rem] tracking-[-1.2px] max-md:text-[2.1875rem] max-md:leading-[2.3125rem] md:max-lg:text-[2.5rem] md:max-lg:leading-[2.625rem]">
                          0
                        </div>
                        <div className="block text-color-001 text-6xl font-medium leading-[4rem] tracking-[-1.2px] max-md:text-[2.1875rem] max-md:leading-[2.3125rem] md:max-lg:text-[2.5rem] md:max-lg:leading-[2.625rem]">
                          1
                        </div>
                        <div className="block text-color-001 text-6xl font-medium leading-[4rem] tracking-[-1.2px] max-md:text-[2.1875rem] max-md:leading-[2.3125rem] md:max-lg:text-[2.5rem] md:max-lg:leading-[2.625rem]">
                          2
                        </div>
                        <div className="block text-color-001 text-6xl font-medium leading-[4rem] tracking-[-1.2px] max-md:text-[2.1875rem] max-md:leading-[2.3125rem] md:max-lg:text-[2.5rem] md:max-lg:leading-[2.625rem]">
                          3
                        </div>
                        <div className="block text-color-001 text-6xl font-medium leading-[4rem] tracking-[-1.2px] max-md:text-[2.1875rem] max-md:leading-[2.3125rem] md:max-lg:text-[2.5rem] md:max-lg:leading-[2.625rem]">
                          4
                        </div>
                      </div>
                      <div className="flex flex-col gap-2.5 transform-[matrix(1,0,0,1,0,-357.969)] max-lg:block max-md:transform-[matrix(1,0,0,1,0,-185.469)] max-lg:[flex-direction:initial] max-lg:gap-[initial] md:max-lg:transform-[matrix(1,0,0,1,0,-212.031)] 2xl:justify-center">
                        <div className="block text-color-001 text-6xl font-medium leading-[4rem] tracking-[-1.2px] max-md:text-[2.1875rem] max-md:leading-[2.3125rem] md:max-lg:text-[2.5rem] md:max-lg:leading-[2.625rem]">
                          5
                        </div>
                        <div className="block text-color-001 text-6xl font-medium leading-[4rem] tracking-[-1.2px] max-md:text-[2.1875rem] max-md:leading-[2.3125rem] md:max-lg:text-[2.5rem] md:max-lg:leading-[2.625rem]">
                          1
                        </div>
                        <div className="block text-color-001 text-6xl font-medium leading-[4rem] tracking-[-1.2px] max-md:text-[2.1875rem] max-md:leading-[2.3125rem] md:max-lg:text-[2.5rem] md:max-lg:leading-[2.625rem]" data-ditto-id="style-div-67">
                          2
                        </div>
                        <div className="block text-color-001 text-6xl font-medium leading-[4rem] tracking-[-1.2px] max-md:text-[2.1875rem] max-md:leading-[2.3125rem] md:max-lg:text-[2.5rem] md:max-lg:leading-[2.625rem]">
                          3
                        </div>
                        <div className="block text-color-001 text-6xl font-medium leading-[4rem] tracking-[-1.2px] max-md:text-[2.1875rem] max-md:leading-[2.3125rem] md:max-lg:text-[2.5rem] md:max-lg:leading-[2.625rem]">
                          4
                        </div>
                      </div>
                    </div>
                  </div>
                  <div className="block -mt-[0.4rem] max-md:-mt-[0.1rem] md:max-lg:-mt-[0.3125rem]">
                    <div className="block text-color-004 [font-family:Merriweather,_serif] text-3xl leading-10 max-md:text-[1.375rem] max-md:leading-[1.8125rem] md:max-lg:text-[1.625rem] md:max-lg:leading-[2.1875rem]">
                      +
                    </div>
                  </div>
                </div>
                <div className="w-[4.0625rem] h-[4.0625rem] flex rounded-[100%] flex-col justify-center items-center bg-surface max-md:w-12 max-md:h-12">
                  <div className="block">
                    <img className="w-full h-[2.1875rem] block max-w-full overflow-clip object-cover aspect-[auto_35/35] align-middle max-md:h-[1.3125rem]" data-component="image" alt="" height="35" src="/assets/cloned/svg/e56150272e53.svg" width="35" />
                  </div>
                </div>
              </div>
              <div className="w-full max-w-64.5 block pt-7.5 max-md:pt-2.5">
                <div className="block text-color-001 text-xl font-medium leading-6.5 tracking-[-0.4px] max-lg:text-lg max-lg:leading-[1.4375rem]">
                  Specialized advanced hair treatment care
                </div>
              </div>
            </div>
            <div className="block max-w-[23.3125rem] max-md:max-w-none">
              <div className="border-b border-solid border-b-border flex pb-[1.8rem] justify-between items-center max-md:pb-2.5 max-md:items-start">
                <div className="flex">
                  <div className="h-16 flex overflow-hidden max-md:h-[2.4rem] md:max-lg:h-[2.7rem]">
                    <div className="flex flex-col gap-2.5 max-lg:block max-lg:[flex-direction:initial] max-lg:gap-[initial]">
                      <div className="flex flex-col gap-2.5 transform-[matrix(1,0,0,1,0,-652.344)] max-lg:block max-md:transform-[matrix(1,0,0,1,0,-333.844)] max-lg:[flex-direction:initial] max-lg:gap-[initial] md:max-lg:transform-[matrix(1,0,0,1,0,-381.656)] 2xl:justify-center">
                        <div className="block text-color-001 text-6xl font-medium leading-[4rem] tracking-[-1.2px] max-md:text-[2.1875rem] max-md:leading-[2.3125rem] md:max-lg:text-[2.5rem] md:max-lg:leading-[2.625rem]">
                          0
                        </div>
                        <div className="block text-color-001 text-6xl font-medium leading-[4rem] tracking-[-1.2px] max-md:text-[2.1875rem] max-md:leading-[2.3125rem] md:max-lg:text-[2.5rem] md:max-lg:leading-[2.625rem]">
                          1
                        </div>
                        <div className="block text-color-001 text-6xl font-medium leading-[4rem] tracking-[-1.2px] max-md:text-[2.1875rem] max-md:leading-[2.3125rem] md:max-lg:text-[2.5rem] md:max-lg:leading-[2.625rem]">
                          2
                        </div>
                        <div className="block text-color-001 text-6xl font-medium leading-[4rem] tracking-[-1.2px] max-md:text-[2.1875rem] max-md:leading-[2.3125rem] md:max-lg:text-[2.5rem] md:max-lg:leading-[2.625rem]">
                          3
                        </div>
                        <div className="block text-color-001 text-6xl font-medium leading-[4rem] tracking-[-1.2px] max-md:text-[2.1875rem] max-md:leading-[2.3125rem] md:max-lg:text-[2.5rem] md:max-lg:leading-[2.625rem]">
                          4
                        </div>
                        <div className="block text-color-001 text-6xl font-medium leading-[4rem] tracking-[-1.2px] max-md:text-[2.1875rem] max-md:leading-[2.3125rem] md:max-lg:text-[2.5rem] md:max-lg:leading-[2.625rem]">
                          5
                        </div>
                        <div className="block text-color-001 text-6xl font-medium leading-[4rem] tracking-[-1.2px] max-md:text-[2.1875rem] max-md:leading-[2.3125rem] md:max-lg:text-[2.5rem] md:max-lg:leading-[2.625rem]">
                          6
                        </div>
                        <div className="block text-color-001 text-6xl font-medium leading-[4rem] tracking-[-1.2px] max-md:text-[2.1875rem] max-md:leading-[2.3125rem] md:max-lg:text-[2.5rem] md:max-lg:leading-[2.625rem]">
                          7
                        </div>
                        <div className="block text-color-001 text-6xl font-medium leading-[4rem] tracking-[-1.2px] max-md:text-[2.1875rem] max-md:leading-[2.3125rem] md:max-lg:text-[2.5rem] md:max-lg:leading-[2.625rem]">
                          8
                        </div>
                      </div>
                      <div className="flex flex-col gap-2.5 transform-[matrix(1,0,0,1,0,-652.344)] max-lg:block max-md:transform-[matrix(1,0,0,1,0,-333.844)] max-lg:[flex-direction:initial] max-lg:gap-[initial] md:max-lg:transform-[matrix(1,0,0,1,0,-381.656)] 2xl:justify-center">
                        <div className="block text-color-001 text-6xl font-medium leading-[4rem] tracking-[-1.2px] max-md:text-[2.1875rem] max-md:leading-[2.3125rem] md:max-lg:text-[2.5rem] md:max-lg:leading-[2.625rem]">
                          9
                        </div>
                        <div className="block text-color-001 text-6xl font-medium leading-[4rem] tracking-[-1.2px] max-md:text-[2.1875rem] max-md:leading-[2.3125rem] md:max-lg:text-[2.5rem] md:max-lg:leading-[2.625rem]">
                          1
                        </div>
                        <div className="block text-color-001 text-6xl font-medium leading-[4rem] tracking-[-1.2px] max-md:text-[2.1875rem] max-md:leading-[2.3125rem] md:max-lg:text-[2.5rem] md:max-lg:leading-[2.625rem]">
                          2
                        </div>
                        <div className="block text-color-001 text-6xl font-medium leading-[4rem] tracking-[-1.2px] max-md:text-[2.1875rem] max-md:leading-[2.3125rem] md:max-lg:text-[2.5rem] md:max-lg:leading-[2.625rem]">
                          3
                        </div>
                        <div className="block text-color-001 text-6xl font-medium leading-[4rem] tracking-[-1.2px] max-md:text-[2.1875rem] max-md:leading-[2.3125rem] md:max-lg:text-[2.5rem] md:max-lg:leading-[2.625rem]">
                          4
                        </div>
                        <div className="block text-color-001 text-6xl font-medium leading-[4rem] tracking-[-1.2px] max-md:text-[2.1875rem] max-md:leading-[2.3125rem] md:max-lg:text-[2.5rem] md:max-lg:leading-[2.625rem]">
                          5
                        </div>
                        <div className="block text-color-001 text-6xl font-medium leading-[4rem] tracking-[-1.2px] max-md:text-[2.1875rem] max-md:leading-[2.3125rem] md:max-lg:text-[2.5rem] md:max-lg:leading-[2.625rem]">
                          6
                        </div>
                        <div className="block text-color-001 text-6xl font-medium leading-[4rem] tracking-[-1.2px] max-md:text-[2.1875rem] max-md:leading-[2.3125rem] md:max-lg:text-[2.5rem] md:max-lg:leading-[2.625rem]">
                          7
                        </div>
                        <div className="block text-color-001 text-6xl font-medium leading-[4rem] tracking-[-1.2px] max-md:text-[2.1875rem] max-md:leading-[2.3125rem] md:max-lg:text-[2.5rem] md:max-lg:leading-[2.625rem]">
                          8
                        </div>
                      </div>
                    </div>
                    <div className="flex flex-col gap-2.5 max-lg:block max-lg:[flex-direction:initial] max-lg:gap-[initial]">
                      <div className="flex flex-col gap-2.5 transform-[matrix(1,0,0,1,0,-210.781)] max-lg:block max-md:transform-[matrix(1,0,0,1,0,-111.281)] max-lg:[flex-direction:initial] max-lg:gap-[initial] md:max-lg:transform-[matrix(1,0,0,1,0,-127.219)] 2xl:justify-center">
                        <div className="block text-color-001 text-6xl font-medium leading-[4rem] tracking-[-1.2px] max-md:text-[2.1875rem] max-md:leading-[2.3125rem] md:max-lg:text-[2.5rem] md:max-lg:leading-[2.625rem]">
                          0
                        </div>
                        <div className="block text-color-001 text-6xl font-medium leading-[4rem] tracking-[-1.2px] max-md:text-[2.1875rem] max-md:leading-[2.3125rem] md:max-lg:text-[2.5rem] md:max-lg:leading-[2.625rem]" data-ditto-id="style-div-68">
                          1
                        </div>
                        <div className="block text-color-001 text-6xl font-medium leading-[4rem] tracking-[-1.2px] max-md:text-[2.1875rem] max-md:leading-[2.3125rem] md:max-lg:text-[2.5rem] md:max-lg:leading-[2.625rem]">
                          2
                        </div>
                      </div>
                      <div className="flex flex-col gap-2.5 transform-[matrix(1,0,0,1,0,-210.781)] max-lg:block max-md:transform-[matrix(1,0,0,1,0,-111.281)] max-lg:[flex-direction:initial] max-lg:gap-[initial] md:max-lg:transform-[matrix(1,0,0,1,0,-127.219)] 2xl:justify-center">
                        <div className="block text-color-001 text-6xl font-medium leading-[4rem] tracking-[-1.2px] max-md:text-[2.1875rem] max-md:leading-[2.3125rem] md:max-lg:text-[2.5rem] md:max-lg:leading-[2.625rem]">
                          3
                        </div>
                        <div className="block text-color-001 text-6xl font-medium leading-[4rem] tracking-[-1.2px] max-md:text-[2.1875rem] max-md:leading-[2.3125rem] md:max-lg:text-[2.5rem] md:max-lg:leading-[2.625rem]">
                          1
                        </div>
                        <div className="block text-color-001 text-6xl font-medium leading-[4rem] tracking-[-1.2px] max-md:text-[2.1875rem] max-md:leading-[2.3125rem] md:max-lg:text-[2.5rem] md:max-lg:leading-[2.625rem]">
                          2
                        </div>
                      </div>
                    </div>
                  </div>
                  <div className="block -mt-[0.4rem] max-md:-mt-[0.1rem] md:max-lg:-mt-[0.3125rem]">
                    <div className="block text-color-004 [font-family:Merriweather,_serif] text-3xl leading-10 max-md:text-[1.375rem] max-md:leading-[1.8125rem] md:max-lg:text-[1.625rem] md:max-lg:leading-[2.1875rem]">
                      %
                    </div>
                  </div>
                </div>
                <div className="w-[4.0625rem] h-[4.0625rem] flex rounded-[100%] flex-col justify-center items-center bg-surface max-md:w-12 max-md:h-12">
                  <div className="block">
                    <img className="w-full h-9.5 block max-w-full overflow-clip object-cover aspect-[auto_32/38] align-middle max-md:h-[1.5625rem]" data-component="image" alt="" height="38" src="/assets/cloned/svg/3ab92b50e772.svg" width="32" />
                  </div>
                </div>
              </div>
              <div className="block max-w-70.5 pt-7.5 max-md:pt-2.5 2xl:max-w-76">
                <div className="block text-color-001 text-xl font-medium leading-6.5 tracking-[-0.4px] max-lg:text-lg max-lg:leading-[1.4375rem]">
                  Excellent patient treatment satisfaction rate
                </div>
              </div>
            </div>
            <div className="block max-w-[23.3125rem] max-md:max-w-none">
              <div className="border-b border-solid border-b-border flex pb-[1.8rem] justify-between items-center max-md:pb-2.5 max-md:items-start">
                <div className="flex">
                  <div className="h-16 flex overflow-hidden max-md:h-[2.4rem] md:max-lg:h-[2.7rem]">
                    <div className="flex flex-col gap-2.5 max-lg:block max-lg:[flex-direction:initial] max-lg:gap-[initial]">
                      <div className="flex flex-col gap-2.5 transform-[matrix(1,0,0,1,0,-210.781)] max-lg:block max-md:transform-[matrix(1,0,0,1,0,-111.281)] max-lg:[flex-direction:initial] max-lg:gap-[initial] md:max-lg:transform-[matrix(1,0,0,1,0,-127.219)] 2xl:justify-center">
                        <div className="block text-color-001 text-6xl font-medium leading-[4rem] tracking-[-1.2px] max-md:text-[2.1875rem] max-md:leading-[2.3125rem] md:max-lg:text-[2.5rem] md:max-lg:leading-[2.625rem]">
                          0
                        </div>
                        <div className="block text-color-001 text-6xl font-medium leading-[4rem] tracking-[-1.2px] max-md:text-[2.1875rem] max-md:leading-[2.3125rem] md:max-lg:text-[2.5rem] md:max-lg:leading-[2.625rem]">
                          1
                        </div>
                        <div className="block text-color-001 text-6xl font-medium leading-[4rem] tracking-[-1.2px] max-md:text-[2.1875rem] max-md:leading-[2.3125rem] md:max-lg:text-[2.5rem] md:max-lg:leading-[2.625rem]" data-ditto-id="style-div-69">
                          2
                        </div>
                      </div>
                      <div className="flex flex-col gap-2.5 transform-[matrix(1,0,0,1,0,-210.781)] max-lg:block max-md:transform-[matrix(1,0,0,1,0,-111.281)] max-lg:[flex-direction:initial] max-lg:gap-[initial] md:max-lg:transform-[matrix(1,0,0,1,0,-127.219)] 2xl:justify-center">
                        <div className="block text-color-001 text-6xl font-medium leading-[4rem] tracking-[-1.2px] max-md:text-[2.1875rem] max-md:leading-[2.3125rem] md:max-lg:text-[2.5rem] md:max-lg:leading-[2.625rem]">
                          3
                        </div>
                        <div className="block text-color-001 text-6xl font-medium leading-[4rem] tracking-[-1.2px] max-md:text-[2.1875rem] max-md:leading-[2.3125rem] md:max-lg:text-[2.5rem] md:max-lg:leading-[2.625rem]">
                          1
                        </div>
                        <div className="block text-color-001 text-6xl font-medium leading-[4rem] tracking-[-1.2px] max-md:text-[2.1875rem] max-md:leading-[2.3125rem] md:max-lg:text-[2.5rem] md:max-lg:leading-[2.625rem]">
                          2
                        </div>
                      </div>
                    </div>
                    <div className="flex flex-col gap-2.5 max-lg:block max-lg:[flex-direction:initial] max-lg:gap-[initial]">
                      <div className="flex flex-col gap-2.5 transform-[matrix(1,0,0,1,0,-357.969)] max-lg:block max-md:transform-[matrix(1,0,0,1,0,-185.469)] max-lg:[flex-direction:initial] max-lg:gap-[initial] md:max-lg:transform-[matrix(1,0,0,1,0,-212.031)] 2xl:justify-center">
                        <div className="block text-color-001 text-6xl font-medium leading-[4rem] tracking-[-1.2px] max-md:text-[2.1875rem] max-md:leading-[2.3125rem] md:max-lg:text-[2.5rem] md:max-lg:leading-[2.625rem]">
                          0
                        </div>
                        <div className="block text-color-001 text-6xl font-medium leading-[4rem] tracking-[-1.2px] max-md:text-[2.1875rem] max-md:leading-[2.3125rem] md:max-lg:text-[2.5rem] md:max-lg:leading-[2.625rem]">
                          1
                        </div>
                        <div className="block text-color-001 text-6xl font-medium leading-[4rem] tracking-[-1.2px] max-md:text-[2.1875rem] max-md:leading-[2.3125rem] md:max-lg:text-[2.5rem] md:max-lg:leading-[2.625rem]">
                          2
                        </div>
                        <div className="block text-color-001 text-6xl font-medium leading-[4rem] tracking-[-1.2px] max-md:text-[2.1875rem] max-md:leading-[2.3125rem] md:max-lg:text-[2.5rem] md:max-lg:leading-[2.625rem]">
                          3
                        </div>
                        <div className="block text-color-001 text-6xl font-medium leading-[4rem] tracking-[-1.2px] max-md:text-[2.1875rem] max-md:leading-[2.3125rem] md:max-lg:text-[2.5rem] md:max-lg:leading-[2.625rem]">
                          4
                        </div>
                      </div>
                      <div className="flex flex-col gap-2.5 transform-[matrix(1,0,0,1,0,-357.969)] max-lg:block max-md:transform-[matrix(1,0,0,1,0,-185.469)] max-lg:[flex-direction:initial] max-lg:gap-[initial] md:max-lg:transform-[matrix(1,0,0,1,0,-212.031)] 2xl:justify-center">
                        <div className="block text-color-001 text-6xl font-medium leading-[4rem] tracking-[-1.2px] max-md:text-[2.1875rem] max-md:leading-[2.3125rem] md:max-lg:text-[2.5rem] md:max-lg:leading-[2.625rem]">
                          5
                        </div>
                        <div className="block text-color-001 text-6xl font-medium leading-[4rem] tracking-[-1.2px] max-md:text-[2.1875rem] max-md:leading-[2.3125rem] md:max-lg:text-[2.5rem] md:max-lg:leading-[2.625rem]">
                          1
                        </div>
                        <div className="block text-color-001 text-6xl font-medium leading-[4rem] tracking-[-1.2px] max-md:text-[2.1875rem] max-md:leading-[2.3125rem] md:max-lg:text-[2.5rem] md:max-lg:leading-[2.625rem]">
                          2
                        </div>
                        <div className="block text-color-001 text-6xl font-medium leading-[4rem] tracking-[-1.2px] max-md:text-[2.1875rem] max-md:leading-[2.3125rem] md:max-lg:text-[2.5rem] md:max-lg:leading-[2.625rem]">
                          3
                        </div>
                        <div className="block text-color-001 text-6xl font-medium leading-[4rem] tracking-[-1.2px] max-md:text-[2.1875rem] max-md:leading-[2.3125rem] md:max-lg:text-[2.5rem] md:max-lg:leading-[2.625rem]" data-ditto-id="style-div-63">
                          4
                        </div>
                      </div>
                    </div>
                  </div>
                  <div className="block -mt-[0.4rem] max-md:-mt-[0.1rem] md:max-lg:-mt-[0.3125rem]">
                    <div className="block text-color-004 [font-family:Merriweather,_serif] text-3xl leading-10 max-md:text-[1.375rem] max-md:leading-[1.8125rem] md:max-lg:text-[1.625rem] md:max-lg:leading-[2.1875rem]">
                      k
                    </div>
                  </div>
                </div>
                <div className="w-[4.0625rem] h-[4.0625rem] flex rounded-[100%] flex-col justify-center items-center bg-surface max-md:w-12 max-md:h-12">
                  <div className="block">
                    <img className="w-full h-[2.1875rem] block max-w-full overflow-clip object-cover aspect-[auto_36/35] align-middle max-md:h-5" data-component="image" alt="" height="35" src="/assets/cloned/svg/8fa9ea6ee436.svg" width="36" />
                  </div>
                </div>
              </div>
              <div className="block max-w-60 pt-7.5 max-md:pt-2.5 2xl:max-w-68">
                <div className="block text-color-001 text-xl font-medium leading-6.5 tracking-[-0.4px] max-lg:text-lg max-lg:leading-[1.4375rem]">
                  Consultations successfully completed
                </div>
              </div>
            </div>
          </div>
        </div>
      </section>
      <section className="block py-30 bg-surface max-lg:pt-[3.3125rem] max-lg:pb-15">
        <div className="block max-w-407.5 px-[0.9375rem] mx-auto before:content-['_'] before:table before:w-0 before:h-0 before:text-foreground before:text-base before:leading-7 after:content-['_'] after:table after:w-0 after:h-0 after:text-foreground after:text-base after:leading-7">
          <div className="block">
            <div className="flex justify-between items-start gap-7.5 max-md:flex-col max-md:items-stretch max-md:grid-cols-[1fr_1fr] max-md:grid-rows-[auto] max-md:[grid-auto-columns:1fr]">
              <div className="block relative max-w-[45.5625rem] flex-1">
                <div className="block mb-[1.5625rem] max-lg:mb-[0.9375rem]">
                  <div className="flex justify-start items-center gap-[0.4rem]">
                    <div className="w-[0.3125rem] h-[0.3125rem] block bg-color-004" />
                    <div className="block text-color-001 text-lg leading-[1.75rem] tracking-[-0.54px] max-md:leading-[1.5625rem] max-md:[font-size:inherit] md:max-lg:text-[1.0625rem] md:max-lg:leading-[1.625rem]">
                      Quick help guide
                    </div>
                  </div>
                </div>
                <div className="block rounded-[5px] overflow-hidden">
                  <img className="w-full h-119 block max-w-full overflow-clip object-cover aspect-[auto_729/569] align-middle max-md:h-[16.8125rem] md:max-lg:h-69 2xl:h-[35.5625rem]" data-component="image" alt="faq-left-image" height="569" sizes="(max-width: 767px) 100vw, (max-width: 991px) 728px, 729px" src="/assets/cloned/images/7c24cf11d3cf.webp" srcSet="/assets/cloned/images/cdbb14f09b2b.webp 500w, /assets/cloned/images/96ff31f7b95a.webp 800w, /assets/cloned/images/6ab2f7ccc69b.webp 1080w, /assets/cloned/images/7c24cf11d3cf.webp 1458w" width="729" />
                </div>
              </div>
              <div className="flex max-w-[45.4375rem] flex-col items-start flex-1 gap-12.5 max-md:gap-5 max-md:max-w-none md:max-lg:gap-7.5">
                <h2 className="block text-color-001 text-[2.625rem] font-semibold leading-[3rem] tracking-[-0.84px] max-md:text-[1.5625rem] max-md:leading-[1.8125rem] md:max-lg:text-3xl md:max-lg:leading-[2.125rem]" data-component="heading">
                  Frequently asked questions
                </h2>
                <div className="w-full flex rounded-[15px] flex-col items-stretch gap-8.5 max-lg:gap-6">
                  <div className="border-b border-solid border-b-border flex relative z-900 pb-2.5 flex-col justify-between items-stretch text-left">
                    <div className="w-full flex relative mb-[1.5625rem] justify-between items-center gap-2.5 align-top text-color-002 whitespace-nowrap text-nowrap cursor-pointer max-md:mb-4 max-md:gap-8 md:max-lg:mb-[1.0625rem]" data-component="button" aria-controls="w-dropdown-list-5" aria-expanded="false" aria-haspopup="menu" id="w-dropdown-toggle-5" role="button">
                      <div className="block text-color-001 text-xl font-medium leading-6.5 tracking-[-0.4px] whitespace-normal max-lg:text-lg max-lg:leading-[1.4375rem]">
                        Do I need an appointment before visiting the clinic?
                      </div>
                      <div className="flex max-w-3 transform-[matrix(-1,0,0,-1,0,0)] origin-[6px_3.42188px] max-md:origin-[4.69531px_2.67969px] md:max-lg:origin-[5.16406px_2.94531px]">
                        <img className="w-full h-[0.4375rem] block max-w-full overflow-clip object-cover aspect-[auto_12/6] align-middle max-md:h-[0.3125rem] md:max-lg:h-1.5" data-ditto-id="style-div-70" data-component="image" alt="" height="6" src="/assets/cloned/svg/a446313568d7.svg" width="12" />
                      </div>
                    </div>
                    <nav className="block min-w-full overflow-hidden bg-clr-15" data-component="nav" aria-labelledby="w-dropdown-toggle-5" id="w-dropdown-list-5">
                      <div className="w-full max-w-157.5 block pb-5.5 max-lg:pb-3.5">
                        <p className="block">
                          Yes, appointments are recommended to ensure adequate consultation time, reduced waiting, and personalized attention from specialists.
                        </p>
                      </div>
                    </nav>
                  </div>
                  {MediaTile2_data.map((d, i) => <MediaTile2 key={i} d={d} styles={MediaTile2_styles[i]} />)}
                </div>
              </div>
            </div>
          </div>
        </div>
      </section>
      <section className="block pb-30 bg-surface max-md:pt-10 max-lg:pb-15">
        <div className="block max-w-407.5 px-[0.9375rem] mx-auto before:content-['_'] before:table before:w-0 before:h-0 before:text-foreground before:text-base before:leading-7 after:content-['_'] after:table after:w-0 after:h-0 after:text-foreground after:text-base after:leading-7">
          <div className="flex flex-col justify-start items-center max-md:items-stretch max-md:gap-6">
            <div className="w-full max-w-136 flex mb-12.5 px-[0.9375rem] flex-col justify-start items-center gap-7.5 text-center max-lg:mb-7.5 max-lg:gap-[1.5625rem]">
              <div className="block max-w-12.5 max-md:max-w-10">
                <img className="w-full h-12.5 block max-w-full overflow-clip object-cover aspect-[auto_50/50] align-middle max-md:h-10" data-component="image" alt="" height="50" src="/assets/cloned/svg/4dfaa84db602.svg" width="50" />
              </div>
              <h2 className="block text-color-001 text-[2.625rem] font-semibold leading-[3rem] tracking-[-0.84px] max-md:text-[1.5625rem] max-md:leading-[1.8125rem] md:max-lg:text-3xl md:max-lg:leading-[2.125rem]" data-component="heading">
                Stay connected with our dermatology clinic
              </h2>
            </div>
            <div className="w-312.5 flex items-start shrink-0 gap-12.5 max-lg:hidden 2xl:w-400">
              {Logo_data.map((d, i) => <Logo key={i} d={d} styles={Logo_styles[i]} />)}
            </div>
          </div>
        </div>
        <div className="hidden items-start self-stretch overflow-hidden max-lg:flex">
          <div className="flex items-start shrink-0 transform-[none] max-lg:w-330 max-md:grid-cols-[1fr_1fr] max-md:grid-rows-[auto_auto] max-md:[grid-auto-columns:1fr] max-md:transform-[matrix(1,0,0,1,-111.45,0)] md:max-lg:transform-[matrix(1,0,0,1,-108.52,0)]">
            {Logo2_data.map((d, i) => <Logo2 key={i} d={d} styles={Logo2_styles[i]} />)}
          </div>
        </div>
      </section>
    </>
  );
}
