import "./ditto.css";
// Generated by clone-site. Do not edit by hand.
export default function Page() {
  return (
    <>
      <div className="h-[59.9375rem] min-h-screen flex max-w-full max-h-full pt-[12.2375rem] pb-30 justify-center items-center bg-surface max-md:h-203 max-lg:pt-25 max-lg:pb-15 max-md:overflow-hidden md:max-lg:h-256 2xl:h-270" data-ditto-id="style-div-5">
        <div className="flex px-[6.3125rem] flex-col items-center gap-[2.9rem] text-center max-md:px-[0.9375rem] max-md:gap-[2.2rem]" data-ditto-id="style-div-13">
          <div className="block max-w-212.5 max-md:max-w-80">
            <img className="w-full h-[26.4375rem] block max-w-full overflow-clip object-cover aspect-[auto_850/422] align-middle max-md:h-[9.9375rem] md:max-lg:h-[17.5625rem]" data-component="image" alt="" height="422" sizes="(max-width: 991px) 100vw, 850px" src="/assets/cloned/images/c5e28983871b.webp" srcSet="/assets/cloned/images/9d75c0137b98.webp 500w, /assets/cloned/images/028ff30868b7.webp 800w, /assets/cloned/images/c23b96d961ce.webp 1080w, /assets/cloned/images/c5e28983871b.webp 1700w" width="850" />
          </div>
          <div className="flex flex-col justify-start items-center">
            <h2 className="block mb-[1.5625rem] text-color-001 text-[2.625rem] font-semibold leading-[3rem] tracking-[-0.84px] max-lg:mb-[0.9375rem] max-md:text-[1.5625rem] max-md:leading-[1.8125rem] md:max-lg:text-3xl md:max-lg:leading-[2.125rem]" data-component="heading">
              Oops! something went wrong
            </h2>
            <div className="block mb-7.5 max-lg:mb-5">
              We can’t find the page your are looking for.
            </div>
            <div className="w-full block max-w-79.5">
              <a className="w-79.5 h-[2.7125rem] border border-solid border-color-010 flex relative z-0 max-w-full pt-[0.5625rem] pb-2.5 px-5 rounded-[50px] justify-between items-center gap-2.5 overflow-hidden bg-clr-1 cursor-pointer" data-ditto-id="style-div" data-component="link" href="/">
                <div className="h-[1.4rem] block relative z-1 overflow-hidden max-md:shrink-0">
                  <div className="block -mb-[0.4rem] text-color-001 leading-6 whitespace-nowrap max-lg:-mb-[0.1rem]" data-ditto-id="style-pass">
                    Back to home
                  </div>
                  <div className="block text-color-001 leading-6 whitespace-nowrap">
                    Back to home
                  </div>
                </div>
                <div className="w-[322.3px] h-[2.6375rem] flex absolute top-0 left-0 min-w-0 rounded-[50px] justify-center items-center bg-color-006 transform-[matrix(1,0,0,1,0,42.2031)] pointer-events-none" data-ditto-id="style-div-25" />
                <div className="w-[0.5875rem] h-[0.6rem] flex relative z-1 mt-0.5 justify-center items-center max-md:shrink-0" data-ditto-id="style-button">
                  <img className="w-full h-2.5 block max-w-full overflow-clip object-cover aspect-[auto_9/9] align-middle [filter:invert(1)]" data-ditto-id="style-div-26" data-component="image" alt="" height="9" src="/assets/cloned/svg/c81dc04c407a.svg" width="9" />
                </div>
              </a>
            </div>
          </div>
        </div>
      </div>
    </>
  );
}
