import "./ditto.css";
import FeatureCard from "./components/feature-card";
import Logo from "./components/logo";
import MediaTile from "./components/media-tile";
import MediaTile2 from "./components/media-tile2";
import Logo2 from "./components/logo2";
import Logo3 from "./components/logo3";
import MediaTile3 from "./components/media-tile3";
import MediaTile5 from "./components/media-tile5";
import Logo4 from "./components/logo4";
// Generated by clone-site. Do not edit by hand.
const FeatureCard_data = [
    { kind: "heading", title: "Bienestar -" },
    { kind: "heading", title: "Masajes -" },
    { title: "Fisioterapia -" },
    { title: "Estética -" }
];
const Logo_data = [
    { alt: "About train image one", imgSrc: "/assets/cloned/images/5a06d51bc141.webp" },
    { alt: "About train image one", imgSrc: "/assets/cloned/images/dd4f116f1f16.webp" },
    { alt: "About train image two", imgSrc: "/assets/cloned/images/c446e3733bb6.webp" },
    { alt: "About train image three", imgSrc: "/assets/cloned/images/fadedbcbd9ae.webp" },
    { alt: "About train image four", imgSrc: "/assets/cloned/images/38fac63ae528.webp" },
    { alt: "About train image five", imgSrc: "/assets/cloned/images/925623bd9eec.webp" }
];
const MediaTile_data = [
    { text: "Sueros y vitaminas antiedad" },
    { text: "Mesoterapia" },
    { text: "Tonificación (flacidez)" }
];
const MediaTile_data2 = [
    { text: "Tratamiento para alopecia" },
    { text: "Reducción de papada" },
    { text: "Tratamiento para ojeras" }
];
const MediaTile2_data = [
    { text: "Maderoterapia ", text2: "y moldeamiento", alt: "service-card-flip-image", imgSrc: "/assets/cloned/images/7095b493bb44.webp", text3: "Reducción de medidas" },
    { text: "Sueros ", text2: "y vitaminas", alt: "service-card-flip-image-2", imgSrc: "/assets/cloned/images/752adf555312.avif", text3: "Sueros y vitaminas antiedad" },
    { text: "Estética ", text2: "facial y corporal", alt: "service service card six", imgSrc: "/assets/cloned/images/b27d237e3e61.avif", text3: "Estética facial y corporal" }
];
const Logo2_data = [
    { alt: "client-service-small-image", imgSrc: "/assets/cloned/images/487fa58beb46.webp" },
    { alt: "rt-recents-treatments-lower-right-small-image-wrapper-image", imgSrc: "/assets/cloned/images/f8937db43bd9.webp" },
    { alt: "client-service-small-image", imgSrc: "/assets/cloned/images/dc8027b34669.webp" }
];
const Logo3_data = [
    { alt: "Masaje relajante", imgSrc: "/assets/fotos/masaje-relajante.webp" },
    { alt: "Terapia manual", imgSrc: "/assets/fotos/terapia-manual.webp" },
    { alt: "Rehabilitación", imgSrc: "/assets/fotos/rehabilitacion.webp" },
    { alt: "Tratamiento facial", imgSrc: "/assets/fotos/tratamiento-facial.webp" },
    { alt: "Electroterapia", imgSrc: "/assets/fotos/electroterapia.webp" },
    { alt: "Mesoterapia facial", imgSrc: "/assets/fotos/mesoterapia-facial.webp" }
];
const MediaTile3_data = [
    { alt: "Fachada de Medical Livesthetic Fisiospa", height: "687", imgSrc: "/assets/brand/local.jpg", text: "Nuestra sede", text2: "Teresa de Ávila y Fray Luis de León", text3: "Parque Valladolid, Cuenca – Ecuador" },
    { alt: "about where you find two", height: "114", imgSrc: "/assets/cloned/images/b364eff3863e.webp", text: "Horario de atención", text2: "Lunes a viernes", text3: "8:30 – 12:00 y 14:00 – 17:30" },
    { alt: "about where you find us three", height: "114", imgSrc: "/assets/cloned/images/975919161932.webp", text: "WhatsApp y llamadas", text2: "+593 97 989 8964", text3: "Agenda tu cita" },
    { alt: "about where you find us four", height: "114", imgSrc: "/assets/cloned/images/1a996c68c9a9.webp", text: "Correo electrónico", text2: "medicallivesthetic@gmail.com", text3: "Consultas e información" }
];
const MediaTile5_data = [
    { alt: "instagram-ticker-image-3", imgSrc: "/assets/cloned/images/1650f68d7e1e.webp", srcSet: "/assets/cloned/images/3a8531c13161.webp 500w, /assets/cloned/images/1650f68d7e1e.webp 600w" },
    { alt: "instagram-ticker-image", imgSrc: "/assets/cloned/images/b1bba367b88b.webp", srcSet: "/assets/cloned/images/96c5b7613678.webp 500w, /assets/cloned/images/b1bba367b88b.webp 600w" },
    { alt: "instagram-ticker-image-2", imgSrc: "/assets/cloned/images/c0c5228e2782.webp", srcSet: "/assets/cloned/images/0313207345a9.webp 500w, /assets/cloned/images/c0c5228e2782.webp 600w" },
    { alt: "service image one", imgSrc: "/assets/cloned/images/bc7a4c90a782.webp", srcSet: "/assets/cloned/images/7e9745369cf7.webp 500w, /assets/cloned/images/bc7a4c90a782.webp 600w" }
];
const Logo4_data = [
    { alt: "Instagram image one", imgSrc: "/assets/cloned/images/b1e539bee6f4.webp", srcSet: "/assets/cloned/images/b7cdb78ef608.webp 500w, /assets/cloned/images/b1e539bee6f4.webp 600w" },
    { alt: "Publicación de Instagram", imgSrc: "/assets/cloned/images/f982b31302c6.webp", srcSet: "/assets/cloned/images/0f47dfe60a3c.webp 500w, /assets/cloned/images/f982b31302c6.webp 600w" },
    { alt: "instagram card image", imgSrc: "/assets/cloned/images/29ff400e0696.webp", srcSet: "/assets/cloned/images/78be52a21c81.webp 500w, /assets/cloned/images/29ff400e0696.webp 600w" }
];
const FeatureCard_meta: string[][] = [
    ["style-div-34", "style-link"],
    ["style-image-3", "style-div-35"],
    ["style-div-36", "style-div-37"],
    ["style-div-38", "style-div-39"]
];
const Logo_meta: string[][] = [
    ["style-div-23", "n155", "n156"],
    ["n157", "n158", "n159"],
    ["n160", "n161", "n162"],
    ["n163", "n164", "n165"],
    ["n166", "n167", "n168"],
    ["n169", "n170", "n171"]
];
const MediaTile_meta: string[][] = [
    ["style-div-66", "n194", "n195", "n196", "n197", "n198"],
    ["n199", "n200", "n201", "n202", "n203", "style-div-67"],
    ["n205", "n206", "n207", "n208", "n209", "n210"]
];
const MediaTile_meta2: string[][] = [
    ["n226", "n227", "n228", "n229", "n230", "n231"],
    ["n232", "n233", "n234", "n235", "n236", "n237"],
    ["n238", "n239", "n240", "n241", "style-div-68", "n243"]
];
const MediaTile2_meta: string[][] = [
    ["n250", "n251", "n252", "n253", "n254", "n255", "n256", "n257", "n258", "n259", "n260", "n261", "n262", "style-div-69", "n264", "n265", "n266", "n267"],
    ["n268", "n269", "n270", "n271", "n272", "n273", "n274", "n275", "n276", "n277", "n278", "n279", "style-div-63", "n281", "n282", "n283", "n284", "n285"],
    ["n286", "n287", "n288", "n289", "n290", "n291", "n292", "n293", "n294", "n295", "n296", "n297", "n298", "n299", "n300", "n301", "n302", "n303"]
];
const Logo2_meta: string[][] = [
    ["n307", "n308"],
    ["n309", "style-div-71"],
    ["n311", "n312"]
];
const Logo3_meta: string[][] = [
    ["n358", "n359"],
    ["n360", "n361"],
    ["n362", "n363"],
    ["n364", "n365"],
    ["n366", "n367"],
    ["n368", "n369"]
];
const MediaTile3_meta: string[][] = [
    ["interaction-div", "n390", "n391", "interaction-div-2", "n393", "n394", "n395", "n396", "interaction-w-slider-mask-0", "n398", "n399", "interaction-div-3", "n401", "n402", "n403", "n404", "interaction-div-4", "n406", "n407", "interaction-div-5", "n409", "n410", "n411"],
    ["n412", "n413", "n414", "n415", "n416", "n417", "n418", "n419", "n420", "n421", "n422", "n423", "n424", "n425", "n426", "n427", "n428", "n429", "n430", "n431", "n432", "n433", "n434"],
    ["style-div-15", "n436", "n437", "n438", "n439", "n440", "n441", "n442", "n443", "n444", "n445", "n446", "n447", "n448", "n449", "n450", "n451", "n452", "n453", "n454", "n455", "n456", "n457"],
    ["n458", "n459", "n460", "n461", "n462", "n463", "n464", "n465", "n466", "n467", "style-div-16", "n469", "n470", "n471", "n472", "n473", "n474", "n475", "n476", "n477", "n478", "n479", "n480"]
];
const MediaTile5_meta: string[][] = [
    ["n595", "n596", "n597", "n598", "n599", "n600"],
    ["n601", "n602", "n603", "n604", "n605", "n606"],
    ["n607", "style-div-17", "n609", "n610", "n611", "n612"],
    ["n613", "n614", "n615", "n616", "n617", "n618"]
];
const Logo4_meta: string[][] = [
    ["n624", "n625", "n626", "n627", "n628"],
    ["n629", "n630", "style-div-18", "n632", "n633"],
    ["n634", "n635", "n636", "n637", "n638"]
];
const FeatureCard_styles = [
    { className: "w-[28.8375rem] h-full md:max-lg:w-[19.3125rem]" },
    { className: "w-81 md:max-lg:w-[218.7px]" },
    { className: "w-[366.3px] md:max-lg:w-[246.9px]" },
    { className: "w-[25.15rem] md:max-lg:w-[270.5px]" }
];
const MediaTile2_styles = [
    { className: "transform-[matrix3d(-1,0,0,0,0,1,0,0,0,0,-1,0,0,0,0,1)] origin-[191.664px_203.805px] max-md:origin-[172.5px_170.398px] md:max-lg:origin-[113px_213.305px] 2xl:origin-[250px_203.805px]", className2: "origin-[191.664px_203.805px]" },
    { className: "transform-[matrix3d(-1,0,0,0,0,1,0,0,0,0,-1,0,0,0,0,1)] origin-[191.664px_203.805px] max-md:origin-[172.5px_170.398px] md:max-lg:origin-[113px_213.305px] 2xl:origin-[250px_203.805px]", className2: "origin-[191.664px_203.805px]" },
    { className2: "origin-[191.672px_203.805px]" }
];
const Logo2_styles = [
    {  },
    { className: "-ml-[2.4375rem]" },
    { className: "-ml-[2.4375rem]" }
];
const Logo3_styles = [
    { className: "max-md:opacity-0", className2: "h-31.5 max-md:h-[9.6875rem]" },
    { className: "max-md:opacity-0", className2: "h-31.5 max-md:h-[9.6875rem]" },
    { className: "max-md:max-w-none", className2: "h-31.5 max-md:h-[9.6875rem]" },
    { className: "max-md:max-w-none", className2: "h-31.5 max-md:h-[9.6875rem]" },
    { className: "max-md:max-w-none", className2: "h-[7.9375rem] max-md:h-39" },
    { className: "max-md:max-w-none", className2: "h-31.5 max-md:h-[9.6875rem]" }
];
const MediaTile3_styles = [
    { className: "h-[136.1px] max-md:h-[106.1px]", className2: "h-26.5 aspect-[auto_114/110]", className3: "w-[1.1875rem] max-md:w-[0.8rem] md:max-lg:w-[0.7875rem]", className4: "max-lg:h-[0.9375rem]" },
    { className: "h-35 max-md:h-27.5", className2: "h-27.5 aspect-[auto_114/114]", className3: "w-[1.1875rem] max-md:w-[0.8rem] md:max-lg:w-[0.7125rem]", className4: "max-md:h-[0.9375rem] md:max-lg:h-3.5" },
    { className: "h-35 max-md:h-27.5", className2: "h-27.5 aspect-[auto_114/114]", className3: "w-[6.5%] max-md:w-[5%] md:max-lg:w-[7%]", className4: "max-md:h-[0.9375rem] md:max-lg:h-[0.8125rem]" },
    { className: "h-35 max-md:h-27.5", className2: "h-27.5 aspect-[auto_114/114]", className3: "w-[1.1875rem] max-md:w-[0.8rem] md:max-lg:w-[0.775rem]", className4: "max-lg:h-[0.9375rem]" }
];
const MediaTile5_styles = [
    { className2: "mt-10 rounded-[0.3px]" },
    { className: "md:max-lg:opacity-0", className2: "rounded-[0.6px]" },
    { className2: "mt-10 rounded-[0.3px]" },
    { className2: "rounded-[0.6px]" }
];
const Logo4_styles = [
    { className: "rounded-[0.6px]", className2: "max-lg:h-[2.3rem]" },
    { className: "mt-10 rounded-[0.3px]" },
    { className: "rounded-[0.6px]" }
];

export default function Page() {
  return (
    <>
      <section className="h-400 min-h-400 block max-md:h-[625.7px] max-lg:min-h-0 md:max-lg:h-[47.05rem] 2xl:h-540 2xl:min-h-540" data-ditto-id="style-div-5">
        <div className="h-[59.725rem] min-h-screen block sticky top-0 pt-[11.6875rem] pb-30 overflow-hidden bg-color-004 [background-size:auto,_auto,_cover] [background-position:0px_0px,_0px_0px,_50%_50%] [background-repeat:repeat,_repeat,_no-repeat] [background-clip:border-box,_border-box,_border-box] [background-origin:padding-box,_padding-box,_padding-box] [background-attachment:scroll,_scroll,_fixed] [background-blend-mode:normal,_normal,_normal] [-webkit-background-clip:border-box,_border-box,_border-box] max-md:h-[625.7px] max-lg:relative max-lg:bottom-0 max-lg:inset-x-0 max-lg:pt-[7.8375rem] max-lg:pb-15 max-lg:min-h-0 md:max-lg:h-[47.05rem] 2xl:h-270" style={{ backgroundImage: "linear-gradient(var(--color-004), var(--clr-17) 21%, var(--clr-17) 81%, var(--color-004)), radial-gradient(circle closest-corner, var(--clr-18) 12%, var(--clr-19)), url(\"/assets/cloned/images/1441319c2c90.webp\")" }} data-ditto-id="style-div-13">
          <div className="block max-w-407.5 px-[0.9375rem] mx-auto before:content-['_'] before:table before:w-0 before:h-0 before:text-foreground before:text-base before:leading-7 after:content-['_'] after:table after:w-0 after:h-0 after:text-foreground after:text-base after:leading-7">
            <div className="flex flex-col justify-start items-center">
              <div className="block mb-12.5 max-lg:mb-7.5 max-md:flex-col max-md:items-start max-md:gap-7.5 2xl:items-center">
                <h1 className="block text-background text-6xl font-semibold leading-[4rem] tracking-[-1.2px] whitespace-nowrap max-md:text-[2.1875rem] max-md:leading-[2.3125rem] md:max-lg:text-[2.5rem] md:max-lg:leading-[2.625rem]" data-component="heading">
                  El centro
                </h1>
              </div>
              <div className="w-full h-[33.4375rem] min-h-[33.4375rem] flex relative z-1 flex-col justify-between items-center max-md:h-[23.325rem] max-lg:min-h-0 md:max-lg:h-[26.4125rem]">
                <div className="w-[26%] h-[164.3px] block mb-10 max-lg:w-full max-md:h-72 md:max-lg:h-90">
                  <div className="h-full block relative rounded-[5px] overflow-hidden text-background" data-ditto-id="style-div">
                    <video className="w-[20.1875rem] h-41 block absolute top-[-164.3px] -left-[20.2rem] -z-100 my-[164.3px] mx-[20.2rem] overflow-clip object-cover bg-cover [background-position:50%_50%] max-md:w-[21.5625rem] max-md:h-72 max-md:-top-72 max-md:-left-[21.5625rem] max-md:my-72 max-md:mx-[21.5625rem] md:max-lg:w-184.5 md:max-lg:h-90 md:max-lg:-top-90 md:max-lg:-left-184.5 md:max-lg:my-90 md:max-lg:mx-184.5 2xl:w-103.5 2xl:left-[-413.7px] 2xl:mx-[413.7px]" style={{ backgroundImage: "url(\"/assets/cloned/images/785413b3ca18.jpg\")" }} autoPlay id="eda1ea67-4959-6330-221f-62f7ccc5caa2-video" loop muted playsInline poster="/assets/cloned/images/8da028852dd2.jpg">
                      <source className="inline text-color-004 [font-family:'Times_New_Roman'] leading-4.5" data-ditto-id="style-pass" src="/assets/cloned/videos/e23b409c3d3a.mp4" />
                      <source className="inline text-color-004 [font-family:'Times_New_Roman'] leading-4.5" src="/assets/cloned/videos/260ff7679b30.webm" />
                    </video>
                    <div className="block" data-ditto-id="style-div-25" aria-live="polite">
                      <button className="w-10 h-10 block absolute bottom-2 left-[6.5px] text-center cursor-pointer max-md:bottom-[0.9rem] max-md:left-[6.9px] md:max-lg:bottom-4.5 md:max-lg:left-[0.925rem] 2xl:left-[8.3px]" data-ditto-id="style-button" data-component="button" aria-controls="eda1ea67-4959-6330-221f-62f7ccc5caa2-video" type="button">
                        <span className="inline" data-ditto-id="style-div-26">
                          <img className="w-full h-10 block max-w-full overflow-clip object-cover align-middle" data-ditto-id="style-image" data-component="image" alt="Pausar video" src="/assets/cloned/svg/5eb5fbcbf2ae.svg" />
                        </span>
                      </button>
                    </div>
                  </div>
                </div>
                <div className="block" data-ditto-id="style-div-27">
                  <div className="flex flex-col justify-start items-center max-md:gap-4" data-ditto-id="style-div-28">
                    <div className="flex justify-start items-center gap-[0.7rem]" data-ditto-id="style-div-29">
                      <div className="w-[0.9375rem] block max-md:w-[11.3px]" data-ditto-id="style-div-30">
                        <img className="w-full h-[0.9375rem] block max-w-full overflow-clip object-cover aspect-[auto_15/15] align-middle max-md:h-[0.6875rem]" data-ditto-id="style-image-2" data-component="image" alt="" height="15" src="/assets/cloned/svg/832f5bfbbd5a.svg" width="15" />
                      </div>
                      <div className="block justify-center items-center text-background text-lg font-medium leading-6 tracking-[-0.36px] max-lg:text-[1.0625rem] max-lg:leading-[1.4375rem]" data-ditto-id="style-div-31">
                        Soluciones completas de fisioterapia y estética
                      </div>
                    </div>
                  </div>
                </div>
              </div>
            </div>
          </div>
          <div className="w-320 h-[3.975rem] flex absolute top-[31.8625rem] left-0 items-start max-md:hidden md:max-lg:w-192 md:max-lg:h-[2.65rem] md:max-lg:bottom-2/5 md:max-lg:inset-x-0 md:max-lg:mt-7.5 md:max-lg:static md:max-lg:top-auto 2xl:w-480 2xl:top-[36.525rem]" data-ditto-id="style-div-32">
            <div className="h-full flex opacity-31 items-start shrink-0 transform-[matrix(1,0,0,1,-115.77,0)] md:max-lg:transform-[matrix(1,0,0,1,-59.73,0)] 2xl:transform-[matrix(1,0,0,1,-424.5,0)]" data-ditto-id="style-div-3">
              <div className="w-[25.15rem] h-full flex pr-2.5 shrink-0 md:max-lg:w-[270.5px]" data-ditto-id="style-div-33">
                <h1 className="basis-full shrink-0 flex pr-2.5 text-color-012 text-6xl font-semibold leading-[4rem] tracking-[-1.2px] whitespace-nowrap md:max-lg:text-[2.5rem] md:max-lg:leading-[2.625rem]" data-ditto-id="style-heading" data-component="heading">
                  Estética -
                </h1>
              </div>
              <div className="w-[24.75rem] h-full flex pr-2.5 shrink-0 md:max-lg:w-[16.5875rem]" data-ditto-id="style-div-10">
                <h1 className="basis-full shrink-0 flex pr-2.5 text-color-012 text-6xl font-semibold leading-[4rem] tracking-[-1.2px] whitespace-nowrap md:max-lg:text-[2.5rem] md:max-lg:leading-[2.625rem]" data-ditto-id="style-heading-2" data-component="heading">
                  Fisiospa -
                </h1>
              </div>
            </div>
            <div className="h-full flex opacity-31 items-start shrink-0 transform-[matrix(1,0,0,1,-1267.48,0)] md:max-lg:transform-[matrix(1,0,0,1,-834.343,0)] 2xl:transform-[matrix(1,0,0,1,-1576.21,0)]" data-ditto-id="style-div-4">
              {FeatureCard_data.map((d, i) => <FeatureCard key={i} d={d} styles={FeatureCard_styles[i]} />)}
            </div>
          </div>
          <div className="h-220 block absolute top-0 right-288 left-0 max-lg:hidden 2xl:h-160 2xl:top-67.5 2xl:right-[105.6rem]" style={{ backgroundImage: "linear-gradient(90deg, var(--color-004), var(--clr-8))" }} data-ditto-id="style-div-40" />
          <div className="h-220 block absolute top-0 right-0 left-288 max-lg:hidden 2xl:h-160 2xl:top-67.5 2xl:right-[105.6rem] 2xl:left-0" data-ditto-id="style-div-2" />
        </div>
      </section>
      <div className="block bg-surface" data-ditto-id="style-div-41">
        <section className="block pt-[7.0625rem] overflow-hidden max-lg:pt-[3.3125rem]" data-ditto-id="style-section">
          <div className="block max-w-407.5 px-[0.9375rem] mx-auto before:content-['_'] before:table before:w-0 before:h-0 before:text-foreground before:text-base before:leading-7 after:content-['_'] after:table after:w-0 after:h-0 after:text-foreground after:text-base after:leading-7" data-ditto-id="style-div-42">
            <div className="flex flex-col justify-start items-center" data-ditto-id="style-div-43">
              <div className="w-full max-w-212.5 block">
                <div className="flex pb-15 flex-col justify-start items-center text-center max-lg:pb-7.5">
                  <div className="block mb-[1.5625rem] max-lg:mb-[0.9375rem]" data-ditto-id="style-div-6">
                    <div className="flex justify-start items-center gap-[0.4rem]">
                      <div className="w-[0.3125rem] h-[0.3125rem] block bg-color-004" data-ditto-id="style-div-7" />
                      <div className="block text-color-001 text-lg leading-[1.75rem] tracking-[-0.54px] max-md:leading-[1.5625rem] max-md:[font-size:inherit] md:max-lg:text-[1.0625rem] md:max-lg:leading-[1.625rem]">
                        Quiénes
                      </div>
                      <div className="block text-lg leading-[1.75rem] tracking-[-0.54px] max-md:leading-[1.5625rem] max-md:[font-size:inherit] md:max-lg:text-[1.0625rem] md:max-lg:leading-[1.625rem]" data-ditto-id="style-div-8">
                        {" somos"}
                      </div>
                    </div>
                  </div>
                  <h2 className="block mb-[1.5625rem] text-color-001 text-[2.625rem] font-semibold leading-[3rem] tracking-[-0.84px] max-lg:mb-[0.9375rem] max-md:text-[1.5625rem] max-md:leading-[1.8125rem] md:max-lg:text-3xl md:max-lg:leading-[2.125rem]" data-component="heading">
                    Comprometidos con tu bienestar
                  </h2>
                  <p className="w-full max-w-99 block" data-ditto-id="style-p">
                    Atención ética y guiada por criterio profesional para tu salud integral.
                  </p>
                </div>
                <div className="flex justify-center gap-13.5 max-md:gap-5 md:max-lg:gap-10" data-ditto-id="style-div-24">
                  <div className="flex relative max-w-65 flex-col justify-start items-center flex-1 text-center" data-ditto-id="style-div-11">
                    <div className="flex items-start">
                      <div className="block text-color-001 text-6xl font-medium leading-[4rem] tracking-[-1.2px] max-md:text-[2.1875rem] max-md:leading-[2.3125rem] md:max-lg:text-[2.5rem] md:max-lg:leading-[2.625rem]">
                        6
                      </div>
                      <div className="block text-color-004 [font-family:Merriweather,_serif] text-3xl leading-10 max-md:text-[1.375rem] max-md:leading-[1.8125rem] md:max-lg:text-[1.625rem] md:max-lg:leading-[2.1875rem]">
                        +
                      </div>
                    </div>
                    <div className="w-full h-full block mt-5 mb-7 bg-border max-lg:mt-2.5 max-lg:mb-[1.4375rem]" />
                    <div className="w-full max-w-57.5 block text-color-001 text-lg font-medium leading-6 tracking-[-0.36px] max-lg:text-[1.0625rem] max-lg:leading-[1.4375rem]">
                      Años de experiencia
                    </div>
                  </div>
                  <div className="w-px block self-stretch bg-border max-md:hidden" />
                  <div className="flex relative max-w-65 flex-col justify-start items-center flex-1 text-center">
                    <div className="flex items-start">
                      <div className="block text-color-001 text-6xl font-medium leading-[4rem] tracking-[-1.2px] max-md:text-[2.1875rem] max-md:leading-[2.3125rem] md:max-lg:text-[2.5rem] md:max-lg:leading-[2.625rem]">
                        300
                      </div>
                      <div className="block text-color-004 [font-family:Merriweather,_serif] text-3xl leading-10 max-md:text-[1.375rem] max-md:leading-[1.8125rem] md:max-lg:text-[1.625rem] md:max-lg:leading-[2.1875rem]">
                        +
                      </div>
                    </div>
                    <div className="w-full h-full block mt-5 mb-7 bg-border max-lg:mt-2.5 max-lg:mb-[1.4375rem]" />
                    <div className="w-full max-w-57.5 block text-color-001 text-lg font-medium leading-6 tracking-[-0.36px] max-lg:text-[1.0625rem] max-lg:leading-[1.4375rem]">
                      Pacientes atendidas
                    </div>
                  </div>
                </div>
              </div>
              <div className="w-full border-b border-solid border-b-border flex py-30 justify-between items-start gap-12.5 grid-cols-[1fr_1fr_1fr_1fr_1fr_1fr] [grid-auto-columns:1fr] max-md:grid max-md:py-7.5 max-md:flex-col max-lg:items-center max-md:gap-4 max-md:grid-cols-[104.328px_104.328px_104.344px] max-lg:justify-items-center md:max-lg:pt-10 md:max-lg:pb-15 md:max-lg:flex-wrap md:max-lg:gap-7.5">
                {Logo_data.map((d, i) => <Logo key={i} d={d} />)}
              </div>
            </div>
          </div>
        </section>
        <section className="block py-30 flex-col gap-[3.8rem] max-md:pt-[3.3125rem] max-md:pb-15 max-md:gap-8 md:max-lg:py-15 md:max-lg:gap-7.5">
          <div className="block max-w-407.5 px-[0.9375rem] mx-auto before:content-['_'] before:table before:w-0 before:h-0 before:text-foreground before:text-base before:leading-7 after:content-['_'] after:table after:w-0 after:h-0 after:text-foreground after:text-base after:leading-7">
            <div className="flex flex-col items-start gap-12.5 max-md:gap-8 md:max-lg:gap-7.5">
              <div className="block">
                <h2 className="block text-color-001 text-[2.625rem] font-semibold leading-[3rem] tracking-[-0.84px] whitespace-nowrap max-md:text-[1.5625rem] max-md:leading-[1.8125rem] md:max-lg:text-3xl md:max-lg:leading-[2.125rem]" data-component="heading">
                  Qué tratamos
                </h2>
              </div>
              <div className="flex flex-col items-start self-stretch gap-15 max-md:gap-[2.8rem]">
                <div className="w-full block">
                  <div className="border-b border-solid border-b-border flex pb-15 justify-between items-stretch gap-7.5 max-md:flex-col max-md:gap-[2.1rem] max-md:grid-cols-[1fr_1fr] max-md:grid-rows-[auto] max-md:[grid-auto-columns:1fr] max-md:border-b-[0] max-md:border-initial max-md:border-b-[initial] max-md:pb-0">
                    <div className="block max-w-75 rounded-md flex-1 overflow-hidden max-md:max-w-none">
                      <img className="w-full h-[16.6875rem] block max-w-full overflow-clip object-cover aspect-[auto_300/247] align-middle max-md:h-71 md:max-lg:h-92.5" data-component="image" alt="tratamiento 1" height="247" sizes="300px" src="/assets/cloned/images/0ec1d1101d96.webp" srcSet="/assets/cloned/images/de442b7fa029.webp 500w, /assets/cloned/images/0ec1d1101d96.webp 600w" width="300" />
                    </div>
                    <div className="flex max-w-[28.8rem] -mt-1.5 flex-col justify-between items-start flex-1 gap-5 max-md:justify-center max-md:gap-[0.1rem] max-lg:max-w-none" data-ditto-id="style-div-65">
                      <div className="block max-lg:mb-[0.9375rem]">
                        <h3 className="block text-color-001 text-3xl font-semibold leading-9 tracking-[-0.6px] max-md:text-[1.375rem] max-md:leading-[1.625rem] md:max-lg:text-[1.625rem] md:max-lg:leading-[1.9375rem]" data-component="heading">
                          {"Estética facial "}
                          <span className="inline text-foreground">
                            y corporal
                          </span>
                        </h3>
                      </div>
                      <div className="flex flex-col items-start gap-7 max-md:gap-4">
                        <div className="block text-color-001 text-xl font-medium leading-6.5 tracking-[-0.4px] max-lg:text-lg max-lg:leading-[1.4375rem]">
                          Qué incluye
                        </div>
                        <p className="block">
                          Limpieza facial profunda, tratamientos faciales para acné, manchas, arrugas y flacidez, reducción de medidas, moldeamiento, maderoterapia y mesoterapia.
                        </p>
                      </div>
                    </div>
                    <div className="flex max-w-[21.5625rem] flex-col items-start flex-1 gap-[0.8rem] max-md:gap-4 max-md:col-start-[span_2] max-md:col-end-[span_2] max-md:row-start-[span_1] max-md:row-end-[span_1] max-md:max-w-none" id="w-node-_0563f2c7-ac9c-51ea-1cc5-c1241a05e84e-98efb413">
                      <div className="block max-w-20 max-md:hidden">
                        <img className="w-full h-20 block max-w-full overflow-clip object-cover aspect-[auto_80/80] align-middle" data-component="image" alt="Tratamiento estético" height="80" src="/assets/cloned/images/63035fb05fec.webp" width="80" />
                      </div>
                      <div className="flex flex-col items-stretch self-stretch max-md:gap-[0.9375rem]">
                        {MediaTile_data.map((d, i) => <MediaTile key={i} d={d} />)}
                      </div>
                    </div>
                  </div>
                </div>
                <div className="w-full block">
                  <div className="border-b border-solid border-b-border flex pb-15 justify-between items-stretch gap-7.5 max-md:flex-col max-md:gap-[2.1rem] max-md:grid-cols-[1fr_1fr] max-md:grid-rows-[auto] max-md:[grid-auto-columns:1fr] max-md:border-b-[0] max-md:border-initial max-md:border-b-[initial] max-md:pb-0">
                    <div className="block max-w-75 rounded-md flex-1 overflow-hidden max-md:max-w-none">
                      <img className="w-full h-[16.6875rem] block max-w-full overflow-clip object-cover aspect-[auto_300/247] align-middle max-md:h-71 md:max-lg:h-[20.1875rem]" data-component="image" alt="tratamiento 2" height="247" sizes="300px" src="/assets/cloned/images/39d039981f5a.webp" srcSet="/assets/cloned/images/0cae13c635da.webp 500w, /assets/cloned/images/39d039981f5a.webp 600w" width="300" />
                    </div>
                    <div className="flex max-w-[28.8rem] -mt-1.5 flex-col justify-between items-start flex-1 gap-5 max-md:justify-center max-md:gap-[0.1rem] max-lg:max-w-none">
                      <div className="block max-lg:mb-[0.9375rem]">
                        <h3 className="block text-color-001 text-3xl font-semibold leading-9 tracking-[-0.6px] max-md:text-[1.375rem] max-md:leading-[1.625rem] md:max-lg:text-[1.625rem] md:max-lg:leading-[1.9375rem]" data-component="heading">
                          {"Tratamiento "}
                          <span className="inline text-foreground">
                            para alopecia
                          </span>
                        </h3>
                      </div>
                      <div className="flex flex-col items-start gap-7 max-md:gap-4">
                        <div className="block text-color-001 text-xl font-medium leading-6.5 tracking-[-0.4px] max-lg:text-lg max-lg:leading-[1.4375rem]">
                          Qué incluye
                        </div>
                        <p className="block">
                          Tratamiento para la alopecia, reducción de papada, tratamiento para ojeras y extracción de lunares y verrugas.
                        </p>
                      </div>
                    </div>
                    <div className="flex max-w-[21.5625rem] flex-col items-start flex-1 gap-[0.8rem] max-md:gap-4 max-md:col-start-[span_2] max-md:col-end-[span_2] max-md:row-start-[span_1] max-md:row-end-[span_1] max-md:max-w-none" id="w-node-_6221c854-bd3f-5425-2665-7e740e34cf7c-98efb413">
                      <div className="block max-w-20 max-md:hidden">
                        <img className="w-full h-20 block max-w-full overflow-clip object-cover aspect-[auto_80/80] align-middle" data-component="image" alt={"Tratamiento para alopecia"} height="80" src="/assets/cloned/images/52fdedd8e04f.webp" width="80" />
                      </div>
                      <div className="flex flex-col items-stretch self-stretch max-md:gap-[0.9375rem]">
                        {MediaTile_data2.map((d, i) => <MediaTile key={i} d={d} />)}
                      </div>
                    </div>
                  </div>
                </div>
              </div>
            </div>
          </div>
        </section>
        <section className="block pb-30 max-lg:pb-15">
          <div className="block pb-22 max-md:hidden md:max-lg:pb-10">
            <div className="block text-clr-20 text-[5.5625rem] leading-[5.5625rem] text-center md:max-lg:text-[3.375rem] md:max-lg:leading-[3.375rem] 2xl:text-[8.9375rem] 2xl:leading-[8.9375rem]">
              Tratamientos recientes
            </div>
          </div>
          <div className="block max-w-407.5 px-[0.9375rem] mx-auto before:content-['_'] before:table before:w-0 before:h-0 before:text-foreground before:text-base before:leading-7 after:content-['_'] after:table after:w-0 after:h-0 after:text-foreground after:text-base after:leading-7">
            <div className="block">
              <div className="grid gap-12.5 [grid-auto-columns:1fr] grid-cols-3 max-lg:gap-7.5 max-md:grid-cols-1">
                {MediaTile2_data.map((d, i) => <MediaTile2 key={i} d={d} styles={MediaTile2_styles[i]} />)}
                <div className="flex pt-[3.4375rem] pr-10 flex-col justify-end items-stretch max-lg:order-[9999] max-md:pt-0 max-lg:pr-0 md:max-lg:pb-6" id="w-node-_08d77223-90d3-19c6-cf28-0b76b3b43382-98efb413">
                  <div className="border-t border-solid border-t-border flex pt-15 justify-start items-end gap-5 max-md:border-t-[0] max-md:border-initial max-md:border-t-[initial] max-md:pt-0 md:max-lg:pt-7.5">
                    <div className="flex max-w-42.5 max-md:hidden md:max-lg:max-w-[8.3rem]" data-ditto-id="style-div-70">
                      {Logo2_data.map((d, i) => <Logo2 key={i} d={d} styles={Logo2_styles[i]} />)}
                    </div>
                    <div className="block -mb-2 max-md:mb-0">
                      <div className="block text-color-001 text-[2.625rem] font-semibold leading-[3rem] tracking-[-0.84px] max-md:text-[1.5625rem] max-md:leading-[1.8125rem] md:max-lg:text-3xl md:max-lg:leading-[2.125rem]">
                        300+
                      </div>
                      <div className="block" data-ditto-id="style-div-72">
                        Pacientes satisfechas
                      </div>
                    </div>
                  </div>
                </div>
                <div className="flex rounded-md flex-col items-start">
                  <div className="fx-flip h-full block relative rounded-md transform-[matrix3d(-1,0,0,0,0,1,0,0,0,0,-1,0,0,0,0,1)] origin-[191.664px_203.805px] max-md:origin-[172.5px_170.398px] md:max-lg:origin-[113px_213.305px] 2xl:origin-[250px_203.805px]">
                    <div className="h-full flex relative z-9 pt-8.5 pb-7.5 px-10 rounded-[5px] flex-col justify-between items-stretch gap-44 overflow-hidden bg-background max-lg:pt-[1.9rem] max-lg:px-5 max-md:gap-[6.7rem]">
                      <div className="flex flex-col items-start gap-7 max-md:pb-4">
                        <div className="block max-w-32.5">
                          <div className="block text-color-001 text-xl font-medium leading-6.5 tracking-[-0.4px] max-lg:text-lg max-lg:leading-[1.4375rem]">
                            {"Moldeamiento "}
                            <span className="inline text-foreground">
                              y tonificación
                            </span>
                          </div>
                        </div>
                        <p className="block mb-2.5 max-md:mb-0 md:max-lg:mb-[0.3125rem]">
                          Estética avanzada y fisioterapia profesional en un solo lugar.
                        </p>
                      </div>
                      <div className="block relative">
                        <a className="flex relative max-w-full justify-between cursor-pointer" data-component="link" href="/service">
                          <div className="block -mb-[0.4rem] text-color-001 font-medium max-lg:-mb-[0.1rem]">
                            Explorar
                          </div>
                          <div className="w-2.5 h-2.5 block z-2">
                            <img className="w-full h-2.5 block max-w-full overflow-clip object-cover aspect-[auto_10/10] align-middle" data-component="image" alt="" height="10" src="/assets/cloned/svg/c81dc04c407a.svg" width="10" />
                          </div>
                        </a>
                      </div>
                    </div>
                    <div className="fx-flip-back h-full block absolute top-0 inset-x-0 z-2 rounded-[5px] gap-15 overflow-hidden transform-[matrix3d(-1,0,0,0,0,1,0,0,0,0,-1,0,0,0,-1,1)] origin-[191.664px_203.805px] max-lg:gap-7.5 max-md:origin-[172.5px_170.398px] md:max-lg:origin-[113px_213.305px] 2xl:origin-[250px_203.805px]">
                      <div className="h-full block overflow-hidden">
                        <img className="w-full h-102 block max-w-full overflow-clip object-cover aspect-[auto_410/420] align-middle max-md:h-[21.3125rem] md:max-lg:h-[26.6875rem]" data-component="image" alt="imagen de servicio" height="420" sizes="410px" src="/assets/cloned/images/1ad9e0ab88ef.webp" srcSet="/assets/cloned/images/09b9edac774e.webp 500w, /assets/cloned/images/a6a6ba9093fd.webp 800w, /assets/cloned/images/1ad9e0ab88ef.webp 820w" width="410" />
                      </div>
                      <div className="h-full flex absolute top-0 inset-x-0 pb-[2.1875rem] pl-10 flex-col justify-end items-start max-lg:pl-5" style={{ backgroundImage: "linear-gradient(var(--clr-8) 55%, var(--clr-21))" }}>
                        <div className="block text-background text-xl font-medium leading-6.5 tracking-[-0.4px] max-lg:text-lg max-lg:leading-[1.4375rem]">
                          Tonificación (flacidez)
                        </div>
                      </div>
                    </div>
                  </div>
                </div>
                <div className="flex rounded-md flex-col items-start">
                  <div className="fx-flip h-full block relative rounded-md transform-[matrix3d(-1,0,0,0,0,1,0,0,0,0,-1,0,0,0,0,1)] origin-[191.672px_203.805px] max-md:origin-[172.5px_170.398px] md:max-lg:origin-[113px_213.305px] 2xl:origin-[250px_203.805px]">
                    <div className="h-full flex relative z-9 pt-8.5 pb-7.5 px-10 rounded-[5px] flex-col justify-between items-stretch gap-44 overflow-hidden bg-background max-lg:pt-[1.9rem] max-lg:px-5 max-md:gap-[6.7rem]">
                      <div className="flex flex-col items-start gap-7 max-md:pb-4">
                        <div className="block max-w-32.5">
                          <div className="block text-color-001 text-xl font-medium leading-6.5 tracking-[-0.4px] max-lg:text-lg max-lg:leading-[1.4375rem]">
                            {"Tratamiento "}
                            <span className="inline text-foreground">
                              para ojeras
                            </span>
                          </div>
                        </div>
                        <p className="block mb-2.5 max-md:mb-0 md:max-lg:mb-[0.3125rem]">
                          Estética avanzada y fisioterapia profesional en un solo lugar.
                        </p>
                      </div>
                      <div className="block relative">
                        <a className="flex relative max-w-full justify-between cursor-pointer" data-component="link" href="/service">
                          <div className="block -mb-[0.4rem] text-color-001 font-medium max-lg:-mb-[0.1rem]">
                            Explorar
                          </div>
                          <div className="w-2.5 h-2.5 block z-2">
                            <img className="w-full h-2.5 block max-w-full overflow-clip object-cover aspect-[auto_10/10] align-middle" data-component="image" alt="" height="10" src="/assets/cloned/svg/c81dc04c407a.svg" width="10" />
                          </div>
                        </a>
                      </div>
                    </div>
                    <div className="fx-flip-back h-full block absolute top-0 inset-x-0 z-2 rounded-[5px] gap-15 overflow-hidden transform-[matrix3d(-1,0,0,0,0,1,0,0,0,0,-1,0,0,0,-1,1)] origin-[191.672px_203.805px] max-lg:gap-7.5 max-md:origin-[172.5px_170.398px] md:max-lg:origin-[113px_213.305px] 2xl:origin-[250px_203.805px]">
                      <div className="h-full block overflow-hidden">
                        <img className="w-full h-102 block max-w-full overflow-clip object-cover aspect-[auto_410/420] align-middle max-md:h-[21.3125rem] md:max-lg:h-[26.6875rem]" data-component="image" alt="imagen de servicio" height="420" sizes="410px" src="/assets/cloned/images/2ece24385b23.webp" srcSet="/assets/cloned/images/5fbd729c8108.webp 500w, /assets/cloned/images/0439a2d4d805.webp 800w, /assets/cloned/images/2ece24385b23.webp 820w" width="410" />
                      </div>
                      <div className="h-full flex absolute top-0 inset-x-0 pb-[2.1875rem] pl-10 flex-col justify-end items-start max-lg:pl-5" style={{ backgroundImage: "linear-gradient(var(--clr-8) 55%, var(--clr-21))" }}>
                        <div className="block text-background text-xl font-medium leading-6.5 tracking-[-0.4px] max-lg:text-lg max-lg:leading-[1.4375rem]">
                          Tratamiento para ojeras
                        </div>
                      </div>
                    </div>
                  </div>
                </div>
              </div>
            </div>
          </div>
        </section>
        <section className="block pb-30 bg-surface max-lg:pb-15">
          <div className="block max-w-407.5 px-[0.9375rem] mx-auto before:content-['_'] before:table before:w-0 before:h-0 before:text-foreground before:text-base before:leading-7 after:content-['_'] after:table after:w-0 after:h-0 after:text-foreground after:text-base after:leading-7">
            <div className="flex py-30 px-[0.9375rem] rounded-[30px] flex-col justify-center items-center bg-color-003 [background-position:50%_0px] bg-no-repeat max-lg:py-15 max-md:items-stretch" style={{ backgroundImage: "url(\"/assets/cloned/svg/62b3bb1cc334.svg\")" }}>
              <div className="block max-w-162.5 pb-[1.5625rem] justify-center items-center text-center max-md:max-w-none">
                <h2 className="block text-background text-[2.625rem] font-semibold leading-[3rem] tracking-[-0.84px] max-md:text-[1.5625rem] max-md:leading-[1.8125rem] md:max-lg:text-3xl md:max-lg:leading-[2.125rem]" data-component="heading">
                  Agenda tu valoración y empieza tu tratamiento
                </h2>
              </div>
              <div className="flex relative z-1 mb-7.5 items-start gap-12.5 max-md:grid max-md:mb-6 max-md:flex-wrap max-md:justify-center max-md:gap-5 max-md:grid-cols-[147.5px_147.5px] max-md:[grid-auto-columns:1fr] md:max-lg:gap-7.5">
                {Logo3_data.map((d, i) => <Logo3 key={i} d={d} styles={Logo3_styles[i]} />)}
              </div>
              <div className="w-full max-w-[36.9375rem] flex flex-col justify-start items-center gap-7.5 text-center max-md:gap-4">
                <p className="block opacity-0 text-background max-lg:opacity-[initial] 2xl:opacity-[initial]">
                  Valoración, tratamientos avanzados y atención personalizada para resultados reales y duraderos.
                </p>
                <div className="flex items-start gap-7.5 max-md:flex-wrap max-md:justify-center max-md:gap-y-5">
                  <a className="h-[2.7125rem] border border-solid border-surface-2 flex relative z-0 max-w-full pt-[0.5625rem] pb-2.5 px-5 rounded-[50px] justify-between items-center gap-2.5 overflow-hidden bg-surface-4 cursor-pointer" data-component="link" href="https://wa.me/593979898964" target="_blank" rel="noopener noreferrer">
                    <div className="h-[1.4rem] block relative z-1 overflow-hidden max-md:shrink-0">
                      <div className="block text-background leading-6 whitespace-nowrap">
                        Agenda tu cita
                      </div>
                      <div className="block text-background leading-6 whitespace-nowrap">
                        Agenda tu cita
                      </div>
                    </div>
                    <div className="w-[213.3px] h-[2.6375rem] flex absolute top-0 left-0 min-w-0 rounded-[50px] justify-center items-center bg-color-001 transform-[matrix(1,0,0,1,0,42.2031)] pointer-events-none" />
                    <div className="w-[0.5875rem] h-[0.6rem] flex relative z-1 mt-0.5 justify-center items-center max-md:shrink-0">
                      <img className="w-full h-2.5 block max-w-full overflow-clip object-cover aspect-[auto_9/9] align-middle" data-component="image" alt="flecha" height="9" src="/assets/cloned/svg/97bfaa7e2654.svg" width="9" />
                    </div>
                  </a>
                </div>
              </div>
            </div>
          </div>
        </section>
        <section className="block pb-30 overflow-hidden max-lg:pb-15">
          <div className="block max-w-407.5 px-[0.9375rem] mx-auto before:content-['_'] before:table before:w-0 before:h-0 before:text-foreground before:text-base before:leading-7 after:content-['_'] after:table after:w-0 after:h-0 after:text-foreground after:text-base after:leading-7">
            <div className="block">
              <div className="flex items-start">
                <div className="flex justify-start items-center gap-[0.4rem]">
                  <div className="w-[0.3125rem] h-[0.3125rem] block bg-color-004" />
                  <div className="block text-color-001 text-lg leading-[1.75rem] tracking-[-0.54px] max-md:leading-[1.5625rem] max-md:[font-size:inherit] md:max-lg:text-[1.0625rem] md:max-lg:leading-[1.625rem]">
                    Encuentra
                  </div>
                  <div className="block text-lg leading-[1.75rem] tracking-[-0.54px] max-md:leading-[1.5625rem] max-md:[font-size:inherit] md:max-lg:text-[1.0625rem] md:max-lg:leading-[1.625rem]">
                    nuestro centro
                  </div>
                </div>
              </div>
            </div>
          </div>
          <div className="flex pt-15 px-[0.9375rem] flex-col justify-start items-center max-md:grid max-lg:pt-10 max-md:gap-4 max-md:grid-cols-[345px] max-md:[grid-auto-columns:1fr]">
            {MediaTile3_data.map((d, i) => <MediaTile3 key={i} d={d} styles={MediaTile3_styles[i]} />)}
          </div>
        </section>
      </div>
      <section className="block py-30 max-lg:py-15">
        <div className="block max-w-407.5 px-[0.9375rem] mx-auto before:content-['_'] before:table before:w-0 before:h-0 before:text-foreground before:text-base before:leading-7 after:content-['_'] after:table after:w-0 after:h-0 after:text-foreground after:text-base after:leading-7">
          <div className="block">
            <div className="flex justify-between items-start gap-7.5 max-md:grid max-md:gap-[2.1rem] max-md:grid-cols-[345px] max-md:[grid-auto-columns:1fr] md:max-lg:pt-4">
              <div className="block max-w-[45.5625rem] rounded-md flex-1 overflow-hidden max-md:flex max-md:max-w-none">
                <img className="w-auto h-174.5 block max-w-full overflow-clip object-cover aspect-[auto_520/595] align-middle max-md:h-[24.6875rem] md:max-lg:h-[25.3125rem] 2xl:h-208.5" data-component="image" alt="imagen de preguntas frecuentes" height="595" sizes="(max-width: 479px) 100vw, 520px" src="/assets/cloned/images/e1a60e9bb150.webp" srcSet="/assets/cloned/images/823e8e74a81f.webp 500w, /assets/cloned/images/884f48f1bec6.webp 800w, /assets/cloned/images/e1a60e9bb150.webp 1040w" width="520" />
              </div>
              <div className="block max-w-[45.4375rem] self-center flex-1 max-md:max-w-none">
                <div className="flex flex-col items-start">
                  <div className="block mb-[1.5625rem] max-lg:mb-[0.9375rem]">
                    <div className="flex justify-start items-center gap-[0.4rem]">
                      <div className="w-[0.3125rem] h-[0.3125rem] block bg-color-004" />
                      <div className="block text-color-001 text-lg leading-[1.75rem] tracking-[-0.54px] max-md:leading-[1.5625rem] max-md:[font-size:inherit] md:max-lg:text-[1.0625rem] md:max-lg:leading-[1.625rem]">
                        Por qué
                      </div>
                      <div className="block text-lg leading-[1.75rem] tracking-[-0.54px] max-md:leading-[1.5625rem] max-md:[font-size:inherit] md:max-lg:text-[1.0625rem] md:max-lg:leading-[1.625rem]">
                        elegirnos
                      </div>
                    </div>
                  </div>
                  <div className="w-full max-w-[42.2rem] block">
                    <h2 className="block mb-[1.5625rem] text-color-001 text-[2.625rem] font-semibold leading-[3rem] tracking-[-0.84px] max-lg:mb-[0.9375rem] max-md:text-[1.5625rem] max-md:leading-[1.8125rem] md:max-lg:text-3xl md:max-lg:leading-[2.125rem]" data-component="heading">
                      Por qué elegir Medical Livesthetic
                    </h2>
                  </div>
                  <div className="block mb-[4.0625rem] max-lg:mb-7.5">
                    <p className="block">
                      Combinamos profesionales certificados, tecnología avanzada, práctica ética y planes personalizados para lograr resultados seguros y efectivos.
                    </p>
                  </div>
                </div>
                <div className="flex rounded-[15px] flex-col items-stretch gap-8.5 max-lg:gap-6">
                  <div className="border-b border-solid border-b-border flex relative z-900 pb-2.5 flex-col justify-between items-stretch text-left">
                    <div className="w-full flex relative mb-[1.5625rem] justify-between items-center gap-2.5 align-top text-color-002 whitespace-nowrap text-nowrap cursor-pointer max-md:mb-4 max-md:gap-8 md:max-lg:mb-[1.0625rem]" data-component="button" aria-controls="w-dropdown-list-2" aria-expanded="false" aria-haspopup="menu" id="w-dropdown-toggle-2" role="button">
                      <div className="block text-color-001 text-xl font-medium leading-6.5 tracking-[-0.4px] whitespace-normal max-lg:text-lg max-lg:leading-[1.4375rem]">
                        Tratamientos avanzados con excelencia clínica.
                      </div>
                      <div className="flex max-w-3 transform-[matrix(-1,0,0,-1,0,0)] origin-[6px_3.42188px] max-md:origin-[5.24219px_2.99219px] md:max-lg:origin-[5.76562px_3.28906px]">
                        <img className="w-full h-[0.4375rem] block max-w-full overflow-clip object-cover aspect-[auto_12/6] align-middle max-md:h-1.5" data-component="image" alt="" height="6" src="/assets/cloned/svg/a446313568d7.svg" width="12" />
                      </div>
                    </div>
                    <nav className="block min-w-full overflow-hidden bg-clr-15" data-component="nav" aria-labelledby="w-dropdown-toggle-2" id="w-dropdown-list-2">
                      <div className="w-full max-w-157.5 block pb-5.5 max-lg:pb-3.5">
                        <p className="block">
                          Programas de tratamiento estructurados para lograr precisión, seguridad y bienestar a largo plazo.
                        </p>
                      </div>
                    </nav>
                  </div>
                  <div className="w-full border-b border-solid border-b-border flex relative z-900 pb-2.5 flex-col justify-between items-stretch text-left">
                    <div className="w-full flex relative mb-[1.5625rem] justify-between items-center gap-2.5 align-top text-color-002 whitespace-nowrap text-nowrap cursor-pointer max-md:mb-4 max-md:gap-8 md:max-lg:mb-[1.0625rem]" data-component="button" aria-controls="w-dropdown-list-3" aria-expanded="false" aria-haspopup="menu" id="w-dropdown-toggle-3" role="button">
                      <div className="block text-color-001 text-xl font-medium leading-6.5 tracking-[-0.4px] whitespace-normal max-lg:text-lg max-lg:leading-[1.4375rem]">
                        Profesionales de confianza con resultados comprobados.
                      </div>
                      <div className="flex max-w-3">
                        <img className="w-full h-[0.4375rem] block max-w-full overflow-clip object-cover aspect-[auto_12/6] align-middle" data-component="image" alt="" height="6" src="/assets/cloned/svg/a446313568d7.svg" width="12" />
                      </div>
                    </div>
                  </div>
                  <div className="w-full border-b border-solid border-b-border flex relative z-900 pb-2.5 flex-col justify-between items-stretch text-left">
                    <div className="w-full flex relative mb-[1.5625rem] justify-between items-center gap-2.5 align-top text-color-002 whitespace-nowrap text-nowrap cursor-pointer max-md:mb-4 max-md:gap-8 md:max-lg:mb-[1.0625rem]" data-component="button" aria-controls="w-dropdown-list-4" aria-expanded="false" aria-haspopup="menu" id="w-dropdown-toggle-4" role="button">
                      <div className="block text-color-001 text-xl font-medium leading-6.5 tracking-[-0.4px] whitespace-normal max-lg:text-lg max-lg:leading-[1.4375rem]">
                        Atención personalizada respaldada por experiencia.
                      </div>
                      <div className="flex max-w-3">
                        <img className="w-full h-[0.4375rem] block max-w-full overflow-clip object-cover aspect-[auto_12/6] align-middle" data-component="image" alt="" height="6" src="/assets/cloned/svg/a446313568d7.svg" width="12" />
                      </div>
                    </div>
                  </div>
                </div>
              </div>
            </div>
          </div>
        </div>
      </section>
      <section className="block py-30 overflow-hidden bg-surface max-lg:py-15">
        <div className="block max-w-407.5 px-[0.9375rem] mx-auto before:content-['_'] before:table before:w-0 before:h-0 before:text-foreground before:text-base before:leading-7 after:content-['_'] after:table after:w-0 after:h-0 after:text-foreground after:text-base after:leading-7">
          <div className="flex items-start">
            <div className="flex justify-start items-center gap-[0.4rem]">
              <div className="w-[0.3125rem] h-[0.3125rem] block bg-color-004" />
              <div className="block text-color-001 text-lg leading-[1.75rem] tracking-[-0.54px] max-md:leading-[1.5625rem] max-md:[font-size:inherit] md:max-lg:text-[1.0625rem] md:max-lg:leading-[1.625rem]">
                Lo que dicen
              </div>
              <div className="block text-lg leading-[1.75rem] tracking-[-0.54px] max-md:leading-[1.5625rem] max-md:[font-size:inherit] md:max-lg:text-[1.0625rem] md:max-lg:leading-[1.625rem]">
                nuestras pacientes
              </div>
            </div>
          </div>
          <div className="block pt-12.5 max-lg:pt-8">
            <div className="h-[34.4375rem] block relative clear-both text-center max-md:h-[868.1px] max-lg:flex max-lg:flex-col md:max-lg:h-[27.525rem]" aria-label="carrusel" role="region">
              <div className="w-full max-w-267.5 h-full block relative z-1 whitespace-nowrap text-nowrap" id="w-slider-mask-0">
                <div className="w-full inline-block relative mr-12.5 align-top text-left whitespace-normal" aria-label="1 de 6" role="group">
                  <div className="flex justify-between items-center gap-12.5 max-md:grid max-lg:items-stretch max-lg:gap-7.5 max-md:grid-cols-[345px] max-md:[grid-auto-columns:1fr]">
                    <div className="block max-w-102.5 rounded-[5px] flex-1 overflow-hidden max-md:self-stretch max-md:max-w-none">
                      <img className="w-full h-[34.4375rem] block max-w-full overflow-clip object-cover aspect-[auto_410/551] align-middle max-md:h-116 md:max-lg:h-110" data-component="image" alt="Paciente" height="551" sizes="(max-width: 479px) 100vw, 410px" src="/assets/cloned/images/90e528970344.webp" srcSet="/assets/cloned/images/b6e4b25036a7.webp 500w, /assets/cloned/images/6e996eb39a39.webp 800w, /assets/cloned/images/90e528970344.webp 820w" width="410" />
                    </div>
                    <div className="flex relative max-w-157.5 py-20 px-[3.5625rem] rounded-[5px] flex-col justify-center items-start self-stretch flex-1 bg-background max-lg:pt-10 max-lg:pb-8.5 max-md:px-5 md:max-lg:px-7.5">
                      <div className="w-[2.8125rem] block mb-13.5 max-lg:mb-6.5">
                        <img className="w-full h-9.5 block max-w-full overflow-clip object-cover aspect-[auto_45/38] align-middle" data-component="image" alt="" height="38" src="/assets/cloned/svg/9bef580093cb.svg" width="45" />
                      </div>
                      <div className="block mb-[2.9375rem] max-lg:mb-[1.1875rem]">
                        <h3 className="block text-color-001 text-3xl font-semibold leading-9 tracking-[-0.6px] max-md:text-[1.375rem] max-md:leading-[1.625rem] md:max-lg:text-[1.625rem] md:max-lg:leading-[1.9375rem]" data-component="heading">
                          «Noté un cambio real en mi piel después del plan personalizado. La atención fue excelente de principio a fin.»
                        </h3>
                      </div>
                      <div className="flex flex-col items-start gap-[1.1875rem] max-md:gap-y-2.5 max-md:gap-x-4 md:max-lg:gap-4">
                        <div className="block text-color-001 text-lg font-medium leading-6 tracking-[-0.36px] whitespace-nowrap max-lg:text-[1.0625rem] max-lg:leading-[1.4375rem]">
                          Sofía M.
                        </div>
                        <div className="block -mb-[0.4rem] text-color-001 max-lg:-mb-[0.1rem]">
                          Parque Valladolid
                        </div>
                      </div>
                    </div>
                  </div>
                </div>
                <div className="w-full inline-block relative mr-12.5 align-top text-left whitespace-normal" aria-hidden="true" aria-label="2 de 6" role="group">
                  <div className="flex justify-between items-center gap-12.5 max-md:grid max-lg:items-stretch max-lg:gap-7.5 max-md:grid-cols-[345px] max-md:[grid-auto-columns:1fr]" aria-hidden="true">
                    <div className="block max-w-102.5 rounded-[5px] flex-1 overflow-hidden max-md:self-stretch max-md:max-w-none" aria-hidden="true">
                      <img className="w-full h-[34.4375rem] block max-w-full overflow-clip object-cover aspect-[auto_410/551] align-middle max-md:h-116 md:max-lg:h-110" data-component="image" alt="Paciente" aria-hidden="true" height="551" src="/assets/cloned/images/1d00a024552e.avif" width="410" />
                    </div>
                    <div className="flex relative max-w-157.5 py-20 px-[3.5625rem] rounded-[5px] flex-col justify-center items-start self-stretch flex-1 bg-background max-lg:pt-10 max-lg:pb-8.5 max-md:px-5 md:max-lg:px-7.5" aria-hidden="true">
                      <div className="w-[2.8125rem] block mb-13.5 max-lg:mb-6.5" aria-hidden="true">
                        <img className="w-full h-9.5 block max-w-full overflow-clip object-cover aspect-[auto_45/38] align-middle" alt="" aria-hidden="true" height="38" src="/assets/cloned/svg/9bef580093cb.svg" width="45" />
                      </div>
                      <div className="block mb-[2.9375rem] max-lg:mb-[1.1875rem]" aria-hidden="true">
                        <h3 className="block text-color-001 text-3xl font-semibold leading-9 tracking-[-0.6px] max-md:text-[1.375rem] max-md:leading-[1.625rem] md:max-lg:text-[1.625rem] md:max-lg:leading-[1.9375rem]" aria-hidden="true">
                          «Llegué con dolor lumbar de años. El plan que me armaron fue preciso y efectivo: hoy me muevo sin molestias.»
                        </h3>
                      </div>
                      <div className="flex flex-col items-start gap-[1.1875rem] max-md:gap-y-2.5 max-md:gap-x-4 md:max-lg:gap-4" aria-hidden="true">
                        <div className="block text-color-001 text-lg font-medium leading-6 tracking-[-0.36px] whitespace-nowrap max-lg:text-[1.0625rem] max-lg:leading-[1.4375rem]" aria-hidden="true">
                          Luis C.
                        </div>
                        <div className="block -mb-[0.4rem] text-color-001 max-lg:-mb-[0.1rem]" aria-hidden="true">
                          Cuenca
                        </div>
                      </div>
                    </div>
                  </div>
                </div>
                <div className="w-px h-px block absolute -m-px overflow-hidden" aria-atomic="true" aria-live="off" />
              </div>
              <div className="w-10 h-10 block absolute -top-15 right-0 z-4 justify-center items-center overflow-hidden text-background text-[2.5rem] bg-color-003 cursor-pointer max-lg:min-w-0" data-component="button" aria-controls="w-slider-mask-0" aria-label="siguiente" role="button">
                <div className="w-10 h-full flex absolute top-0 left-0 p-[0.9rem] justify-center items-center">
                  <div className="w-2 h-full flex absolute top-0 right-3.5 z-1 min-w-0 max-w-2 flex-col justify-center items-center [filter:invert(0)]">
                    <div className="block">
                      <img className="w-full h-3.5 block max-w-full overflow-clip object-cover align-middle" data-component="image" alt="" src="/assets/cloned/svg/3e8b2fde4e1b.svg" />
                    </div>
                  </div>
                </div>
              </div>
            </div>
          </div>
        </div>
      </section>
      <section className="block py-30 max-lg:py-15">
        <div className="block max-w-407.5 px-[0.9375rem] mx-auto before:content-['_'] before:table before:w-0 before:h-0 before:text-foreground before:text-base before:leading-7 after:content-['_'] after:table after:w-0 after:h-0 after:text-foreground after:text-base after:leading-7">
          <div className="flex flex-col justify-start items-center max-md:items-stretch max-md:gap-6">
            <div className="w-full max-w-136 flex mb-12.5 px-[0.9375rem] flex-col justify-start items-center gap-7.5 text-center max-lg:mb-7.5 max-lg:gap-[1.5625rem]">
              <div className="block max-w-12.5 max-md:max-w-10">
                <img className="w-full h-12.5 block max-w-full overflow-clip object-cover aspect-[auto_50/50] align-middle max-md:h-10" data-component="image" alt="" height="50" src="/assets/cloned/svg/4dfaa84db602.svg" width="50" />
              </div>
              <h2 className="block text-color-001 text-[2.625rem] font-semibold leading-[3rem] tracking-[-0.84px] max-md:text-[1.5625rem] max-md:leading-[1.8125rem] md:max-lg:text-3xl md:max-lg:leading-[2.125rem]" data-component="heading">
                Síguenos y mantente en contacto
              </h2>
            </div>
            <div className="w-312.5 flex items-start shrink-0 gap-12.5 max-lg:hidden 2xl:w-400">
              {MediaTile5_data.map((d, i) => <MediaTile5 key={i} d={d} styles={MediaTile5_styles[i]} />)}
            </div>
          </div>
        </div>
        <div className="hidden items-start self-stretch overflow-hidden max-lg:flex">
          <div className="flex items-start shrink-0 transform-[none] max-lg:w-330 max-md:grid-cols-[1fr_1fr] max-md:grid-rows-[auto_auto] max-md:[grid-auto-columns:1fr] max-md:transform-[matrix(1,0,0,1,-255.182,0)] md:max-lg:transform-[matrix(1,0,0,1,-442.913,0)]">
            <div className="block min-w-0 max-w-82.5 px-[0.9375rem] shrink-0 max-lg:w-82.5">
              <div className="block relative max-w-75 mt-10 rounded-[0.3px] shrink-0 overflow-hidden max-md:max-w-none">
                <img className="w-full h-full block max-w-full overflow-clip object-cover aspect-[auto_300/360] align-middle max-lg:h-90" alt="Publicación de Instagram" height="360" sizes="300px" src="/assets/cloned/images/3a64c1d70e79.webp" srcSet="/assets/cloned/images/71725079b07d.webp 500w, /assets/cloned/images/3a64c1d70e79.webp 600w" width="300" />
              </div>
            </div>
            {Logo4_data.map((d, i) => <Logo4 key={i} d={d} styles={Logo4_styles[i]} />)}
          </div>
        </div>
      </section>
    </>
  );
}
