import "./ditto.css";
// Generated by clone-site. Do not edit by hand.
export default function Page() {
  return (
    <>
      <div className="h-200 min-h-screen flex max-w-full max-h-full pt-[12.2375rem] pb-30 px-[0.9375rem] justify-center items-center bg-surface max-md:h-203 max-lg:pt-25 max-lg:pb-15 max-md:overflow-hidden md:max-lg:h-256 2xl:h-270" data-ditto-id="style-div-5">
        <div className="w-[68%] block pt-[7.0625rem] pb-30 px-[6.3125rem] rounded-md flex-col text-center bg-background max-lg:w-full max-lg:pt-[3.3125rem] max-lg:pb-15 max-md:px-[0.9375rem] 2xl:w-[45%]" data-ditto-id="style-div-13">
          <form className="flex flex-col justify-start items-center gap-7.5" aria-label="Email Form" id="email-form" name="email-form">
            <div className="w-full max-w-133.5 flex flex-col justify-start items-center gap-7.5">
              <div className="flex max-w-133.5 flex-col justify-start items-center">
                <h2 className="block mb-[1.5625rem] text-color-001 text-[2.625rem] font-semibold leading-[3rem] tracking-[-0.84px] max-lg:mb-[0.9375rem] max-md:text-[1.5625rem] max-md:leading-[1.8125rem] md:max-lg:text-3xl md:max-lg:leading-[2.125rem]" data-component="heading">
                  Password protected
                </h2>
                <p className="block">
                  This page is password protected. If you are the website admin, or have access to this page, please type your password below.
                </p>
              </div>
              <label className="hidden min-w-0 mb-[0.3125rem] font-bold cursor-default" htmlFor="pass">
                Password
              </label>
              <div className="w-full max-w-[20.3125rem] flex flex-col justify-center items-center" data-ditto-id="style-div">
                <div className="w-full block relative rounded-[60px] overflow-hidden">
                  <input className="w-full h-[2.6875rem] border border-solid border-color-013 block py-2 px-[1.5625rem] rounded-[60px] overflow-clip align-middle text-sm leading-5 text-start bg-background cursor-text 2xl:border-color-010" data-ditto-id="style-pass" data-component="input" id="pass" name="pass" placeholder="Enter password" type="password" />
                  <div className="w-2.5 h-full block absolute top-0 right-0 mr-5">
                    <div className="h-full flex relative flex-col justify-center items-center" data-ditto-id="style-div-25">
                      <input className="w-7.5 h-[2.6875rem] block absolute top-0 left-0 min-w-0 pt-[0.5625rem] px-[0.9375rem] overflow-clip text-background whitespace-pre text-nowrap cursor-pointer" data-ditto-id="style-button" data-component="button" type="submit" value="Submit" />
                      <div className="w-2.5 h-2.5 block inset-0" data-ditto-id="style-div-26">
                        <img className="w-full h-2.5 block max-w-full overflow-clip object-cover aspect-[auto_10/10] align-middle" data-ditto-id="style-image" data-component="image" alt="" height="10" src="/assets/cloned/svg/4bd3c1246840.svg" width="10" />
                      </div>
                    </div>
                  </div>
                </div>
              </div>
            </div>
          </form>
        </div>
      </div>
    </>
  );
}
