import "./ditto.css";
import Faq from "../components/Faq";
import Logo from "./components/logo";
import Tile from "./components/tile";
import MediaTile from "./components/media-tile";
import MediaTile2 from "./components/media-tile2";
import MediaCard from "./components/media-card";
import Logo2 from "./components/logo2";
import Logo3 from "./components/logo3";
// Generated by clone-site. Do not edit by hand.
const Logo_data = [
    { alt: "client-service-small-image", imgSrc: "/assets/cloned/images/487fa58beb46.webp" },
    { alt: "rt-recents-treatments-lower-right-small-image-wrapper-image", imgSrc: "/assets/cloned/images/f8937db43bd9.webp" },
    { alt: "client-service-small-image", imgSrc: "/assets/cloned/images/dc8027b34669.webp" }
];
const Tile_data = [
    { text: "Antiedad" },
    { text: "Masajes terapéuticos" },
    { text: "Tratamientos faciales" },
    { text: "Estética facial y corporal" }
];
const MediaTile_data = [
    { text: "Evaluación fisioterapéutica", description: "El punto de partida: valoramos tu caso y definimos el plan", alt: "Evaluación fisioterapéutica", imgSrc: "/assets/fotos/terapia-manual.webp" },
    { text: "Terapia para dolor muscular y articular", description: "Alivio del dolor y la tensión con técnicas manuales y aparatología", alt: "Terapia para dolor muscular", imgSrc: "/assets/fotos/masaje-terapeutico.webp" },
    { text: "Rehabilitación de lesiones y postoperatoria", description: "Recupera movilidad y fuerza tras una lesión o una cirugía", alt: "Rehabilitación", imgSrc: "/assets/fotos/rehabilitacion.webp" },
    { text: "Electroterapia y ultrasonido", description: "Aparatología para aliviar el dolor y acelerar la recuperación", alt: "Electroterapia", imgSrc: "/assets/fotos/electroterapia.webp" },
    { text: "Ejercicios terapéuticos", description: "Ejercicios guiados y rehabilitación funcional para recuperar fuerza y movilidad", alt: "Ejercicios terapéuticos", imgSrc: "/assets/fotos/ejercicios-terapeuticos.webp" },
    { text: "Masoterapia y masajes", description: "Masajes relajantes, deportivos y terapéuticos", alt: "Masaje relajante", imgSrc: "/assets/fotos/masaje-relajante.webp" }
];
const MediaTileCosmo_data = [
    { text: "Limpieza facial profunda", description: "Limpieza, extracción e hidratación para una piel sana y luminosa", alt: "Limpieza facial profunda", imgSrc: "/assets/fotos/tratamiento-facial.webp" },
    { text: "Tratamientos faciales", description: "Acné, deshidratación, manchas, arrugas y flacidez", alt: "Tratamiento facial para acné", imgSrc: "/assets/fotos/tratamiento-acne.webp" },
    { text: "Extracción de lunares y verrugas", description: "Procedimiento seguro, siempre con valoración previa", alt: "Extracción de lunares y verrugas", imgSrc: "/assets/cloned/images/1c90136a435f.webp" },
    { text: "Reducción de papada y ojeras", description: "Tratamientos localizados para papada y ojeras", alt: "Tratamiento para ojeras", imgSrc: "/assets/cloned/images/1ad9e0ab88ef.webp" },
    { text: "Reducción de medidas y maderoterapia", description: "Maderoterapia, tonificación (flacidez) y moldeamiento corporal", alt: "Maderoterapia", imgSrc: "/assets/cloned/images/7095b493bb44.webp" },
    { text: "Mesoterapia y alopecia", description: "Mesoterapia facial y corporal, y tratamiento para la alopecia", alt: "Mesoterapia", imgSrc: "/assets/fotos/mesoterapia-facial.webp" }
];
const MediaTile2_data = [
    { href: "/contact", imgSrc: "/assets/fotos/antiedad-antes-despues.webp", href2: "/contact", label: "Sueros y vitaminas antiedad ", href3: "/contact" },
    { href: "/contact", imgSrc: "/assets/cloned/images/2e20d9930768.webp", srcSet: "/assets/cloned/images/6c1b62d7ab78.webp 500w, /assets/cloned/images/18f4b5db04f9.webp 800w, /assets/cloned/images/02e1846354e0.webp 1080w, /assets/cloned/images/5bc3abf2829d.webp 1600w, /assets/cloned/images/fe0e8f26158d.webp 2000w, /assets/cloned/images/0a1f389ce5f5.webp 2600w, /assets/cloned/images/2707f429becd.webp 3200w, /assets/cloned/images/2e20d9930768.webp 3216w", href2: "/contact", label: "Reducción de medidas ", href3: "/contact" },
    { href: "/contact", imgSrc: "/assets/cloned/images/23fd68cba0e9.webp", srcSet: "/assets/cloned/images/78f4fefe9cb5.webp 500w, /assets/cloned/images/7fbfe5c95ebd.webp 800w, /assets/cloned/images/baa83cd82510.webp 1080w, /assets/cloned/images/45c18adf75c8.webp 1600w, /assets/cloned/images/022fdf278d6a.webp 2000w, /assets/cloned/images/9bc841dc1a54.webp 2600w, /assets/cloned/images/16793beebcd8.webp 3200w, /assets/cloned/images/23fd68cba0e9.webp 3216w", href2: "/contact", label: "Extracción de lunares y verrugas ", href3: "/contact" }
];
const MediaCard_data = [
    { imgSrc: "/assets/cloned/images/4c7b15cb7f8d.webp", srcSet: "/assets/cloned/images/ea3e7c2d23b2.webp 500w, /assets/cloned/images/4c7b15cb7f8d.webp 760w", title: "Tratamientos avanzados con excelencia clínica", description: "Tratamientos avanzados con excelencia clínica" },
    { imgSrc: "/assets/cloned/images/9aa6f611c7a6.webp", srcSet: "/assets/cloned/images/32e0acd7333b.webp 500w, /assets/cloned/images/9aa6f611c7a6.webp 760w", title: "Profesionales de confianza con resultados comprobados", description: "Experiencia y resultados comprobados" },
    { imgSrc: "/assets/cloned/images/05273eae95af.webp", srcSet: "/assets/cloned/images/56935d329a93.webp 500w, /assets/cloned/images/05273eae95af.webp 760w", title: "Atención personalizada respaldada por experiencia", description: "Soluciones personalizadas a cargo de profesionales con experiencia" }
];
const Logo2_data = [
    { imgSrc: "/assets/cloned/svg/575281ae9ada.svg" },
    { imgSrc: "/assets/cloned/svg/8f11228c9fd6.svg", kind: "image" },
    { imgSrc: "/assets/cloned/svg/1a287d2208d6.svg", kind: "image" },
    { imgSrc: "/assets/cloned/svg/ed6d2b1fc69f.svg", kind: "image" },
    { imgSrc: "/assets/cloned/svg/05ddcb1865a1.svg", kind: "image" }
];
const Logo3_data = [
    { kind: "image", imgSrc: "/assets/cloned/svg/af50b37515d8.svg" },
    { imgSrc: "/assets/cloned/svg/575281ae9ada.svg" },
    { imgSrc: "/assets/cloned/svg/8f11228c9fd6.svg" },
    { imgSrc: "/assets/cloned/svg/1a287d2208d6.svg" }
];
const Logo_meta: string[][] = [
    ["style-heading-2", "style-div-4"],
    ["style-div-34", "style-link"],
    ["style-image-3", "style-div-35"]
];
const Tile_meta: string[][] = [
    ["style-div-2", "style-div-41", "style-section"],
    ["style-div-42", "style-div-43", "n78"],
    ["n79", "style-div-6", "n81"],
    ["style-div-7", "n83", "style-div-8"]
];
const MediaTile_meta: string[][] = [
    ["style-div-54", "style-div-55", "style-div-56", "style-div-57", "style-div-58", "style-div-59"],
    ["style-div-60", "style-div-61", "n111", "n112", "n113", "n114"],
    ["n115", "n116", "n117", "n118", "n119", "style-div-21"],
    ["n121", "n122", "n123", "n124", "n125", "style-div-62"],
    ["style-div-14", "n128", "n129", "n130", "n131", "n132"],
    ["n133", "n134", "n135", "n136", "n137", "n138"]
];
const MediaTile2_meta: string[][] = [
    ["n174", "n175", "n176", "n177", "n178", "n179", "n180", "n181", "style-div-65", "n183", "n184"],
    ["n185", "n186", "n187", "n188", "n189", "n190", "n191", "n192", "style-div-66", "n194", "n195"],
    ["n196", "n197", "n198", "n199", "n200", "n201", "n202", "n203", "style-div-67", "n205", "n206"]
];
const MediaCard_meta: string[][] = [
    ["n219", "n220", "n221", "n222", "n223", "n224"],
    ["n225", "n226", "n227", "n228", "n229", "n230"],
    ["n231", "n232", "n233", "n234", "n235", "n236"]
];
const Logo2_meta: string[][] = [
    ["n243", "n244", "n245", "n246"],
    ["n247", "n248", "n249", "n250"],
    ["n251", "n252", "n253", "n254"],
    ["n255", "n256", "n257", "n258"],
    ["n259", "n260", "n261", "n262"]
];
const Logo3_meta: string[][] = [
    ["n264", "n265", "n266", "n267"],
    ["n268", "n269", "n270", "n271"],
    ["n272", "n273", "n274", "n275"],
    ["n276", "n277", "n278", "n279"]
];
const Logo_styles = [
    {  },
    { className: "-ml-[2.4375rem]" },
    { className: "-ml-[2.4375rem]" }
];
const MediaTile_styles = [
    { className: "max-md:h-[12.6875rem] md:max-lg:h-52" },
    { className: "max-md:h-[10.9375rem] md:max-lg:h-52" },
    { className: "max-md:h-[10.9375rem] md:max-lg:h-45" },
    { className: "max-md:h-38 md:max-lg:h-45" },
    { className: "max-md:h-45 md:max-lg:h-[11.4375rem]" },
    { className: "max-md:h-[10.9375rem] md:max-lg:h-[11.4375rem]" }
];
const MediaTile2_styles = [
    { className: "[filter:blur(0px)] max-lg:[filter:initial]" },
    { className: "[filter:blur(0px)] max-lg:[filter:initial]" },
    {  }
];
const MediaCard_styles = [
    { className: "relative z-1", className2: "h-58" },
    { className: "relative z-1", className2: "h-58" },
    { className2: "h-[14.5625rem]" }
];
const Logo2_styles = [
    { className: "h-[1.6875rem]" },
    { className: "h-[1.3125rem]" },
    { className: "h-5.5" },
    { className: "h-[1.1875rem]" },
    { className: "h-6.5" }
];
const Logo3_styles = [
    { className: "h-[1.4375rem]" },
    { className: "h-[1.6875rem]" },
    { className: "h-[1.3125rem]" },
    { className: "h-5.5" }
];

export default function Page() {
  return (
    <>
      <section className="block relative overflow-hidden bg-color-004 [background-size:auto,_cover,_auto] [background-position:0px_0px,_50%_50%,_50%_50%] [background-repeat:repeat,_no-repeat,_repeat] [background-clip:border-box,_border-box,_border-box] [background-origin:padding-box,_padding-box,_padding-box] [background-attachment:scroll,_scroll,_scroll] [background-blend-mode:normal,_normal,_normal] [-webkit-background-clip:border-box,_border-box,_border-box] max-md:[background-position:54%_50%] max-md:[background-size:initial] max-md:[background-repeat:initial] max-md:[background-clip:initial] max-md:[background-origin:initial] max-md:[background-attachment:initial] max-md:[background-blend-mode:initial] max-md:[-webkit-background-clip:initial] 2xl:bg-[none] 2xl:[background-size:initial] 2xl:[background-position:initial] 2xl:[background-repeat:initial] 2xl:[background-clip:initial] 2xl:[background-origin:initial] 2xl:[background-attachment:initial] 2xl:[background-blend-mode:initial] 2xl:[-webkit-background-clip:initial]" data-ditto-id="style-div-5">
        <div className="h-full block absolute top-0 inset-x-0" data-ditto-id="style-div-13">
          <img className="w-full h-[51.5625rem] block max-w-full overflow-clip object-cover aspect-[auto_1920/953] align-middle [filter:blur(5px)] max-md:h-[43.1875rem] max-lg:[filter:initial] md:max-lg:h-139 2xl:h-270 2xl:aspect-[initial]" data-component="image" alt="Imagen de servicios" height="953" src="/assets/cloned/images/fb9822b6ddb8.avif" width="1920" />
        </div>
        <div className="h-full flex absolute top-0 inset-x-0 z-1 justify-center items-center max-lg:hidden">
          <div className="w-130 h-[48.4375rem] border-2 border-solid border-border flex relative rounded-[30px] justify-center items-center overflow-hidden transform-[none] 2xl:transform-[matrix(1,0,0,1,-69.9132,-69.86)]">
            <div className="w-320 h-200 block min-w-320 max-w-500 object-cover transform-[none] 2xl:w-480 2xl:h-270 2xl:min-w-480 2xl:max-w-750 2xl:overflow-auto 2xl:transform-[matrix(1,0,0,1,69.9132,69.86)]">
              <img className="w-full h-200 block max-w-full overflow-clip object-cover align-middle 2xl:h-270" data-component="image" alt="Imagen de servicios" src="/assets/cloned/images/fb9822b6ddb8.avif" />
            </div>
          </div>
        </div>
        <div className="block max-w-407.5 px-[0.9375rem] mx-auto before:content-['_'] before:table before:w-0 before:h-0 before:text-foreground before:text-base before:leading-7 after:content-['_'] after:table after:w-0 after:h-0 after:text-foreground after:text-base after:leading-7">
          <div className="h-[51.575rem] min-h-screen flex relative z-2 pt-[15.6rem] pb-20 flex-col justify-end items-stretch gap-22.5 max-md:h-[43.2125rem] max-md:pt-[30.8rem] max-md:pb-13.5 max-md:gap-7.5 max-lg:min-h-0 md:max-lg:h-139 md:max-lg:pt-[21.3rem] md:max-lg:pb-15 md:max-lg:gap-10 2xl:h-270 2xl:pb-[6.9rem]" data-ditto-id="style-div">
            <div className="flex max-w-[25.1875rem] flex-col items-start gap-[1.6875rem] max-md:justify-between max-md:items-center max-md:text-center max-md:max-w-none">
              <h1 className="block text-background text-6xl font-semibold leading-[4rem] tracking-[-1.2px] max-md:text-[2.1875rem] max-md:leading-[2.3125rem] md:max-lg:text-[2.5rem] md:max-lg:leading-[2.625rem]" data-ditto-id="style-pass" data-component="heading">
                Nuestros servicios
              </h1>
              <div className="block relative">
                <a className="h-[2.7125rem] border border-solid border-surface-2 flex relative z-0 max-w-full pt-[0.5625rem] pb-2.5 px-5 rounded-[50px] justify-center items-center gap-2.5 overflow-hidden bg-surface-4 cursor-pointer" data-ditto-id="style-div-25" data-component="link" href="/contact">
                  <div className="h-[1.4rem] block relative z-1 overflow-hidden max-md:shrink-0" data-ditto-id="style-button">
                    <div className="block text-background leading-6 whitespace-nowrap" data-ditto-id="style-div-26">
                      Explorar
                    </div>
                    <div className="block text-background leading-6 whitespace-nowrap" data-ditto-id="style-image">
                      Explorar
                    </div>
                  </div>
                  <div className="w-[157.5px] h-[2.6375rem] flex absolute top-0 left-0 min-w-0 rounded-[50px] justify-center items-center bg-color-001 transform-[matrix(1,0,0,1,0,42.2031)] pointer-events-none" data-ditto-id="style-div-27" />
                  <div className="w-[0.5875rem] h-[0.6rem] flex relative z-1 mt-0.5 justify-center items-center max-md:shrink-0" data-ditto-id="style-div-28">
                    <img className="w-full h-2.5 block max-w-full overflow-clip object-cover aspect-[auto_9/9] align-middle" data-ditto-id="style-div-29" data-component="image" alt="flecha" height="9" src="/assets/cloned/svg/97bfaa7e2654.svg" width="9" />
                  </div>
                </a>
              </div>
            </div>
            <div className="flex justify-between items-end gap-7.5 max-lg:hidden" data-ditto-id="style-div-30">
              <div className="block max-w-[34.6875rem] flex-1 max-lg:hidden" data-ditto-id="style-image-2">
                <div className="h-[55.7px] block opacity-0 text-background text-2xl font-semibold leading-[1.75rem] tracking-[-0.48px]" data-ditto-id="style-div-31">
                  <span className="inline text-clr-31" data-ditto-id="style-div-32">
                    [ 001 ]
                  </span>
                  {" Tratamientos estéticos y fisioterapéuticos realizados por profesionales certificados."}
                </div>
              </div>
              <div className="flex relative max-w-[28.4375rem] py-10 rounded-[30px] flex-col justify-start items-start flex-1 gap-5 overflow-hidden bg-background max-md:hidden md:max-lg:opacity-0" style={{ maskImage: "url(\"/assets/cloned/svg/aa238a6d554a.svg\")" }} data-ditto-id="style-div-3">
                <div className="w-[5.6875rem] h-[2.6rem] block absolute bottom-[1.95rem] z-1 min-w-0" style={{ backgroundImage: "linear-gradient(90deg, var(--background), var(--color-012))" }} data-ditto-id="style-div-33" />
                <div className="flex pl-15 items-center gap-5" data-ditto-id="style-heading">
                  <div className="flex max-w-42.5 max-md:hidden" data-ditto-id="style-div-10">
                    {Logo_data.map((d, i) => <Logo key={i} d={d} styles={Logo_styles[i]} />)}
                  </div>
                  <div className="block" data-ditto-id="style-div-36">
                    <div className="block text-color-001 text-[2.625rem] font-semibold leading-[3rem] tracking-[-0.84px]" data-ditto-id="style-div-37">
                      300+
                    </div>
                    <div className="block whitespace-nowrap" data-ditto-id="style-div-38">
                      Pacientes satisfechas
                    </div>
                  </div>
                </div>
                <div className="flex relative gap-[0.9rem] overflow-hidden" data-ditto-id="style-div-39">
                  <div className="flex shrink-0 gap-[0.9rem] transform-[matrix(1,0,0,1,-314.26,0)] 2xl:transform-[matrix(1,0,0,1,-29.8548,0)]" data-ditto-id="style-div-40">
                    {Tile_data.map((d, i) => <Tile key={i} d={d} />)}
                  </div>
                  <div className="flex shrink-0 gap-[0.9rem] transform-[matrix(1,0,0,1,-314.26,0)] 2xl:transform-[matrix(1,0,0,1,-29.8548,0)]">
                    <div className="flex justify-center items-center grow shrink-0 gap-[0.9rem]" data-ditto-id="style-p">
                      <div className="w-[0.2rem] h-[0.2rem] block bg-color-004" data-ditto-id="style-div-24" />
                      <div className="block" data-ditto-id="style-div-11">
                        Antiedad
                      </div>
                    </div>
                  </div>
                </div>
                <div className="w-[5.6875rem] h-[2.6rem] block absolute right-0 bottom-[1.95rem] z-1 min-w-0" style={{ backgroundImage: "linear-gradient(90deg, var(--color-012), var(--background))" }} />
              </div>
            </div>
          </div>
        </div>
        <div className="h-full block absolute top-0 inset-x-0" style={{ backgroundImage: "linear-gradient(90deg, var(--clr-32), var(--clr-33) 22%, var(--clr-34) 41%, var(--clr-34) 62%, var(--clr-33) 74%, var(--clr-32))" }} />
      </section>
      <section className="block py-30 bg-surface max-lg:py-15" data-ditto-id="style-div-44">
        <div className="block max-w-407.5 px-[0.9375rem] mx-auto before:content-['_'] before:table before:w-0 before:h-0 before:text-foreground before:text-base before:leading-7 after:content-['_'] after:table after:w-0 after:h-0 after:text-foreground after:text-base after:leading-7" data-ditto-id="style-div-45">
          <div className="flex flex-col justify-start items-center" data-ditto-id="style-div-46">
            <div className="flex mb-15 flex-col justify-start items-center self-stretch text-center max-lg:mb-10" data-ditto-id="style-div-12">
              <div className="block mb-[1.5625rem] max-lg:mb-[0.9375rem]" data-ditto-id="style-div-47">
                <div className="flex justify-start items-center gap-[0.4rem]" data-ditto-id="style-div-48">
                  <div className="w-[0.3125rem] h-[0.3125rem] block bg-color-004" data-ditto-id="style-div-49" />
                  <div className="block text-color-001 text-lg leading-[1.75rem] tracking-[-0.54px] max-md:leading-[1.5625rem] max-md:[font-size:inherit] md:max-lg:text-[1.0625rem] md:max-lg:leading-[1.625rem]" data-ditto-id="style-div-50">
                    Nuestros
                  </div>
                  <div className="block text-lg leading-[1.75rem] tracking-[-0.54px] max-md:leading-[1.5625rem] max-md:[font-size:inherit] md:max-lg:text-[1.0625rem] md:max-lg:leading-[1.625rem]" data-ditto-id="style-div-51">
                    servicios
                  </div>
                </div>
              </div>
              <div className="w-full max-w-213 block" data-ditto-id="style-div-9">
                <h2 className="block text-color-001 text-[2.625rem] font-semibold leading-[3rem] tracking-[-0.84px] max-md:text-[1.5625rem] max-md:leading-[1.8125rem] md:max-lg:text-3xl md:max-lg:leading-[2.125rem]" data-ditto-id="style-div-52" data-component="heading">
                  Fisioterapia y cosmetología con soluciones profesionales
                </h2>
              </div>
            </div>
            <div className="flex self-stretch mb-7.5 flex-col items-start gap-3 text-left max-lg:mb-5">
              <div className="flex justify-start items-center gap-[0.4rem]">
                <div className="w-[0.3125rem] h-[0.3125rem] block bg-color-004" />
                <div className="block text-color-001 text-lg leading-[1.75rem] tracking-[-0.54px] max-md:leading-[1.5625rem]">
                  Fisioterapia
                </div>
              </div>
              <h3 className="block text-color-001 text-3xl font-semibold leading-9 tracking-[-0.6px] max-md:text-[1.375rem] max-md:leading-[1.625rem]">
                Para aliviar el dolor, recuperar la movilidad y mejorar la función física
              </h3>
            </div>
            <div className="grid self-stretch gap-7.5 [grid-auto-columns:1fr] grid-cols-2 max-lg:gap-5 max-md:grid-cols-1" data-ditto-id="style-div-53">
              {MediaTile_data.map((d, i) => <MediaTile key={i} d={d} styles={MediaTile_styles[i]} />)}
            </div>
            <div className="flex self-stretch mb-7.5 flex-col items-start gap-3 text-left mt-15 max-lg:mt-10 max-lg:mb-5">
              <div className="flex justify-start items-center gap-[0.4rem]">
                <div className="w-[0.3125rem] h-[0.3125rem] block bg-color-004" />
                <div className="block text-color-001 text-lg leading-[1.75rem] tracking-[-0.54px] max-md:leading-[1.5625rem]">
                  Cosmetología
                </div>
              </div>
              <h3 className="block text-color-001 text-3xl font-semibold leading-9 tracking-[-0.6px] max-md:text-[1.375rem] max-md:leading-[1.625rem]">
                Tratamientos faciales y corporales para cuidar tu piel y tu figura
              </h3>
            </div>
            <div className="grid self-stretch gap-7.5 [grid-auto-columns:1fr] grid-cols-2 max-lg:gap-5 max-md:grid-cols-1">
              {MediaTileCosmo_data.map((d, i) => <MediaTile key={i} d={d} styles={MediaTile_styles[i]} />)}
            </div>
          </div>
        </div>
      </section>
      <section className="block py-30 bg-color-003 max-lg:py-15">
        <div className="block max-w-407.5 px-[0.9375rem] mx-auto before:content-['_'] before:table before:w-0 before:h-0 before:text-foreground before:text-base before:leading-7 after:content-['_'] after:table after:w-0 after:h-0 after:text-foreground after:text-base after:leading-7">
          <div className="block max-md:flex-col">
            <div className="flex pb-12.5 justify-between items-center gap-7.5 max-lg:pb-7.5 max-md:flex-col max-md:justify-start max-md:gap-5 max-md:text-center">
              <div className="flex max-w-192.5 flex-col items-start flex-1 gap-10 max-md:gap-7 max-lg:max-w-none">
                <h2 className="block text-background text-[2.625rem] font-semibold leading-[3rem] tracking-[-0.84px] max-md:text-[1.5625rem] max-md:leading-[1.8125rem] md:max-lg:text-3xl md:max-lg:leading-[2.125rem]" data-component="heading">
                  {"Solicitud de cita "}
                  <a className="inline leading-[4.625rem] underline cursor-pointer max-md:leading-[2.75rem] md:max-lg:leading-[3.3125rem]" data-component="link" href="mailto:medicallivesthetic@gmail.com">
                    medicallivesthetic@gmail.com
                  </a>
                </h2>
              </div>
              <div className="block relative">
                <a className="h-[2.7125rem] border border-solid border-color-003 flex relative z-0 max-w-full pt-[0.5625rem] pb-2.5 px-5 rounded-[50px] justify-between items-center gap-2.5 overflow-hidden bg-background cursor-pointer" data-ditto-id="style-div-64" data-component="link" href="/contact">
                  <div className="h-[1.4rem] block relative z-1 overflow-hidden max-md:shrink-0">
                    <div className="block -mb-[0.4rem] text-color-001 leading-6 whitespace-nowrap max-lg:-mb-[0.1rem]" data-ditto-id="style-div-22">
                      Contáctanos
                    </div>
                    <div className="block text-color-001 leading-6 whitespace-nowrap">
                      Contáctanos
                    </div>
                  </div>
                  <div className="w-[150.7px] h-[2.6375rem] flex absolute top-0 left-0 min-w-0 rounded-[50px] justify-center items-center bg-color-006 transform-[matrix(1,0,0,1,0,42.2031)] pointer-events-none" />
                  <div className="w-[0.5875rem] h-[0.6rem] flex relative z-1 mt-0.5 justify-center items-center max-md:shrink-0">
                    <img className="w-full h-2.5 block max-w-full overflow-clip object-cover aspect-[auto_9/9] align-middle" data-component="image" alt="" height="9" src="/assets/cloned/svg/c81dc04c407a.svg" width="9" />
                  </div>
                </a>
              </div>
            </div>
            <div className="h-156.5 block max-md:h-57.5 max-md:aspect-[3/2] md:max-lg:h-[415.1px] md:max-lg:aspect-video" data-ditto-id="style-div-23">
              <div className="h-full block relative z-1 rounded-md overflow-hidden text-background">
                <video className="w-312.5 h-156.5 block absolute -top-156.5 -left-312.5 -z-100 my-156.5 mx-312.5 overflow-clip object-cover bg-cover [background-position:50%_50%] max-md:w-[21.5625rem] max-md:h-57.5 max-md:-top-57.5 max-md:-left-[21.5625rem] max-md:my-57.5 max-md:mx-[21.5625rem] md:max-lg:w-184.5 md:max-lg:h-[25.9375rem] md:max-lg:top-[-415.1px] md:max-lg:-left-184.5 md:max-lg:my-[415.1px] md:max-lg:mx-184.5 2xl:w-400 2xl:-left-400 2xl:mx-400" style={{ backgroundImage: "url(\"/assets/cloned/images/cfcfa0d49b34.jpg\")" }} autoPlay id="717a910b-87e7-81ba-4a54-1f370ee540d8-video" loop muted playsInline poster="/assets/cloned/images/d378237d3e3e.jpg">
                  <source className="inline text-color-004 [font-family:'Times_New_Roman'] leading-4.5" src="/assets/cloned/videos/be2b7fecbe0d.mp4" />
                  <source className="inline text-color-004 [font-family:'Times_New_Roman'] leading-4.5" src="/assets/cloned/videos/ed7ec92a7a30.webm" />
                </video>
                <div className="block" aria-live="polite">
                  <button className="w-10 h-10 block absolute top-[1.175rem] right-[37.5px] text-center cursor-pointer max-md:top-[6.9px] max-md:right-[10.3px] md:max-lg:top-[12.5px] md:max-lg:right-[22.1px] 2xl:right-12" data-component="button" aria-controls="717a910b-87e7-81ba-4a54-1f370ee540d8-video" type="button">
                    <span className="inline">
                      <img className="w-full h-10 block max-w-full overflow-clip object-cover align-middle" data-component="image" alt="Pausar video" src="/assets/cloned/svg/5eb5fbcbf2ae.svg" />
                    </span>
                  </button>
                </div>
                <div className="h-0 block absolute top-0 inset-x-0 z-1 bg-color-003" />
              </div>
            </div>
          </div>
        </div>
      </section>
      <section className="block py-30 bg-background max-lg:py-15">
        <div className="block max-w-407.5 px-[0.9375rem] mx-auto">
          <div className="flex mb-15 flex-col justify-start items-center text-center max-lg:mb-10">
            <div className="block mb-[1.5625rem] max-lg:mb-[0.9375rem]">
              <div className="flex justify-center items-center gap-[0.4rem]">
                <div className="w-[0.3125rem] h-[0.3125rem] block bg-color-004" />
                <div className="block text-color-001 text-lg leading-[1.75rem] tracking-[-0.54px] max-md:leading-[1.5625rem] max-md:[font-size:inherit]">
                  Todo lo que ofrecemos
                </div>
              </div>
            </div>
            <h2 className="block max-w-240 text-color-001 text-[2.625rem] font-semibold leading-[3rem] tracking-[-0.84px] max-md:text-[1.5625rem] max-md:leading-[1.8125rem] md:max-lg:text-3xl md:max-lg:leading-[2.125rem]">
              Nuestra lista completa de servicios
            </h2>
          </div>
          <div className="w-full grid gap-y-12.5 gap-x-12.5 grid-cols-[repeat(auto-fit,_minmax(300px,_1fr))] items-start max-md:gap-y-10">
              <div className="flex flex-col items-start gap-5 max-lg:gap-4">
                <div className="flex justify-start items-center gap-[0.4rem]">
                  <div className="w-[0.3125rem] h-[0.3125rem] block bg-color-004" />
                  <div className="block text-color-001 text-lg leading-[1.75rem] tracking-[-0.54px] max-md:leading-[1.5625rem] max-md:[font-size:inherit]">
                    Fisioterapia
                  </div>
                </div>
                <h3 className="block text-color-001 text-2xl font-semibold leading-[1.75rem] tracking-[-0.48px] max-md:text-xl max-md:leading-[1.4375rem]">
                  Tratamientos personalizados para aliviar el dolor, recuperar la movilidad y mejorar la función física.
                </h3>
                <ul className="w-full flex flex-col items-start gap-[0.6rem]">
                  <li className="w-full flex border-t border-solid border-t-border pt-[0.6rem] justify-start items-start gap-2.5">
                    <div className="w-[0.3125rem] h-[0.3125rem] block mt-[0.6rem] shrink-0 rounded-[100%] bg-color-011" />
                    <div className="block text-foreground">
                      Evaluación fisioterapéutica
                    </div>
                  </li>
                  <li className="w-full flex border-t border-solid border-t-border pt-[0.6rem] justify-start items-start gap-2.5">
                    <div className="w-[0.3125rem] h-[0.3125rem] block mt-[0.6rem] shrink-0 rounded-[100%] bg-color-011" />
                    <div className="block text-foreground">
                      Terapia para dolor muscular y articular
                    </div>
                  </li>
                  <li className="w-full flex border-t border-solid border-t-border pt-[0.6rem] justify-start items-start gap-2.5">
                    <div className="w-[0.3125rem] h-[0.3125rem] block mt-[0.6rem] shrink-0 rounded-[100%] bg-color-011" />
                    <div className="block text-foreground">
                      Rehabilitación de lesiones
                    </div>
                  </li>
                  <li className="w-full flex border-t border-solid border-t-border pt-[0.6rem] justify-start items-start gap-2.5">
                    <div className="w-[0.3125rem] h-[0.3125rem] block mt-[0.6rem] shrink-0 rounded-[100%] bg-color-011" />
                    <div className="block text-foreground">
                      Terapia postoperatoria
                    </div>
                  </li>
                  <li className="w-full flex border-t border-solid border-t-border pt-[0.6rem] justify-start items-start gap-2.5">
                    <div className="w-[0.3125rem] h-[0.3125rem] block mt-[0.6rem] shrink-0 rounded-[100%] bg-color-011" />
                    <div className="block text-foreground">
                      Masoterapia terapéutica
                    </div>
                  </li>
                  <li className="w-full flex border-t border-solid border-t-border pt-[0.6rem] justify-start items-start gap-2.5">
                    <div className="w-[0.3125rem] h-[0.3125rem] block mt-[0.6rem] shrink-0 rounded-[100%] bg-color-011" />
                    <div className="block text-foreground">
                      Electroterapia
                    </div>
                  </li>
                  <li className="w-full flex border-t border-solid border-t-border pt-[0.6rem] justify-start items-start gap-2.5">
                    <div className="w-[0.3125rem] h-[0.3125rem] block mt-[0.6rem] shrink-0 rounded-[100%] bg-color-011" />
                    <div className="block text-foreground">
                      Ultrasonido terapéutico
                    </div>
                  </li>
                  <li className="w-full flex border-t border-solid border-t-border pt-[0.6rem] justify-start items-start gap-2.5">
                    <div className="w-[0.3125rem] h-[0.3125rem] block mt-[0.6rem] shrink-0 rounded-[100%] bg-color-011" />
                    <div className="block text-foreground">
                      Ejercicios terapéuticos
                    </div>
                  </li>
                  <li className="w-full flex border-t border-solid border-t-border pt-[0.6rem] justify-start items-start gap-2.5">
                    <div className="w-[0.3125rem] h-[0.3125rem] block mt-[0.6rem] shrink-0 rounded-[100%] bg-color-011" />
                    <div className="block text-foreground">
                      Rehabilitación funcional
                    </div>
                  </li>
                </ul>
              </div>
              <div className="flex flex-col items-start gap-5 max-lg:gap-4">
                <div className="flex justify-start items-center gap-[0.4rem]">
                  <div className="w-[0.3125rem] h-[0.3125rem] block bg-color-004" />
                  <div className="block text-color-001 text-lg leading-[1.75rem] tracking-[-0.54px] max-md:leading-[1.5625rem] max-md:[font-size:inherit]">
                    Cosmetología
                  </div>
                </div>
                <h3 className="block text-color-001 text-2xl font-semibold leading-[1.75rem] tracking-[-0.48px] max-md:text-xl max-md:leading-[1.4375rem]">
                  Tratamientos que cuidan tu piel y tu figura, con protocolos definidos tras la valoración.
                </h3>
                <ul className="w-full flex flex-col items-start gap-[0.6rem]">
                  <li className="w-full flex border-t border-solid border-t-border pt-[0.6rem] justify-start items-start gap-2.5">
                    <div className="w-[0.3125rem] h-[0.3125rem] block mt-[0.6rem] shrink-0 rounded-[100%] bg-color-011" />
                    <div className="block text-foreground">
                      Limpieza facial profunda
                    </div>
                  </li>
                  <li className="w-full flex border-t border-solid border-t-border pt-[0.6rem] justify-start items-start gap-2.5">
                    <div className="w-[0.3125rem] h-[0.3125rem] block mt-[0.6rem] shrink-0 rounded-[100%] bg-color-011" />
                    <div className="block text-foreground">
                      Tratamientos faciales: acné, deshidratación, manchas, arrugas, flacidez
                    </div>
                  </li>
                  <li className="w-full flex border-t border-solid border-t-border pt-[0.6rem] justify-start items-start gap-2.5">
                    <div className="w-[0.3125rem] h-[0.3125rem] block mt-[0.6rem] shrink-0 rounded-[100%] bg-color-011" />
                    <div className="block text-foreground">
                      Extracción de lunares y verrugas
                    </div>
                  </li>
                  <li className="w-full flex border-t border-solid border-t-border pt-[0.6rem] justify-start items-start gap-2.5">
                    <div className="w-[0.3125rem] h-[0.3125rem] block mt-[0.6rem] shrink-0 rounded-[100%] bg-color-011" />
                    <div className="block text-foreground">
                      Reducción de papada
                    </div>
                  </li>
                  <li className="w-full flex border-t border-solid border-t-border pt-[0.6rem] justify-start items-start gap-2.5">
                    <div className="w-[0.3125rem] h-[0.3125rem] block mt-[0.6rem] shrink-0 rounded-[100%] bg-color-011" />
                    <div className="block text-foreground">
                      Tratamiento para ojeras
                    </div>
                  </li>
                  <li className="w-full flex border-t border-solid border-t-border pt-[0.6rem] justify-start items-start gap-2.5">
                    <div className="w-[0.3125rem] h-[0.3125rem] block mt-[0.6rem] shrink-0 rounded-[100%] bg-color-011" />
                    <div className="block text-foreground">
                      Tratamiento para alopecia
                    </div>
                  </li>
                  <li className="w-full flex border-t border-solid border-t-border pt-[0.6rem] justify-start items-start gap-2.5">
                    <div className="w-[0.3125rem] h-[0.3125rem] block mt-[0.6rem] shrink-0 rounded-[100%] bg-color-011" />
                    <div className="block text-foreground">
                      Reducción de medidas
                    </div>
                  </li>
                  <li className="w-full flex border-t border-solid border-t-border pt-[0.6rem] justify-start items-start gap-2.5">
                    <div className="w-[0.3125rem] h-[0.3125rem] block mt-[0.6rem] shrink-0 rounded-[100%] bg-color-011" />
                    <div className="block text-foreground">
                      Tonificación (flacidez)
                    </div>
                  </li>
                  <li className="w-full flex border-t border-solid border-t-border pt-[0.6rem] justify-start items-start gap-2.5">
                    <div className="w-[0.3125rem] h-[0.3125rem] block mt-[0.6rem] shrink-0 rounded-[100%] bg-color-011" />
                    <div className="block text-foreground">
                      Moldeamiento
                    </div>
                  </li>
                  <li className="w-full flex border-t border-solid border-t-border pt-[0.6rem] justify-start items-start gap-2.5">
                    <div className="w-[0.3125rem] h-[0.3125rem] block mt-[0.6rem] shrink-0 rounded-[100%] bg-color-011" />
                    <div className="block text-foreground">
                      Maderoterapia
                    </div>
                  </li>
                  <li className="w-full flex border-t border-solid border-t-border pt-[0.6rem] justify-start items-start gap-2.5">
                    <div className="w-[0.3125rem] h-[0.3125rem] block mt-[0.6rem] shrink-0 rounded-[100%] bg-color-011" />
                    <div className="block text-foreground">
                      Mesoterapia
                    </div>
                  </li>
                </ul>
              </div>
              <div className="flex flex-col items-start gap-5 max-lg:gap-4">
                <div className="flex justify-start items-center gap-[0.4rem]">
                  <div className="w-[0.3125rem] h-[0.3125rem] block bg-color-004" />
                  <div className="block text-color-001 text-lg leading-[1.75rem] tracking-[-0.54px] max-md:leading-[1.5625rem] max-md:[font-size:inherit]">
                    Otros servicios
                  </div>
                </div>
                <h3 className="block text-color-001 text-2xl font-semibold leading-[1.75rem] tracking-[-0.48px] max-md:text-xl max-md:leading-[1.4375rem]">
                  Bienestar y recuperación para acompañar cualquier tratamiento.
                </h3>
                <ul className="w-full flex flex-col items-start gap-[0.6rem]">
                  <li className="w-full flex border-t border-solid border-t-border pt-[0.6rem] justify-start items-start gap-2.5">
                    <div className="w-[0.3125rem] h-[0.3125rem] block mt-[0.6rem] shrink-0 rounded-[100%] bg-color-011" />
                    <div className="block text-foreground">
                      Administración de sueros y vitaminas: antiedad, deshidratación, vitaminas, energía
                    </div>
                  </li>
                  <li className="w-full flex border-t border-solid border-t-border pt-[0.6rem] justify-start items-start gap-2.5">
                    <div className="w-[0.3125rem] h-[0.3125rem] block mt-[0.6rem] shrink-0 rounded-[100%] bg-color-011" />
                    <div className="block text-foreground">
                      Masajes relajantes
                    </div>
                  </li>
                  <li className="w-full flex border-t border-solid border-t-border pt-[0.6rem] justify-start items-start gap-2.5">
                    <div className="w-[0.3125rem] h-[0.3125rem] block mt-[0.6rem] shrink-0 rounded-[100%] bg-color-011" />
                    <div className="block text-foreground">
                      Masajes deportivos
                    </div>
                  </li>
                  <li className="w-full flex border-t border-solid border-t-border pt-[0.6rem] justify-start items-start gap-2.5">
                    <div className="w-[0.3125rem] h-[0.3125rem] block mt-[0.6rem] shrink-0 rounded-[100%] bg-color-011" />
                    <div className="block text-foreground">
                      Masajes terapéuticos
                    </div>
                  </li>
                </ul>
              </div>
          </div>
          <div className="flex mt-15 justify-center items-center max-lg:mt-10">
            <a className="h-[2.7125rem] border border-solid border-color-003 flex relative z-0 max-w-full pt-[0.5625rem] pb-2.5 px-5 rounded-[50px] justify-center items-center gap-2.5 overflow-hidden bg-color-003 cursor-pointer" href="https://wa.me/593979898964" target="_blank" rel="noopener noreferrer">
              <div className="block text-background leading-6 whitespace-nowrap">
                Agenda tu cita por WhatsApp
              </div>
            </a>
          </div>
        </div>
      </section>
      <section className="block pt-[7.0625rem] pb-30 max-lg:pt-[3.3125rem] max-lg:pb-15">
        <div className="block max-w-407.5 px-[0.9375rem] mx-auto before:content-['_'] before:table before:w-0 before:h-0 before:text-foreground before:text-base before:leading-7 after:content-['_'] after:table after:w-0 after:h-0 after:text-foreground after:text-base after:leading-7">
          <div className="flex flex-col justify-start items-center gap-12.5 max-lg:gap-7.5">
            <div className="h-[148.7px] flex sticky top-[6.4rem] max-w-136 flex-col justify-start items-center text-center max-md:h-[6.05rem] max-lg:static max-lg:max-w-none md:max-lg:h-[75.5px]">
              <div className="block mb-[1.5625rem] max-lg:mb-[0.9375rem]">
                <div className="flex justify-start items-center gap-[0.4rem]">
                  <div className="w-[0.3125rem] h-[0.3125rem] block bg-color-004" />
                  <div className="block text-color-001 text-lg leading-[1.75rem] tracking-[-0.54px] max-md:leading-[1.5625rem] max-md:[font-size:inherit] md:max-lg:text-[1.0625rem] md:max-lg:leading-[1.625rem]">
                    Nuestros resultados
                  </div>
                </div>
              </div>
              <h2 className="block text-color-001 text-[2.625rem] font-semibold leading-[3rem] tracking-[-0.84px] max-md:text-[1.5625rem] max-md:leading-[1.8125rem] md:max-lg:text-3xl md:max-lg:leading-[2.125rem]" data-component="heading">
                Casos y resultados de tratamiento
              </h2>
            </div>
            <div className="flex flex-col items-stretch self-stretch gap-10">
              {MediaTile2_data.map((d, i) => <MediaTile2 key={i} d={d} styles={MediaTile2_styles[i]} />)}
            </div>
          </div>
        </div>
      </section>
      <section className="block pt-[7.0625rem] pb-30 overflow-hidden bg-surface max-lg:pt-[3.3125rem] max-lg:pb-15">
        <div className="block max-w-407.5 px-[0.9375rem] mx-auto before:content-['_'] before:table before:w-0 before:h-0 before:text-foreground before:text-base before:leading-7 after:content-['_'] after:table after:w-0 after:h-0 after:text-foreground after:text-base after:leading-7">
          <div className="flex pb-12.5 flex-col justify-start items-center text-center max-lg:pb-7.5">
            <div className="block mb-[1.5625rem] max-lg:mb-[0.9375rem]">
              <div className="flex justify-start items-center gap-[0.4rem]">
                <div className="w-[0.3125rem] h-[0.3125rem] block bg-color-004" />
                <div className="block text-color-001 text-lg leading-[1.75rem] tracking-[-0.54px] max-md:leading-[1.5625rem] max-md:[font-size:inherit] md:max-lg:text-[1.0625rem] md:max-lg:leading-[1.625rem]">
                  Atención comprobada
                </div>
                <div className="block text-lg leading-[1.75rem] tracking-[-0.54px] max-md:leading-[1.5625rem] max-md:[font-size:inherit] md:max-lg:text-[1.0625rem] md:max-lg:leading-[1.625rem]">
                  excelencia
                </div>
              </div>
            </div>
            <div className="w-full max-w-[32.1875rem] block justify-center items-center">
              <h2 className="block mb-[1.5625rem] text-color-001 text-[2.625rem] font-semibold leading-[3rem] tracking-[-0.84px] max-lg:mb-[0.9375rem] max-md:text-[1.5625rem] max-md:leading-[1.8125rem] md:max-lg:text-3xl md:max-lg:leading-[2.125rem]" data-component="heading">
                Por qué confiar en nuestro centro
              </h2>
            </div>
            <p className="block">
              Atención personalizada respaldada por experiencia
            </p>
          </div>
          <div className="grid items-start gap-12.5 [grid-auto-columns:1fr] justify-items-stretch grid-cols-3 max-lg:gap-7.5 max-md:grid-cols-1">
            {MediaCard_data.map((d, i) => <MediaCard key={i} d={d} styles={MediaCard_styles[i]} />)}
          </div>
        </div>
      </section>
      <section className="block pb-30 bg-surface max-lg:pb-15">
        <div className="block max-w-407.5 px-[0.9375rem] mx-auto before:content-['_'] before:table before:w-0 before:h-0 before:text-foreground before:text-base before:leading-7 after:content-['_'] after:table after:w-0 after:h-0 after:text-foreground after:text-base after:leading-7">
          <div className="block relative py-px overflow-hidden">
            <div className="w-16 h-[9.2625rem] block absolute -top-[1.0625rem] -left-[1.5625rem] z-1 max-lg:hidden 2xl:-left-8" style={{ backgroundImage: "linear-gradient(270deg, var(--clr-14), var(--surface) 60%, var(--surface) 69%, var(--surface))" }} />
            <div className="flex items-start overflow-hidden">
              <div className="flex items-start shrink-0 transform-[matrix(1,0,0,1,-205.57,0)] max-md:transform-[matrix(1,0,0,1,-162.85,0)] md:max-lg:transform-[matrix(1,0,0,1,-145.5,0)] 2xl:transform-[matrix(1,0,0,1,-520.62,0)]" data-ditto-id="style-div-68">
                {Logo2_data.map((d, i) => <Logo2 key={i} d={d} styles={Logo2_styles[i]} />)}
              </div>
              <div className="flex items-start shrink-0 transform-[matrix(1,0,0,1,-472.574,0)] max-md:transform-[matrix(1,0,0,1,-429.849,0)] md:max-lg:transform-[matrix(1,0,0,1,-412.499,0)] 2xl:transform-[matrix(1,0,0,1,-787.623,0)]" data-ditto-id="style-div-69">
                {Logo3_data.map((d, i) => <Logo3 key={i} d={d} styles={Logo3_styles[i]} />)}
              </div>
            </div>
            <div className="w-16 h-[9.2625rem] block absolute -top-[1.0625rem] -right-[1.5625rem] max-lg:hidden 2xl:-right-8" data-ditto-id="style-div-63" />
          </div>
        </div>
      </section>
      <section className="block pb-30 overflow-hidden bg-surface max-lg:pb-15">
        <div className="block max-w-407.5 px-[0.9375rem] mx-auto before:content-['_'] before:table before:w-0 before:h-0 before:text-foreground before:text-base before:leading-7 after:content-['_'] after:table after:w-0 after:h-0 after:text-foreground after:text-base after:leading-7" data-ditto-id="interaction-div">
          <div className="flex items-start">
            <div className="flex justify-start items-center gap-[0.4rem]">
              <div className="w-[0.3125rem] h-[0.3125rem] block bg-color-004" data-ditto-id="interaction-div-2" />
              <div className="block text-color-001 text-lg leading-[1.75rem] tracking-[-0.54px] max-md:leading-[1.5625rem] max-md:[font-size:inherit] md:max-lg:text-[1.0625rem] md:max-lg:leading-[1.625rem]">
                Lo que dicen
              </div>
              <div className="block text-lg leading-[1.75rem] tracking-[-0.54px] max-md:leading-[1.5625rem] max-md:[font-size:inherit] md:max-lg:text-[1.0625rem] md:max-lg:leading-[1.625rem]">
                nuestras pacientes
              </div>
            </div>
          </div>
          <div className="block pt-12.5 max-lg:pt-8">
            <div className="h-[34.4375rem] block relative clear-both text-center max-md:h-[868.1px] max-lg:flex max-lg:flex-col md:max-lg:h-[27.525rem]" aria-label="carrusel" role="region">
              <div className="w-full max-w-267.5 h-full block relative z-1 whitespace-nowrap text-nowrap" data-ditto-id="interaction-w-slider-mask-0" id="w-slider-mask-0">
                <div className="w-full inline-block relative mr-12.5 align-top text-left whitespace-normal" aria-label="1 de 6" role="group">
                  <div className="flex justify-between items-center gap-12.5 max-md:grid max-lg:items-stretch max-lg:gap-7.5 max-md:grid-cols-[345px] max-md:[grid-auto-columns:1fr]">
                    <div className="block max-w-102.5 rounded-[5px] flex-1 overflow-hidden max-md:self-stretch max-md:max-w-none" data-ditto-id="interaction-div-3">
                      <img className="w-full h-[34.4375rem] block max-w-full overflow-clip object-cover aspect-[auto_410/551] align-middle max-md:h-116 md:max-lg:h-110" data-component="image" alt="Paciente" height="551" sizes="(max-width: 479px) 100vw, 410px" src="/assets/cloned/images/90e528970344.webp" srcSet="/assets/cloned/images/b6e4b25036a7.webp 500w, /assets/cloned/images/6e996eb39a39.webp 800w, /assets/cloned/images/90e528970344.webp 820w" width="410" />
                    </div>
                    <div className="flex relative max-w-157.5 py-20 px-[3.5625rem] rounded-[5px] flex-col justify-center items-start self-stretch flex-1 bg-background max-lg:pt-10 max-lg:pb-8.5 max-md:px-5 md:max-lg:px-7.5">
                      <div className="w-[2.8125rem] block mb-13.5 max-lg:mb-6.5">
                        <img className="w-full h-9.5 block max-w-full overflow-clip object-cover aspect-[auto_45/38] align-middle" data-component="image" alt="" height="38" src="/assets/cloned/svg/9bef580093cb.svg" width="45" />
                      </div>
                      <div className="block mb-[2.9375rem] max-lg:mb-[1.1875rem]" data-ditto-id="interaction-div-4">
                        <h3 className="block text-color-001 text-3xl font-semibold leading-9 tracking-[-0.6px] max-md:text-[1.375rem] max-md:leading-[1.625rem] md:max-lg:text-[1.625rem] md:max-lg:leading-[1.9375rem]" data-component="heading">
                          «Noté un cambio real en mi piel después del plan personalizado. La atención fue excelente de principio a fin.»
                        </h3>
                      </div>
                      <div className="flex flex-col items-start gap-[1.1875rem] max-md:gap-y-2.5 max-md:gap-x-4 md:max-lg:gap-4">
                        <div className="block text-color-001 text-lg font-medium leading-6 tracking-[-0.36px] whitespace-nowrap max-lg:text-[1.0625rem] max-lg:leading-[1.4375rem]" data-ditto-id="interaction-div-5">
                          Sofía M.
                        </div>
                        <div className="block -mb-[0.4rem] text-color-001 max-lg:-mb-[0.1rem]">
                          Parque Valladolid
                        </div>
                      </div>
                    </div>
                  </div>
                </div>
                <div className="w-full inline-block relative mr-12.5 align-top text-left whitespace-normal" aria-hidden="true" aria-label="2 de 6" role="group">
                  <div className="flex justify-between items-center gap-12.5 max-md:grid max-lg:items-stretch max-lg:gap-7.5 max-md:grid-cols-[345px] max-md:[grid-auto-columns:1fr]" aria-hidden="true">
                    <div className="block max-w-102.5 rounded-[5px] flex-1 overflow-hidden max-md:self-stretch max-md:max-w-none" aria-hidden="true">
                      <img className="w-full h-[34.4375rem] block max-w-full overflow-clip object-cover aspect-[auto_410/551] align-middle max-md:h-116 md:max-lg:h-110" data-component="image" alt="Paciente" aria-hidden="true" height="551" src="/assets/cloned/images/1d00a024552e.avif" width="410" />
                    </div>
                    <div className="flex relative max-w-157.5 py-20 px-[3.5625rem] rounded-[5px] flex-col justify-center items-start self-stretch flex-1 bg-background max-lg:pt-10 max-lg:pb-8.5 max-md:px-5 md:max-lg:px-7.5" aria-hidden="true">
                      <div className="w-[2.8125rem] block mb-13.5 max-lg:mb-6.5" aria-hidden="true">
                        <img className="w-full h-9.5 block max-w-full overflow-clip object-cover aspect-[auto_45/38] align-middle" alt="" aria-hidden="true" height="38" src="/assets/cloned/svg/9bef580093cb.svg" width="45" />
                      </div>
                      <div className="block mb-[2.9375rem] max-lg:mb-[1.1875rem]" aria-hidden="true">
                        <h3 className="block text-color-001 text-3xl font-semibold leading-9 tracking-[-0.6px] max-md:text-[1.375rem] max-md:leading-[1.625rem] md:max-lg:text-[1.625rem] md:max-lg:leading-[1.9375rem]" aria-hidden="true">
                          «Llegué con dolor lumbar de años. El plan que me armaron fue preciso y efectivo: hoy me muevo sin molestias.»
                        </h3>
                      </div>
                      <div className="flex flex-col items-start gap-[1.1875rem] max-md:gap-y-2.5 max-md:gap-x-4 md:max-lg:gap-4" aria-hidden="true">
                        <div className="block text-color-001 text-lg font-medium leading-6 tracking-[-0.36px] whitespace-nowrap max-lg:text-[1.0625rem] max-lg:leading-[1.4375rem]" aria-hidden="true">
                          Luis C.
                        </div>
                        <div className="block -mb-[0.4rem] text-color-001 max-lg:-mb-[0.1rem]" aria-hidden="true">
                          Cuenca
                        </div>
                      </div>
                    </div>
                  </div>
                </div>
                <div className="w-px h-px block absolute -m-px overflow-hidden" aria-atomic="true" aria-live="off" />
              </div>
              <div className="w-10 h-10 block absolute -top-15 right-0 z-4 justify-center items-center overflow-hidden text-background text-[2.5rem] bg-color-003 cursor-pointer max-lg:min-w-0" data-component="button" aria-controls="w-slider-mask-0" aria-label="siguiente" role="button">
                <div className="w-10 h-full flex absolute top-0 left-0 p-[0.9rem] justify-center items-center">
                  <div className="w-2 h-full flex absolute top-0 right-3.5 z-1 min-w-0 max-w-2 flex-col justify-center items-center [filter:invert(0)]">
                    <div className="block">
                      <img className="w-full h-3.5 block max-w-full overflow-clip object-cover align-middle" data-component="image" alt="" src="/assets/cloned/svg/3e8b2fde4e1b.svg" />
                    </div>
                  </div>
                </div>
              </div>
            </div>
          </div>
        </div>
      </section>
      <section className="block py-30 max-lg:pt-[3.3125rem] max-lg:pb-15">
        <div className="block max-w-407.5 px-[0.9375rem] mx-auto before:content-['_'] before:table before:w-0 before:h-0 before:text-foreground before:text-base before:leading-7 after:content-['_'] after:table after:w-0 after:h-0 after:text-foreground after:text-base after:leading-7">
          <div className="block">
            <div className="flex justify-between items-start gap-7.5 max-md:flex-col max-md:items-stretch max-md:grid-cols-[1fr_1fr] max-md:grid-rows-[auto] max-md:[grid-auto-columns:1fr]">
              <div className="block relative max-w-[45.5625rem] flex-1">
                <div className="block mb-[1.5625rem] max-lg:mb-[0.9375rem]">
                  <div className="flex justify-start items-center gap-[0.4rem]">
                    <div className="w-[0.3125rem] h-[0.3125rem] block bg-color-004" data-ditto-id="style-div-15" />
                    <div className="block text-color-001 text-lg leading-[1.75rem] tracking-[-0.54px] max-md:leading-[1.5625rem] max-md:[font-size:inherit] md:max-lg:text-[1.0625rem] md:max-lg:leading-[1.625rem]">
                      Guía rápida
                    </div>
                  </div>
                </div>
                <div className="block rounded-[5px] overflow-hidden">
                  <img className="w-full h-119 block max-w-full overflow-clip object-cover aspect-[auto_729/569] align-middle max-md:h-[16.8125rem] md:max-lg:h-69 2xl:h-[35.5625rem]" data-component="image" alt="imagen de preguntas frecuentes" height="569" sizes="(max-width: 767px) 100vw, (max-width: 991px) 728px, 729px" src="/assets/cloned/images/7c24cf11d3cf.webp" srcSet="/assets/cloned/images/cdbb14f09b2b.webp 500w, /assets/cloned/images/96ff31f7b95a.webp 800w, /assets/cloned/images/6ab2f7ccc69b.webp 1080w, /assets/cloned/images/7c24cf11d3cf.webp 1458w" width="729" />
                </div>
              </div>
              <div className="flex max-w-[45.4375rem] flex-col items-start flex-1 gap-12.5 max-md:gap-5 max-md:max-w-none md:max-lg:gap-7.5">
                <h2 className="block text-color-001 text-[2.625rem] font-semibold leading-[3rem] tracking-[-0.84px] max-md:text-[1.5625rem] max-md:leading-[1.8125rem] md:max-lg:text-3xl md:max-lg:leading-[2.125rem]" data-component="heading">
                  Preguntas frecuentes
                </h2>
                <Faq />
              </div>
            </div>
          </div>
        </div>
      </section>
    </>
  );
}
