import "./ditto.css";
import Tile from "./components/tile";
import MediaTile from "./components/media-tile";
// Generated by clone-site. Do not edit by hand.
const Tile_data = [
    { value: "", text: "Custom consultation type" },
    { value: "General skin consultation", text: "General skin consultation" },
    { value: "Hair & scalp consultation", text: "Hair & scalp consultation" },
    { value: "Cosmetic / aesthetic consultation", text: "Cosmetic / aesthetic consultation" }
];
const Tile_data2 = [
    { value: "", text: "Choose time" },
    { value: "Morning (9:00 AM – 12:00 PM)", text: "Morning (9:00 AM – 12:00 PM)" },
    { value: "Afternoon (12:00 PM – 4:00 PM)", text: "Afternoon (12:00 PM – 4:00 PM)" },
    { value: "Evening (4:00 PM – 8:00 PM)", text: "Evening (4:00 PM – 8:00 PM)" }
];
const MediaTile_data = [
    { ariacontrols: "w-dropdown-list-3", id: "w-dropdown-toggle-3", text: "What skin and hair conditions do you treat?" },
    { ariacontrols: "w-dropdown-list-4", id: "w-dropdown-toggle-4", text: "Are treatments safe and dermatologist-approved?" },
    { ariacontrols: "w-dropdown-list-5", id: "w-dropdown-toggle-5", text: "How many sessions are required to see results?" },
    { ariacontrols: "w-dropdown-list-6", id: "w-dropdown-toggle-6", text: "Do you offer personalized treatment plans?" }
];
const Tile_meta: string[][] = [
    ["n89"],
    ["n90"],
    ["style-div-44"],
    ["style-div-45"]
];
const Tile_meta2: string[][] = [
    ["style-div-47"],
    ["style-div-48"],
    ["style-div-49"],
    ["style-div-50"]
];
const MediaTile_meta: string[][] = [
    ["n156", "n157", "n158", "n159", "n160"],
    ["n161", "n162", "n163", "n164", "n165"],
    ["n166", "n167", "n168", "n169", "n170"],
    ["n171", "n172", "n173", "n174", "n175"]
];
const MediaTile_styles = [
    { className: "max-md:h-1.5" },
    { className: "max-md:h-[0.3125rem] md:max-lg:h-1.5" },
    { className: "max-lg:h-1.5" },
    { className: "max-md:h-1.5" }
];

export default function Page() {
  return (
    <>
      <section className="block pt-100 pb-18 bg-color-004 [background-size:auto,_cover] [background-position:0px_0px,_50%_50%] [background-repeat:repeat,_no-repeat] [background-clip:border-box,_border-box] [background-origin:padding-box,_padding-box] [background-attachment:scroll,_scroll] [background-blend-mode:normal,_normal] [-webkit-background-clip:border-box,_border-box] max-md:pt-32.5 max-md:bg-clr-28 max-md:bg-[none] max-md:[background-size:initial] max-md:[background-position:initial] max-md:[background-repeat:initial] max-md:[background-clip:initial] max-md:[background-origin:initial] max-md:[background-attachment:initial] max-md:[background-blend-mode:initial] max-md:[-webkit-background-clip:initial] md:max-lg:pt-[15.2rem]" data-ditto-id="style-div-5">
        <div className="block max-w-407.5 px-[0.9375rem] mx-auto before:content-['_'] before:table before:w-0 before:h-0 before:text-foreground before:text-base before:leading-7 after:content-['_'] after:table after:w-0 after:h-0 after:text-foreground after:text-base after:leading-7" data-ditto-id="style-div-13">
          <div className="flex relative flex-col items-start gap-52.5 grid-cols-[1fr_1fr] grid-rows-[auto] [grid-auto-columns:1fr] justify-items-stretch max-md:justify-start max-md:items-center max-md:gap-[0.9375rem] max-md:text-center md:max-lg:gap-25 2xl:grid-cols-[66.4%_1fr]">
            <div className="flex max-w-[42.1875rem] flex-col items-start max-lg:max-w-[34.7rem] max-md:justify-start max-md:items-center">
              <div className="block mb-[1.5625rem] max-lg:mb-[0.9375rem]">
                <div className="flex justify-start items-center gap-[0.4rem]">
                  <div className="w-[0.3125rem] h-[0.3125rem] block bg-background" />
                  <div className="block text-background text-lg leading-[1.75rem] tracking-[-0.54px] max-md:leading-[1.5625rem] max-md:[font-size:inherit] md:max-lg:text-[1.0625rem] md:max-lg:leading-[1.625rem]">
                    Contact us
                  </div>
                </div>
              </div>
              <h1 className="block text-background text-6xl font-semibold leading-[4rem] tracking-[-1.2px] max-md:text-[2.1875rem] max-md:leading-[2.3125rem] md:max-lg:text-[2.5rem] md:max-lg:leading-[2.625rem]" data-ditto-id="style-div" data-component="heading">
                Consult dermatology experts for treatment
              </h1>
            </div>
            <div className="w-full max-w-157.5 block self-end max-md:self-center">
              <p className="block text-background" data-ditto-id="style-pass">
                Speak with experienced dermatologists to receive trusted advice, safe procedures, personalized treatments, and comprehensive care for achieving long-term healthy skin results.
              </p>
            </div>
          </div>
        </div>
      </section>
      <section className="block pt-30 pb-96 bg-surface max-lg:pt-15 max-lg:pb-81">
        <div className="block max-w-407.5 px-[0.9375rem] mx-auto before:content-['_'] before:table before:w-0 before:h-0 before:text-foreground before:text-base before:leading-7 after:content-['_'] after:table after:w-0 after:h-0 after:text-foreground after:text-base after:leading-7" data-ditto-id="style-div-25">
          <div className="block" data-ditto-id="style-button">
            <div className="flex justify-between items-center gap-7.5 max-md:flex-wrap max-md:grid-cols-[repeat(auto-fit,_minmax(260px,_1fr))] max-md:grid-rows-[auto] max-lg:[grid-auto-columns:1fr] md:max-lg:grid-cols-[1fr_1fr] md:max-lg:grid-rows-[auto_auto]" data-ditto-id="style-div-26">
              <div className="flex max-w-[45.4375rem] flex-col items-start self-stretch flex-1 gap-15 max-md:justify-start max-md:gap-5 max-md:max-w-none md:max-lg:gap-10" data-ditto-id="style-image">
                <div className="block" data-ditto-id="style-div-27">
                  <div className="block rounded-md overflow-hidden" data-ditto-id="style-div-28">
                    <img className="w-full h-77.5 block max-w-full overflow-clip object-cover aspect-[auto_727/369] align-middle max-md:h-[10.9375rem] md:max-lg:h-45 2xl:h-[23.0625rem]" data-ditto-id="style-div-29" data-component="image" alt="contact form image" height="369" sizes="(max-width: 767px) 100vw, 727px" src="/assets/cloned/images/201b694ca32f.avif" srcSet="/assets/cloned/images/81c8c71f49f9.avif 500w, /assets/cloned/images/b9dbda8c1af8.avif 800w, /assets/cloned/images/201b694ca32f.avif 1454w" width="727" />
                  </div>
                </div>
                <div className="block self-stretch" data-ditto-id="style-div-30">
                  <div className="flex mb-[1.5625rem] flex-col items-stretch gap-6.5 max-md:gap-4" data-ditto-id="style-image-2">
                    <div className="h-px block bg-border" data-ditto-id="style-div-31" />
                    <div className="flex justify-start items-center gap-[1.5625rem] max-md:gap-4" data-ditto-id="style-div-32">
                      <div className="w-[1.6875rem] block max-md:w-[1.3rem]" data-ditto-id="style-div-3">
                        <img className="w-full h-[1.6875rem] block max-w-full overflow-clip object-cover aspect-[auto_27/27] align-middle max-md:h-[1.3125rem]" data-ditto-id="style-div-33" data-component="image" alt="" height="27" src="/assets/cloned/svg/89f1eb405e53.svg" width="27" />
                      </div>
                      <div className="block text-color-001 text-xl font-medium leading-6.5 tracking-[-0.4px] max-lg:text-lg max-lg:leading-[1.4375rem]" data-ditto-id="style-heading">
                        {"Call us: "}
                        <a className="inline leading-[2.1875rem] cursor-pointer max-lg:leading-[2rem]" data-ditto-id="style-div-10" data-component="link" href="tel:8881234567">
                          (888)1234-567
                        </a>
                      </div>
                    </div>
                    <div className="h-px block bg-border" data-ditto-id="style-heading-2" />
                    <div className="flex justify-start items-center gap-[1.5625rem] max-md:gap-4" data-ditto-id="style-div-4">
                      <div className="w-[1.6875rem] block max-md:w-[1.3rem]" data-ditto-id="style-div-34">
                        <img className="w-full h-5.5 block max-w-full overflow-clip object-cover aspect-[auto_27/27] align-middle max-md:h-[1.0625rem]" data-ditto-id="style-link" data-component="image" alt="" height="27" src="/assets/cloned/svg/d1d6db3aab0b.svg" width="27" />
                      </div>
                      <div className="block text-color-001 text-xl font-medium leading-6.5 tracking-[-0.4px] max-lg:text-lg max-lg:leading-[1.4375rem]" data-ditto-id="style-image-3">
                        {"Email us: "}
                        <a className="inline text-foreground leading-[2.1875rem] cursor-pointer max-lg:leading-[2rem]" data-ditto-id="style-div-35" data-component="link" href="mailto:info@example.com">
                          info@example.com
                        </a>
                      </div>
                    </div>
                    <div className="h-px block bg-border" data-ditto-id="style-div-36" />
                  </div>
                  <div className="w-full max-w-120.5 block" data-ditto-id="style-div-37">
                    <div className="block" data-ditto-id="style-div-38">
                      <span className="inline -mb-[0.4rem] text-color-001 max-lg:-mb-[0.1rem]" data-ditto-id="style-div-39">
                        Ready to start your journey
                      </span>
                      {" toward healthier, glowing skin with our expert care?"}
                    </div>
                  </div>
                </div>
              </div>
              <div className="block max-w-[45.5625rem] flex-1 max-md:max-w-none" data-ditto-id="style-div-40">
                <div className="flex max-w-[33.0625rem] mb-9 flex-col items-start gap-[1.5625rem] max-lg:mb-4 max-lg:gap-[0.9375rem] max-md:max-w-none" data-ditto-id="style-div-2">
                  <h2 className="block text-color-001 text-[2.625rem] font-semibold leading-[3rem] tracking-[-0.84px] max-md:text-[1.5625rem] max-md:leading-[1.8125rem] md:max-lg:text-3xl md:max-lg:leading-[2.125rem]" data-ditto-id="style-div-41" data-component="heading">
                    Request expert dermatology advice now
                  </h2>
                  <div className="block" data-ditto-id="style-section">
                    Specialist advice for better skin.
                  </div>
                </div>
                <div className="block" data-ditto-id="style-div-42">
                  <form className="block flex-col gap-[37.5px] grid-cols-[1fr_1fr] grid-rows-[auto_auto] [grid-auto-columns:1fr] overflow-hidden max-md:gap-y-5 max-md:gap-x-[34.3px] md:max-lg:gap-5 md:max-lg:grid-cols-[repeat(auto-fit,_minmax(240px,_1fr))]" data-ditto-id="style-div-43" aria-label="Contact Form One" id="wf-form-Contact-Form-One" name="wf-form-Contact-Form-One">
                    <div className="grid mb-6.5 gap-y-5 gap-x-7.5 [grid-auto-columns:1fr] grid-cols-2 grid-rows-3 max-md:mb-4 max-md:gap-2.5 max-md:grid-cols-1 max-md:grid-rows-6">
                      <div className="block">
                        <input className="w-full h-12.5 border-b border-solid border-b-border block py-2 pr-3 overflow-clip align-middle text-color-001 text-sm leading-5 cursor-text" data-ditto-id="style-div-6" data-component="input" id="Contact-first-name" name="Contact-first-name" placeholder="First name" type="text" />
                      </div>
                      <div className="block">
                        <input className="w-full h-12.5 border-b border-solid border-b-border block py-2 pr-3 overflow-clip align-middle text-color-001 text-sm leading-5 cursor-text" data-ditto-id="style-div-7" data-component="input" id="Contact-last-name" name="Contact-last-name" placeholder="Last name" type="text" />
                      </div>
                      <div className="block">
                        <input className="w-full h-12.5 border-b border-solid border-b-border block py-2 pr-3 overflow-clip align-middle text-color-001 text-sm leading-5 cursor-text" data-ditto-id="style-div-8" data-component="input" id="Contact-phone" name="Contact-phone" placeholder="Phone" type="tel" />
                      </div>
                      <div className="block">
                        <input className="w-full h-12.5 border-b border-solid border-b-border block py-2 pr-3 overflow-clip align-middle text-color-001 text-sm leading-5 cursor-text" data-ditto-id="style-p" data-component="input" id="Contact-email" name="Contact-email" placeholder="Email" type="email" />
                      </div>
                      <div className="block" data-ditto-id="style-div-24">
                        <select className="w-full h-12.5 border-b border-solid border-b-border block py-2 pr-3 items-center align-middle text-color-001 leading-[1.4375rem] whitespace-pre text-nowrap bg-surface cursor-default" data-ditto-id="style-div-11" data-component="select" id="Custom-consultation-type" name="Custom-consultation-type">
                          {Tile_data.map((d, i) => <Tile key={i} d={d} />)}
                        </select>
                      </div>
                      <div className="block" data-ditto-id="style-div-46">
                        <select className="w-full h-12.5 border-b border-solid border-b-border block py-2 pr-3 items-center align-middle text-color-001 leading-[1.4375rem] whitespace-pre text-nowrap bg-surface cursor-default" data-ditto-id="style-div-12" data-component="select" id="Choose-time-v2" name="Choose-time">
                          {Tile_data2.map((d, i) => <Tile key={i} d={d} />)}
                        </select>
                      </div>
                    </div>
                    <div className="block mb-7.5 max-md:gap-4 max-md:grid-cols-[1fr] max-md:grid-rows-[auto] max-md:[grid-auto-columns:1fr]" data-ditto-id="style-div-51">
                      <textarea className="w-full h-40 min-h-40 border-b border-solid border-b-border block min-w-full max-w-full py-2 pr-3 overflow-auto align-middle text-color-001 text-sm leading-5 whitespace-pre-wrap [overflow-wrap:break-word] bg-clr-27 cursor-text" data-ditto-id="style-div-9" data-component="textarea" id="field" name="field" placeholder="Type message" />
                    </div>
                    <div className="flex relative items-start" data-ditto-id="style-div-52">
                      <div className="block relative" data-ditto-id="style-div-53">
                        <a className="h-[2.7125rem] border border-solid border-color-003 flex relative z-0 max-w-full pt-[0.5625rem] pb-2.5 px-5 rounded-[50px] justify-center items-center gap-2.5 overflow-hidden bg-color-003 cursor-pointer" data-ditto-id="style-div-54" data-component="link" aria-current="page" href="/contact">
                          <div className="h-[1.4rem] block relative z-1 overflow-hidden max-md:shrink-0" data-ditto-id="style-div-55">
                            <div className="block text-background leading-6 whitespace-nowrap" data-ditto-id="style-div-56">
                              Inquire now
                            </div>
                            <div className="block text-background leading-6 whitespace-nowrap" data-ditto-id="style-div-57">
                              Inquire now
                            </div>
                          </div>
                          <div className="w-[157.5px] h-[2.6375rem] flex absolute top-0 left-0 min-w-0 rounded-[50px] justify-center items-center bg-color-006 transform-[matrix(1,0,0,1,0,42.2031)] pointer-events-none" data-ditto-id="style-div-58" />
                          <div className="w-[0.5875rem] h-[0.6rem] flex relative z-1 mt-0.5 justify-center items-center max-md:shrink-0" data-ditto-id="style-div-59">
                            <img className="w-full h-2.5 block max-w-full overflow-clip object-cover aspect-[auto_9/9] align-middle" data-ditto-id="style-div-60" data-component="image" alt="button white arrow" height="9" src="/assets/cloned/svg/97bfaa7e2654.svg" width="9" />
                          </div>
                        </a>
                        <input className="w-full h-[2.6875rem] block absolute top-0 left-0 z-2 py-[0.5625rem] px-[0.9375rem] overflow-clip text-clr-8 text-center whitespace-pre text-nowrap cursor-pointer" data-ditto-id="style-div-61" data-component="button" type="submit" value="Submit" />
                      </div>
                    </div>
                  </form>
                </div>
              </div>
            </div>
          </div>
        </div>
      </section>
      <section className="block -mt-[16.6875rem]">
        <div className="block max-w-407.5 px-[0.9375rem] mx-auto before:content-['_'] before:table before:w-0 before:h-0 before:text-foreground before:text-base before:leading-7 after:content-['_'] after:table after:w-0 after:h-0 after:text-foreground after:text-base after:leading-7">
          <div className="block relative overflow-hidden max-md:flex-col max-md:[overflow-x:initial] max-md:[overflow-y:initial]">
            <div className="block rounded-md overflow-hidden max-md:aspect-[2/3]">
              <img className="w-full h-[32.6875rem] block max-w-full overflow-clip object-cover aspect-[auto_1290/540] align-middle max-md:h-129.5 md:max-lg:h-[19.3125rem] 2xl:h-167.5" data-component="image" alt="Contact middle section bg image" height="540" sizes="(max-width: 767px) 100vw, (max-width: 991px) 728px, 940px" src="/assets/cloned/images/322c78517d65.webp" srcSet="/assets/cloned/images/c5a4b2c7b3af.webp 500w, /assets/cloned/images/1b05a70b74b5.webp 800w, /assets/cloned/images/26b8f5243dc4.webp 1080w, /assets/cloned/images/aad5fe811000.webp 1600w, /assets/cloned/images/82b8e45732cc.webp 2000w, /assets/cloned/images/322c78517d65.webp 2580w" width="1290" />
            </div>
            <div className="h-79 flex absolute right-7.5 bottom-7.5 left-237.5 z-2 p-10 rounded-md flex-col gap-6 max-lg:h-[16.5875rem] max-lg:right-4 max-lg:bottom-8 max-md:left-[6.5625rem] max-lg:p-4 md:max-lg:left-124.5 2xl:left-325" style={{ backgroundImage: "linear-gradient(var(--clr-29), var(--clr-29))" }}>
              <div className="block max-w-47.5 max-md:max-w-none">
                <div className="h-30 block relative rounded-md overflow-hidden text-background">
                  <video className="w-47.5 h-30 block absolute -top-30 -left-47.5 -z-100 my-30 mx-47.5 overflow-clip object-cover bg-cover [background-position:50%_50%] max-md:w-48 max-md:-left-48 max-md:mx-48" style={{ backgroundImage: "url(\"/assets/cloned/images/72b06c1691d5.jpg\")" }} autoPlay id="eea44be6-ef24-1e22-713c-bcdf67c85beb-video" loop muted playsInline poster="/assets/cloned/images/9c79f8fa3b5b.jpg">
                    <source className="inline text-color-004 [font-family:'Times_New_Roman'] leading-4.5" data-ditto-id="style-div-21" src="/assets/cloned/videos/4836a61465c6.mp4" />
                    <source className="inline text-color-004 [font-family:'Times_New_Roman'] leading-4.5" src="/assets/cloned/videos/209c240f795b.webm" />
                  </video>
                  <div className="block" aria-live="polite">
                    <button className="w-10 h-10 block absolute right-4 bottom-4 text-center cursor-pointer" data-component="button" aria-controls="eea44be6-ef24-1e22-713c-bcdf67c85beb-video" type="button">
                      <span className="inline">
                        <img className="w-full h-10 block max-w-full overflow-clip object-cover aspect-[auto_30/30] align-middle" data-component="image" alt="Pause video" height="30" src="/assets/cloned/svg/5eb5fbcbf2ae.svg" width="30" />
                      </span>
                    </button>
                  </div>
                </div>
              </div>
              <div className="flex flex-col gap-2.5" data-ditto-id="style-div-62">
                <div className="flex gap-4" data-ditto-id="style-div-14">
                  <div className="block max-w-5.5">
                    <div className="block">
                      <img className="w-full h-5 block max-w-full overflow-clip object-cover aspect-[auto_22/20] align-middle" data-component="image" alt="" height="20" src="/assets/cloned/svg/91accd9c6760.svg" width="22" />
                    </div>
                  </div>
                  <div className="block text-background text-xl font-medium leading-6.5 tracking-[-0.4px] max-lg:text-lg max-lg:leading-[1.4375rem]">
                    Find our clinic
                  </div>
                </div>
                <div className="block max-w-[14.1875rem] max-lg:max-w-none">
                  <div className="block text-background">
                    123 Riverbend, California 94025, USA
                  </div>
                </div>
              </div>
            </div>
          </div>
        </div>
      </section>
      <section className="block py-30 max-lg:pt-[3.3125rem] max-lg:pb-15">
        <div className="block max-w-407.5 px-[0.9375rem] mx-auto before:content-['_'] before:table before:w-0 before:h-0 before:text-foreground before:text-base before:leading-7 after:content-['_'] after:table after:w-0 after:h-0 after:text-foreground after:text-base after:leading-7">
          <div className="block">
            <div className="flex justify-between items-start gap-7.5 max-md:flex-col max-md:items-stretch max-md:grid-cols-[1fr_1fr] max-md:grid-rows-[auto] max-md:[grid-auto-columns:1fr]">
              <div className="block relative max-w-[45.5625rem] flex-1">
                <div className="block mb-[1.5625rem] max-lg:mb-[0.9375rem]">
                  <div className="flex justify-start items-center gap-[0.4rem]">
                    <div className="w-[0.3125rem] h-[0.3125rem] block bg-color-004" />
                    <div className="block text-color-001 text-lg leading-[1.75rem] tracking-[-0.54px] max-md:leading-[1.5625rem] max-md:[font-size:inherit] md:max-lg:text-[1.0625rem] md:max-lg:leading-[1.625rem]">
                      Quick help guide
                    </div>
                  </div>
                </div>
                <div className="block rounded-[5px] overflow-hidden">
                  <img className="w-full h-119 block max-w-full overflow-clip object-cover aspect-[auto_729/569] align-middle max-md:h-[16.8125rem] md:max-lg:h-69 2xl:h-[35.5625rem]" data-component="image" alt="faq-left-image" height="569" sizes="(max-width: 767px) 100vw, (max-width: 991px) 728px, 729px" src="/assets/cloned/images/7c24cf11d3cf.webp" srcSet="/assets/cloned/images/cdbb14f09b2b.webp 500w, /assets/cloned/images/96ff31f7b95a.webp 800w, /assets/cloned/images/6ab2f7ccc69b.webp 1080w, /assets/cloned/images/7c24cf11d3cf.webp 1458w" width="729" />
                </div>
              </div>
              <div className="flex max-w-[45.4375rem] flex-col items-start flex-1 gap-12.5 max-md:gap-5 max-md:max-w-none md:max-lg:gap-7.5">
                <h2 className="block text-color-001 text-[2.625rem] font-semibold leading-[3rem] tracking-[-0.84px] max-md:text-[1.5625rem] max-md:leading-[1.8125rem] md:max-lg:text-3xl md:max-lg:leading-[2.125rem]" data-component="heading">
                  Frequently asked questions
                </h2>
                <div className="w-full flex rounded-[15px] flex-col items-stretch gap-8.5 max-lg:gap-6" data-ditto-id="style-div-64">
                  <div className="border-b border-solid border-b-border flex relative z-900 pb-2.5 flex-col justify-between items-stretch text-left">
                    <div className="w-full flex relative mb-[1.5625rem] justify-between items-center gap-2.5 align-top text-color-002 whitespace-nowrap text-nowrap cursor-pointer max-md:mb-4 max-md:gap-8 md:max-lg:mb-[1.0625rem]" data-ditto-id="style-div-22" data-component="button" aria-controls="w-dropdown-list-2" aria-expanded="false" aria-haspopup="menu" id="w-dropdown-toggle-2" role="button">
                      <div className="block text-color-001 text-xl font-medium leading-6.5 tracking-[-0.4px] whitespace-normal max-lg:text-lg max-lg:leading-[1.4375rem]">
                        Do I need an appointment before visiting the clinic?
                      </div>
                      <div className="flex max-w-3 transform-[matrix(-1,0,0,-1,0,0)] origin-[6px_3.42188px] max-md:origin-[4.69531px_2.67969px] md:max-lg:origin-[5.16406px_2.94531px]">
                        <img className="w-full h-[0.4375rem] block max-w-full overflow-clip object-cover aspect-[auto_12/6] align-middle max-md:h-[0.3125rem] md:max-lg:h-1.5" data-component="image" alt="" height="6" src="/assets/cloned/svg/a446313568d7.svg" width="12" />
                      </div>
                    </div>
                    <nav className="block min-w-full overflow-hidden bg-clr-15" data-component="nav" aria-labelledby="w-dropdown-toggle-2" id="w-dropdown-list-2">
                      <div className="w-full max-w-157.5 block pb-5.5 max-lg:pb-3.5" data-ditto-id="style-div-23">
                        <p className="block">
                          Yes, appointments are recommended to ensure adequate consultation time, reduced waiting, and personalized attention from specialists.
                        </p>
                      </div>
                    </nav>
                  </div>
                  {MediaTile_data.map((d, i) => <MediaTile key={i} d={d} styles={MediaTile_styles[i]} />)}
                </div>
              </div>
            </div>
          </div>
        </div>
      </section>
    </>
  );
}
