import "./ditto.css";
import Logo from "./components/logo";
import MediaTile from "./components/media-tile";
import MediaTile2 from "./components/media-tile2";
import MediaTile3 from "./components/media-tile3";
// Generated by clone-site. Do not edit by hand.
const Logo_data = [
    { imgSrc: "/assets/cloned/images/65be8e0e9c90.webp" },
    { imgSrc: "/assets/cloned/images/034b99219bf4.webp" },
    { imgSrc: "/assets/cloned/images/b0c6f9ecfb23.webp" },
    { imgSrc: "/assets/cloned/images/9ebcf73e8e4c.webp" }
];
const MediaTile_data = [
    { text: "Basic care plan", description: "Basic dermatology care plan", text2: "$149", imgSrc: "/assets/cloned/svg/937b7bc944f4.svg", text3: "Skin consultation session", imgSrc2: "/assets/cloned/svg/937b7bc944f4.svg", text4: "Basic acne treatment", imgSrc3: "/assets/cloned/svg/937b7bc944f4.svg", text5: "Routine skin analysis", imgSrc4: "/assets/cloned/svg/937b7bc944f4.svg", text6: "Prescription guidance support" },
    { style: { backgroundImage: "url(\"/assets/cloned/svg/3a46de8cfc8c.svg\")" }, text: "Advanced care plan", description: "Comprehensive advanced care services", text2: "$299", imgSrc: "/assets/cloned/svg/067e45ca67a5.svg", text3: "Detailed skin assessment", imgSrc2: "/assets/cloned/svg/067e45ca67a5.svg", text4: "Customized treatment plan", imgSrc3: "/assets/cloned/svg/067e45ca67a5.svg", text5: "Chemical peel sessions", imgSrc4: "/assets/cloned/svg/067e45ca67a5.svg", text6: "Laser therapy options" },
    { text: "Premium skin plan", description: "High-end dermatology care", text2: "$499", imgSrc: "/assets/cloned/svg/937b7bc944f4.svg", text3: "Comprehensive skin evaluation", imgSrc2: "/assets/cloned/svg/937b7bc944f4.svg", text4: "Advanced laser treatments", imgSrc3: "/assets/cloned/svg/937b7bc944f4.svg", text5: "Anti-aging therapy sessions", imgSrc4: "/assets/cloned/svg/937b7bc944f4.svg", text6: "Personalized skincare regimen" }
];
const MediaTile2_data = [
    { text: "No hidden charges policy" },
    { text: "Flexible plan upgrades" },
    { text: "Personalized treatment approach" }
];
const MediaTile3_data = [
    { imgSrc: "/assets/cloned/images/4c7b15cb7f8d.webp", srcSet: "/assets/cloned/images/ea3e7c2d23b2.webp 500w, /assets/cloned/images/4c7b15cb7f8d.webp 760w", text: "Advanced treatments with clinical excellence", description: "Advanced treatments delivered with clinical excellence" },
    { imgSrc: "/assets/cloned/images/9aa6f611c7a6.webp", srcSet: "/assets/cloned/images/32e0acd7333b.webp 500w, /assets/cloned/images/9aa6f611c7a6.webp 760w", text: "Trusted experts delivering proven results", description: "Experienced specialists delivering reliable proven outcomes" },
    { imgSrc: "/assets/cloned/images/05273eae95af.webp", srcSet: "/assets/cloned/images/56935d329a93.webp 500w, /assets/cloned/images/05273eae95af.webp 760w", text: "Personalized care backed by expertise", description: "Customized skin care solutions delivered by experienced professionals" }
];
const Logo_meta: string[][] = [
    ["style-div", "n44"],
    ["style-pass", "n46"],
    ["style-div-25", "style-button"],
    ["style-div-26", "style-image"]
];
const MediaTile_meta: string[][] = [
    ["style-heading-2", "style-div-4", "style-div-34", "style-link", "style-image-3", "style-div-35", "style-div-36", "style-div-37", "style-div-38", "style-div-39", "style-div-40", "style-div-2", "style-div-41", "style-section", "style-div-42", "style-div-43", "n78", "n79", "style-div-6", "n81", "style-div-7", "n83", "style-div-8", "n85", "style-p", "style-div-24", "style-div-11", "n89", "n90", "style-div-44", "style-div-45", "style-div-46"],
    ["style-div-12", "style-div-47", "style-div-48", "style-div-49", "style-div-50", "style-div-51", "style-div-9", "style-div-52", "style-div-53", "style-div-54", "style-div-55", "style-div-56", "style-div-57", "style-div-58", "style-div-59", "style-div-60", "style-div-61", "n111", "n112", "n113", "n114", "n115", "n116", "n117", "n118", "n119", "style-div-21", "n121", "n122", "n123", "n124", "n125"],
    ["style-div-62", "style-div-14", "n128", "n129", "n130", "n131", "n132", "n133", "n134", "n135", "n136", "n137", "n138", "n139", "n140", "n141", "n142", "n143", "n144", "n145", "n146", "style-div-64", "n148", "style-div-22", "n150", "n151", "n152", "n153", "style-div-23", "n155", "n156", "n157"]
];
const MediaTile2_meta: string[][] = [
    ["n172", "n173", "n174", "n175"],
    ["n176", "n177", "n178", "n179"],
    ["n180", "n181", "style-div-65", "n183"]
];
const MediaTile3_meta: string[][] = [
    ["n196", "n197", "n198", "n199", "n200", "n201"],
    ["n202", "n203", "style-div-67", "n205", "n206", "n207"],
    ["n208", "n209", "n210", "n211", "n212", "n213"]
];
const Logo_styles = [
    { className: "z-10 transform-[matrix3d(1,0,0,0,0,1,0,0,0,0,1,0,0,0,109.44,1)] max-md:transform-[matrix3d(1,0,0,0,0,1,0,0,0,0,1,0,0,0,-88,1)]" },
    { className: "z-9 transform-[matrix3d(0,0,1,0,0,1,0,0,-1,0,0,0,109.44,0,0,1)] max-md:transform-[matrix3d(0,0,1,0,0,1,0,0,-1,0,0,0,88,0,-1,1)]" },
    { className: "z-8 transform-[matrix3d(0,0,-1,0,0,1,0,0,1,0,0,0,-110,0,0,1)] max-md:transform-[matrix3d(0,0,-1,0,0,1,0,0,1,0,0,0,-88,0,0,1)]" },
    { className: "z-7 transform-[matrix3d(-1,0,0,0,0,1,0,0,0,0,-1,0,0,0,-110,1)] max-md:transform-[matrix3d(-1,0,0,0,0,1,0,0,0,0,-1,0,0,0,88,1)]" }
];
const MediaTile_styles = [
    { className: "bg-background", className2: "text-color-001", className4: "text-color-001", className6: "border-color-003 bg-color-003", className7: "w-[307.3px] bg-color-006", className8: "text-color-001" },
    { className: "bg-color-003 [background-position:100%_100%] bg-no-repeat", className2: "text-background", className3: "text-background", className4: "text-background", className5: "text-background", className6: "border-surface-2 bg-surface-4", className7: "w-[307.3px] bg-color-001", className8: "justify-center items-center text-background", className9: "text-background", className10: "text-background", className11: "text-background", className12: "text-background" },
    { className: "bg-background", className2: "text-color-001", className4: "text-color-001", className6: "border-color-003 bg-color-003", className7: "w-[19.2125rem] bg-color-006", className8: "text-color-001" }
];
const MediaTile2_styles = [
    { className: "border-t border-t-border max-lg:py-[1.0625rem]" },
    {  },
    { className2: "md:max-lg:w-[14.9px]", className3: "md:max-lg:h-[0.9375rem]" }
];
const MediaTile3_styles = [
    { className: "relative z-1", className2: "h-58" },
    { className: "relative z-1", className2: "h-58" },
    { className2: "h-[14.5625rem]" }
];

export default function Page() {
  return (
    <>
      <section className="block relative z-11 bg-color-004" data-ditto-id="style-div-5">
        <div className="h-full block absolute top-0 inset-x-0" data-ditto-id="style-div-13">
          <img className="w-full h-[54.8125rem] block max-w-full overflow-clip object-cover aspect-[auto_1920/953] align-middle max-md:h-189.5 md:max-lg:h-200 2xl:h-[58.8125rem]" data-component="image" alt="pricing bg section " height="953" sizes="(max-width: 1919px) 100vw, 1920px" src="/assets/cloned/images/ec65eeb359f4.webp" srcSet="/assets/cloned/images/51a085d3166a.webp 500w, /assets/cloned/images/7cea75f4036c.webp 800w, /assets/cloned/images/62fca5232e9f.webp 1080w, /assets/cloned/images/1cd32a27cc51.webp 1600w, /assets/cloned/images/b047d67528ef.webp 2000w, /assets/cloned/images/02df5be3ef16.webp 2600w, /assets/cloned/images/7a8e1ab16b68.webp 3200w, /assets/cloned/images/ec65eeb359f4.webp 3840w" width="1920" />
        </div>
        <div className="block max-w-407.5 px-[0.9375rem] mx-auto before:content-['_'] before:table before:w-0 before:h-0 before:text-foreground before:text-base before:leading-7 after:content-['_'] after:table after:w-0 after:h-0 after:text-foreground after:text-base after:leading-7">
          <div className="flex relative z-11 pt-42.5 pb-13.5 flex-col items-stretch">
            <div className="flex pb-24 flex-col justify-center items-center gap-15 max-md:pb-5 max-lg:gap-7.5">
              <div className="block">
                <div className="w-[5.5%] h-67.5 block relative justify-center items-center transform-[matrix3d(-0.0597175,0,0.998215,0,0,1,0,0,-0.998215,0,-0.0597175,0,0,0,-108.8,1)] origin-[110px_135px] mx-auto max-md:w-[14%] max-md:h-60 max-md:transform-[matrix3d(-0.145612,0,0.989342,0,0,1,0,0,-0.989342,0,-0.145612,0,0,0,-108.8,1)] max-md:origin-[88px_120px] md:max-lg:w-[95%] md:max-lg:transform-[matrix3d(0.999915,0,-0.0130372,0,0,1,0,0,0.0130372,0,0.999915,0,0,0,-108.8,1)] 2xl:w-[19%] 2xl:transform-[matrix3d(-0.201726,0,0.979442,0,0,1,0,0,-0.979442,0,-0.201726,0,0,0,-108.8,1)] 2xl:mx-0">
                  {Logo_data.map((d, i) => <Logo key={i} d={d} styles={Logo_styles[i]} />)}
                </div>
              </div>
              <div className="w-full max-w-187 flex flex-col gap-5 text-center" data-ditto-id="style-div-27">
                <h1 className="block text-background text-6xl font-semibold leading-[4rem] tracking-[-1.2px] max-md:text-[2.1875rem] max-md:leading-[2.3125rem] md:max-lg:text-[2.5rem] md:max-lg:leading-[2.625rem]" data-ditto-id="style-div-28" data-component="heading">
                  Affordable dermatology treatment plans
                </h1>
                <p className="block text-background" data-ditto-id="style-div-29">
                  Transparent pricing for trusted treatments
                </p>
              </div>
            </div>
            <div className="flex justify-between max-md:flex-col max-md:justify-start max-md:items-center max-md:gap-[0.9375rem] max-md:text-center 2xl:pt-16" data-ditto-id="style-div-30">
              <div className="block max-w-65" data-ditto-id="style-image-2">
                <div className="block text-background text-xl font-medium leading-6.5 tracking-[-0.4px] max-lg:text-lg max-lg:leading-[1.4375rem]" data-ditto-id="style-div-31">
                  Derma - Affordable solutions for skin and hair
                </div>
              </div>
              <div className="block justify-center items-center text-background text-lg font-medium leading-6 tracking-[-0.36px] max-lg:text-[1.0625rem] max-lg:leading-[1.4375rem]" data-ditto-id="style-div-32">
                *Advanced Dermatology
              </div>
            </div>
          </div>
        </div>
      </section>
      <section className="block pt-[7.0625rem] pb-30 bg-surface max-md:pt-12 max-lg:pb-15 md:max-lg:pt-[3.3125rem]" data-ditto-id="style-div-3">
        <div className="block max-w-407.5 px-[0.9375rem] mx-auto before:content-['_'] before:table before:w-0 before:h-0 before:text-foreground before:text-base before:leading-7 after:content-['_'] after:table after:w-0 after:h-0 after:text-foreground after:text-base after:leading-7" data-ditto-id="style-div-33">
          <div className="block" data-ditto-id="style-heading">
            <div className="grid gap-12.5 [grid-auto-columns:1fr] grid-cols-3 max-lg:gap-7.5 max-md:grid-cols-1 md:max-lg:grid-cols-2" data-ditto-id="style-div-10">
              {MediaTile_data.map((d, i) => <MediaTile key={i} d={d} styles={MediaTile_styles[i]} />)}
            </div>
          </div>
        </div>
      </section>
      <section className="block py-30 max-lg:py-15">
        <div className="block max-w-407.5 px-[0.9375rem] mx-auto before:content-['_'] before:table before:w-0 before:h-0 before:text-foreground before:text-base before:leading-7 after:content-['_'] after:table after:w-0 after:h-0 after:text-foreground after:text-base after:leading-7">
          <div className="flex justify-between items-center gap-7.5 max-md:grid max-md:gap-[0.9375rem] max-md:grid-cols-[345px] max-md:[grid-auto-columns:1fr]">
            <div className="block max-w-[45.5625rem] rounded-[5px] self-stretch flex-1 overflow-hidden max-md:max-w-none">
              <img className="w-full h-174.5 block max-w-full overflow-clip object-cover aspect-[auto_729/644] align-middle max-md:h-[24.6875rem] md:max-lg:h-[30.3125rem] 2xl:h-208.5" data-component="image" alt="faq-left-image-2" height="644" sizes="(max-width: 767px) 100vw, (max-width: 991px) 728px, 729px" src="/assets/cloned/images/e1a60e9bb150.webp" srcSet="/assets/cloned/images/823e8e74a81f.webp 500w, /assets/cloned/images/884f48f1bec6.webp 800w, /assets/cloned/images/e1a60e9bb150.webp 1040w" width="729" />
            </div>
            <div className="flex max-w-[45.4375rem] flex-col items-start flex-1 max-md:self-stretch max-md:max-w-none">
              <div className="w-full max-w-132.5 block mb-[5.8125rem] max-lg:mb-7.5">
                <div className="block mb-[1.5625rem] max-lg:mb-[0.9375rem]">
                  <div className="flex justify-start items-center gap-[0.4rem]">
                    <div className="w-[0.3125rem] h-[0.3125rem] block bg-color-004" />
                    <div className="block text-color-001 text-lg leading-[1.75rem] tracking-[-0.54px] max-md:leading-[1.5625rem] max-md:[font-size:inherit] md:max-lg:text-[1.0625rem] md:max-lg:leading-[1.625rem]">
                      Trusted pricing model
                    </div>
                  </div>
                </div>
                <h2 className="block mb-[1.5625rem] text-color-001 text-[2.625rem] font-semibold leading-[3rem] tracking-[-0.84px] max-lg:mb-[0.9375rem] max-md:text-[1.5625rem] max-md:leading-[1.8125rem] md:max-lg:text-3xl md:max-lg:leading-[2.125rem]" data-component="heading">
                  Why choose our transparent pricing plans
                </h2>
                <p className="block">
                  Transparent pricing ensures trust and clarity
                </p>
              </div>
              <div className="flex flex-col items-stretch self-stretch">
                {MediaTile2_data.map((d, i) => <MediaTile2 key={i} d={d} styles={MediaTile2_styles[i]} />)}
              </div>
            </div>
          </div>
        </div>
      </section>
      <section className="block pt-[7.0625rem] pb-30 overflow-hidden bg-surface max-lg:pt-[3.3125rem] max-lg:pb-15">
        <div className="block max-w-407.5 px-[0.9375rem] mx-auto before:content-['_'] before:table before:w-0 before:h-0 before:text-foreground before:text-base before:leading-7 after:content-['_'] after:table after:w-0 after:h-0 after:text-foreground after:text-base after:leading-7">
          <div className="flex pb-12.5 flex-col justify-start items-center text-center max-lg:pb-7.5">
            <div className="block mb-[1.5625rem] max-lg:mb-[0.9375rem]">
              <div className="flex justify-start items-center gap-[0.4rem]">
                <div className="w-[0.3125rem] h-[0.3125rem] block bg-color-004" />
                <div className="block text-color-001 text-lg leading-[1.75rem] tracking-[-0.54px] max-md:leading-[1.5625rem] max-md:[font-size:inherit] md:max-lg:text-[1.0625rem] md:max-lg:leading-[1.625rem]">
                  Who
                </div>
                <div className="block text-lg leading-[1.75rem] tracking-[-0.54px] max-md:leading-[1.5625rem] max-md:[font-size:inherit] md:max-lg:text-[1.0625rem] md:max-lg:leading-[1.625rem]">
                  {" we are"}
                </div>
              </div>
            </div>
            <div className="w-full max-w-[32.1875rem] block justify-center items-center">
              <h2 className="block mb-[1.5625rem] text-color-001 text-[2.625rem] font-semibold leading-[3rem] tracking-[-0.84px] max-lg:mb-[0.9375rem] max-md:text-[1.5625rem] max-md:leading-[1.8125rem] md:max-lg:text-3xl md:max-lg:leading-[2.125rem]" data-ditto-id="style-div-66" data-component="heading">
                Why trust our expert skin care clinic
              </h2>
            </div>
            <p className="block">
              Personalized care backed by expertise
            </p>
          </div>
          <div className="grid items-start gap-12.5 [grid-auto-columns:1fr] justify-items-stretch grid-cols-3 max-lg:gap-7.5 max-md:grid-cols-1">
            {MediaTile3_data.map((d, i) => <MediaTile3 key={i} d={d} styles={MediaTile3_styles[i]} />)}
          </div>
        </div>
      </section>
      <section className="block pb-[7.0625rem] bg-surface max-lg:pb-[3.3125rem]">
        <div className="block max-w-407.5 px-[0.9375rem] mx-auto before:content-['_'] before:table before:w-0 before:h-0 before:text-foreground before:text-base before:leading-7 after:content-['_'] after:table after:w-0 after:h-0 after:text-foreground after:text-base after:leading-7">
          <div className="grid [grid-auto-columns:1fr] grid-cols-3 max-md:flex max-md:flex-col max-md:gap-[2.3rem] max-md:grid-cols-[repeat(auto-fit,_minmax(230px,_1fr))]">
            <div className="block max-w-[23.3125rem] max-md:max-w-none">
              <div className="border-b border-solid border-b-border flex pb-[1.8rem] justify-between items-center max-md:pb-2.5 max-md:items-start">
                <div className="flex items-start">
                  <div className="h-16 flex overflow-hidden max-md:h-[2.4rem] md:max-lg:h-[2.7rem]">
                    <div className="flex flex-col gap-2.5 max-lg:block max-lg:[flex-direction:initial] max-lg:gap-[initial]">
                      <div className="flex flex-col gap-2.5 transform-[matrix(1,0,0,1,0,-137.188)] max-lg:block max-md:transform-[matrix(1,0,0,1,0,-74.1875)] max-lg:[flex-direction:initial] max-lg:gap-[initial] md:max-lg:transform-[matrix(1,0,0,1,0,-84.8125)] 2xl:justify-center">
                        <div className="block text-color-001 text-6xl font-medium leading-[4rem] tracking-[-1.2px] max-md:text-[2.1875rem] max-md:leading-[2.3125rem] md:max-lg:text-[2.5rem] md:max-lg:leading-[2.625rem]">
                          0
                        </div>
                        <div className="block text-color-001 text-6xl font-medium leading-[4rem] tracking-[-1.2px] max-md:text-[2.1875rem] max-md:leading-[2.3125rem] md:max-lg:text-[2.5rem] md:max-lg:leading-[2.625rem]">
                          1
                        </div>
                      </div>
                      <div className="flex flex-col gap-2.5 transform-[matrix(1,0,0,1,0,-137.188)] max-lg:block max-md:transform-[matrix(1,0,0,1,0,-74.1875)] max-lg:[flex-direction:initial] max-lg:gap-[initial] md:max-lg:transform-[matrix(1,0,0,1,0,-84.8125)] 2xl:justify-center">
                        <div className="block text-color-001 text-6xl font-medium leading-[4rem] tracking-[-1.2px] max-md:text-[2.1875rem] max-md:leading-[2.3125rem] md:max-lg:text-[2.5rem] md:max-lg:leading-[2.625rem]">
                          2
                        </div>
                        <div className="block text-color-001 text-6xl font-medium leading-[4rem] tracking-[-1.2px] max-md:text-[2.1875rem] max-md:leading-[2.3125rem] md:max-lg:text-[2.5rem] md:max-lg:leading-[2.625rem]">
                          1
                        </div>
                      </div>
                    </div>
                    <div className="flex flex-col gap-2.5 max-lg:block max-lg:[flex-direction:initial] max-lg:gap-[initial]">
                      <div className="flex flex-col gap-2.5 transform-[matrix(1,0,0,1,0,-357.969)] max-lg:block max-md:transform-[matrix(1,0,0,1,0,-185.469)] max-lg:[flex-direction:initial] max-lg:gap-[initial] md:max-lg:transform-[matrix(1,0,0,1,0,-212.031)] 2xl:justify-center">
                        <div className="block text-color-001 text-6xl font-medium leading-[4rem] tracking-[-1.2px] max-md:text-[2.1875rem] max-md:leading-[2.3125rem] md:max-lg:text-[2.5rem] md:max-lg:leading-[2.625rem]">
                          0
                        </div>
                        <div className="block text-color-001 text-6xl font-medium leading-[4rem] tracking-[-1.2px] max-md:text-[2.1875rem] max-md:leading-[2.3125rem] md:max-lg:text-[2.5rem] md:max-lg:leading-[2.625rem]">
                          1
                        </div>
                        <div className="block text-color-001 text-6xl font-medium leading-[4rem] tracking-[-1.2px] max-md:text-[2.1875rem] max-md:leading-[2.3125rem] md:max-lg:text-[2.5rem] md:max-lg:leading-[2.625rem]">
                          2
                        </div>
                        <div className="block text-color-001 text-6xl font-medium leading-[4rem] tracking-[-1.2px] max-md:text-[2.1875rem] max-md:leading-[2.3125rem] md:max-lg:text-[2.5rem] md:max-lg:leading-[2.625rem]">
                          3
                        </div>
                        <div className="block text-color-001 text-6xl font-medium leading-[4rem] tracking-[-1.2px] max-md:text-[2.1875rem] max-md:leading-[2.3125rem] md:max-lg:text-[2.5rem] md:max-lg:leading-[2.625rem]">
                          4
                        </div>
                      </div>
                      <div className="flex flex-col gap-2.5 transform-[matrix(1,0,0,1,0,-357.969)] max-lg:block max-md:transform-[matrix(1,0,0,1,0,-185.469)] max-lg:[flex-direction:initial] max-lg:gap-[initial] md:max-lg:transform-[matrix(1,0,0,1,0,-212.031)] 2xl:justify-center">
                        <div className="block text-color-001 text-6xl font-medium leading-[4rem] tracking-[-1.2px] max-md:text-[2.1875rem] max-md:leading-[2.3125rem] md:max-lg:text-[2.5rem] md:max-lg:leading-[2.625rem]">
                          5
                        </div>
                        <div className="block text-color-001 text-6xl font-medium leading-[4rem] tracking-[-1.2px] max-md:text-[2.1875rem] max-md:leading-[2.3125rem] md:max-lg:text-[2.5rem] md:max-lg:leading-[2.625rem]">
                          1
                        </div>
                        <div className="block text-color-001 text-6xl font-medium leading-[4rem] tracking-[-1.2px] max-md:text-[2.1875rem] max-md:leading-[2.3125rem] md:max-lg:text-[2.5rem] md:max-lg:leading-[2.625rem]">
                          2
                        </div>
                        <div className="block text-color-001 text-6xl font-medium leading-[4rem] tracking-[-1.2px] max-md:text-[2.1875rem] max-md:leading-[2.3125rem] md:max-lg:text-[2.5rem] md:max-lg:leading-[2.625rem]">
                          3
                        </div>
                        <div className="block text-color-001 text-6xl font-medium leading-[4rem] tracking-[-1.2px] max-md:text-[2.1875rem] max-md:leading-[2.3125rem] md:max-lg:text-[2.5rem] md:max-lg:leading-[2.625rem]">
                          4
                        </div>
                      </div>
                    </div>
                  </div>
                  <div className="block -mt-[0.4rem] max-md:-mt-[0.1rem] md:max-lg:-mt-[0.3125rem]">
                    <div className="block text-color-004 [font-family:Merriweather,_serif] text-3xl leading-10 max-md:text-[1.375rem] max-md:leading-[1.8125rem] md:max-lg:text-[1.625rem] md:max-lg:leading-[2.1875rem]" data-ditto-id="style-div-68">
                      +
                    </div>
                  </div>
                </div>
                <div className="w-[4.0625rem] h-[4.0625rem] flex rounded-[100%] flex-col justify-center items-center bg-background max-md:w-12 max-md:h-12">
                  <div className="block">
                    <img className="w-full h-[2.1875rem] block max-w-full overflow-clip object-cover aspect-[auto_35/35] align-middle max-md:h-[1.3125rem]" data-component="image" alt="" height="35" src="/assets/cloned/svg/e56150272e53.svg" width="35" />
                  </div>
                </div>
              </div>
              <div className="w-full max-w-64.5 block pt-7.5 max-md:pt-2.5">
                <div className="block text-color-001 text-xl font-medium leading-6.5 tracking-[-0.4px] max-lg:text-lg max-lg:leading-[1.4375rem]">
                  Specialized advanced hair treatment care
                </div>
              </div>
            </div>
            <div className="block max-w-[23.3125rem] max-md:max-w-none">
              <div className="border-b border-solid border-b-border flex pb-[1.8rem] justify-between items-center max-md:pb-2.5 max-md:items-start">
                <div className="flex">
                  <div className="h-16 flex overflow-hidden max-md:h-[2.4rem] md:max-lg:h-[2.7rem]">
                    <div className="flex flex-col gap-2.5 max-lg:block max-lg:[flex-direction:initial] max-lg:gap-[initial]">
                      <div className="flex flex-col gap-2.5 transform-[matrix(1,0,0,1,0,-652.344)] max-lg:block max-md:transform-[matrix(1,0,0,1,0,-333.844)] max-lg:[flex-direction:initial] max-lg:gap-[initial] md:max-lg:transform-[matrix(1,0,0,1,0,-381.656)] 2xl:justify-center">
                        <div className="block text-color-001 text-6xl font-medium leading-[4rem] tracking-[-1.2px] max-md:text-[2.1875rem] max-md:leading-[2.3125rem] md:max-lg:text-[2.5rem] md:max-lg:leading-[2.625rem]">
                          0
                        </div>
                        <div className="block text-color-001 text-6xl font-medium leading-[4rem] tracking-[-1.2px] max-md:text-[2.1875rem] max-md:leading-[2.3125rem] md:max-lg:text-[2.5rem] md:max-lg:leading-[2.625rem]">
                          1
                        </div>
                        <div className="block text-color-001 text-6xl font-medium leading-[4rem] tracking-[-1.2px] max-md:text-[2.1875rem] max-md:leading-[2.3125rem] md:max-lg:text-[2.5rem] md:max-lg:leading-[2.625rem]">
                          2
                        </div>
                        <div className="block text-color-001 text-6xl font-medium leading-[4rem] tracking-[-1.2px] max-md:text-[2.1875rem] max-md:leading-[2.3125rem] md:max-lg:text-[2.5rem] md:max-lg:leading-[2.625rem]">
                          3
                        </div>
                        <div className="block text-color-001 text-6xl font-medium leading-[4rem] tracking-[-1.2px] max-md:text-[2.1875rem] max-md:leading-[2.3125rem] md:max-lg:text-[2.5rem] md:max-lg:leading-[2.625rem]">
                          4
                        </div>
                        <div className="block text-color-001 text-6xl font-medium leading-[4rem] tracking-[-1.2px] max-md:text-[2.1875rem] max-md:leading-[2.3125rem] md:max-lg:text-[2.5rem] md:max-lg:leading-[2.625rem]">
                          5
                        </div>
                        <div className="block text-color-001 text-6xl font-medium leading-[4rem] tracking-[-1.2px] max-md:text-[2.1875rem] max-md:leading-[2.3125rem] md:max-lg:text-[2.5rem] md:max-lg:leading-[2.625rem]">
                          6
                        </div>
                        <div className="block text-color-001 text-6xl font-medium leading-[4rem] tracking-[-1.2px] max-md:text-[2.1875rem] max-md:leading-[2.3125rem] md:max-lg:text-[2.5rem] md:max-lg:leading-[2.625rem]">
                          7
                        </div>
                        <div className="block text-color-001 text-6xl font-medium leading-[4rem] tracking-[-1.2px] max-md:text-[2.1875rem] max-md:leading-[2.3125rem] md:max-lg:text-[2.5rem] md:max-lg:leading-[2.625rem]">
                          8
                        </div>
                      </div>
                      <div className="flex flex-col gap-2.5 transform-[matrix(1,0,0,1,0,-652.344)] max-lg:block max-md:transform-[matrix(1,0,0,1,0,-333.844)] max-lg:[flex-direction:initial] max-lg:gap-[initial] md:max-lg:transform-[matrix(1,0,0,1,0,-381.656)] 2xl:justify-center" data-ditto-id="style-div-69">
                        <div className="block text-color-001 text-6xl font-medium leading-[4rem] tracking-[-1.2px] max-md:text-[2.1875rem] max-md:leading-[2.3125rem] md:max-lg:text-[2.5rem] md:max-lg:leading-[2.625rem]">
                          9
                        </div>
                        <div className="block text-color-001 text-6xl font-medium leading-[4rem] tracking-[-1.2px] max-md:text-[2.1875rem] max-md:leading-[2.3125rem] md:max-lg:text-[2.5rem] md:max-lg:leading-[2.625rem]">
                          1
                        </div>
                        <div className="block text-color-001 text-6xl font-medium leading-[4rem] tracking-[-1.2px] max-md:text-[2.1875rem] max-md:leading-[2.3125rem] md:max-lg:text-[2.5rem] md:max-lg:leading-[2.625rem]">
                          2
                        </div>
                        <div className="block text-color-001 text-6xl font-medium leading-[4rem] tracking-[-1.2px] max-md:text-[2.1875rem] max-md:leading-[2.3125rem] md:max-lg:text-[2.5rem] md:max-lg:leading-[2.625rem]">
                          3
                        </div>
                        <div className="block text-color-001 text-6xl font-medium leading-[4rem] tracking-[-1.2px] max-md:text-[2.1875rem] max-md:leading-[2.3125rem] md:max-lg:text-[2.5rem] md:max-lg:leading-[2.625rem]">
                          4
                        </div>
                        <div className="block text-color-001 text-6xl font-medium leading-[4rem] tracking-[-1.2px] max-md:text-[2.1875rem] max-md:leading-[2.3125rem] md:max-lg:text-[2.5rem] md:max-lg:leading-[2.625rem]">
                          5
                        </div>
                        <div className="block text-color-001 text-6xl font-medium leading-[4rem] tracking-[-1.2px] max-md:text-[2.1875rem] max-md:leading-[2.3125rem] md:max-lg:text-[2.5rem] md:max-lg:leading-[2.625rem]">
                          6
                        </div>
                        <div className="block text-color-001 text-6xl font-medium leading-[4rem] tracking-[-1.2px] max-md:text-[2.1875rem] max-md:leading-[2.3125rem] md:max-lg:text-[2.5rem] md:max-lg:leading-[2.625rem]">
                          7
                        </div>
                        <div className="block text-color-001 text-6xl font-medium leading-[4rem] tracking-[-1.2px] max-md:text-[2.1875rem] max-md:leading-[2.3125rem] md:max-lg:text-[2.5rem] md:max-lg:leading-[2.625rem]">
                          8
                        </div>
                      </div>
                    </div>
                    <div className="flex flex-col gap-2.5 max-lg:block max-lg:[flex-direction:initial] max-lg:gap-[initial]">
                      <div className="flex flex-col gap-2.5 transform-[matrix(1,0,0,1,0,-210.781)] max-lg:block max-md:transform-[matrix(1,0,0,1,0,-111.281)] max-lg:[flex-direction:initial] max-lg:gap-[initial] md:max-lg:transform-[matrix(1,0,0,1,0,-127.219)] 2xl:justify-center">
                        <div className="block text-color-001 text-6xl font-medium leading-[4rem] tracking-[-1.2px] max-md:text-[2.1875rem] max-md:leading-[2.3125rem] md:max-lg:text-[2.5rem] md:max-lg:leading-[2.625rem]">
                          0
                        </div>
                        <div className="block text-color-001 text-6xl font-medium leading-[4rem] tracking-[-1.2px] max-md:text-[2.1875rem] max-md:leading-[2.3125rem] md:max-lg:text-[2.5rem] md:max-lg:leading-[2.625rem]">
                          1
                        </div>
                        <div className="block text-color-001 text-6xl font-medium leading-[4rem] tracking-[-1.2px] max-md:text-[2.1875rem] max-md:leading-[2.3125rem] md:max-lg:text-[2.5rem] md:max-lg:leading-[2.625rem]">
                          2
                        </div>
                      </div>
                      <div className="flex flex-col gap-2.5 transform-[matrix(1,0,0,1,0,-210.781)] max-lg:block max-md:transform-[matrix(1,0,0,1,0,-111.281)] max-lg:[flex-direction:initial] max-lg:gap-[initial] md:max-lg:transform-[matrix(1,0,0,1,0,-127.219)] 2xl:justify-center">
                        <div className="block text-color-001 text-6xl font-medium leading-[4rem] tracking-[-1.2px] max-md:text-[2.1875rem] max-md:leading-[2.3125rem] md:max-lg:text-[2.5rem] md:max-lg:leading-[2.625rem]">
                          3
                        </div>
                        <div className="block text-color-001 text-6xl font-medium leading-[4rem] tracking-[-1.2px] max-md:text-[2.1875rem] max-md:leading-[2.3125rem] md:max-lg:text-[2.5rem] md:max-lg:leading-[2.625rem]" data-ditto-id="style-div-63">
                          1
                        </div>
                        <div className="block text-color-001 text-6xl font-medium leading-[4rem] tracking-[-1.2px] max-md:text-[2.1875rem] max-md:leading-[2.3125rem] md:max-lg:text-[2.5rem] md:max-lg:leading-[2.625rem]">
                          2
                        </div>
                      </div>
                    </div>
                  </div>
                  <div className="block -mt-[0.4rem] max-md:-mt-[0.1rem] md:max-lg:-mt-[0.3125rem]">
                    <div className="block text-color-004 [font-family:Merriweather,_serif] text-3xl leading-10 max-md:text-[1.375rem] max-md:leading-[1.8125rem] md:max-lg:text-[1.625rem] md:max-lg:leading-[2.1875rem]">
                      %
                    </div>
                  </div>
                </div>
                <div className="w-[4.0625rem] h-[4.0625rem] flex rounded-[100%] flex-col justify-center items-center bg-background max-md:w-12 max-md:h-12">
                  <div className="block">
                    <img className="w-full h-9.5 block max-w-full overflow-clip object-cover aspect-[auto_32/38] align-middle max-md:h-[1.5625rem]" data-component="image" alt="" height="38" src="/assets/cloned/svg/3ab92b50e772.svg" width="32" />
                  </div>
                </div>
              </div>
              <div className="block max-w-70.5 pt-7.5 max-md:pt-2.5 2xl:max-w-76">
                <div className="block text-color-001 text-xl font-medium leading-6.5 tracking-[-0.4px] max-lg:text-lg max-lg:leading-[1.4375rem]">
                  Excellent patient treatment satisfaction rate
                </div>
              </div>
            </div>
            <div className="block max-w-[23.3125rem] max-md:max-w-none">
              <div className="border-b border-solid border-b-border flex pb-[1.8rem] justify-between items-center max-md:pb-2.5 max-md:items-start">
                <div className="flex">
                  <div className="h-16 flex overflow-hidden max-md:h-[2.4rem] md:max-lg:h-[2.7rem]">
                    <div className="flex flex-col gap-2.5 max-lg:block max-lg:[flex-direction:initial] max-lg:gap-[initial]">
                      <div className="flex flex-col gap-2.5 transform-[matrix(1,0,0,1,0,-210.781)] max-lg:block max-md:transform-[matrix(1,0,0,1,0,-111.281)] max-lg:[flex-direction:initial] max-lg:gap-[initial] md:max-lg:transform-[matrix(1,0,0,1,0,-127.219)] 2xl:justify-center">
                        <div className="block text-color-001 text-6xl font-medium leading-[4rem] tracking-[-1.2px] max-md:text-[2.1875rem] max-md:leading-[2.3125rem] md:max-lg:text-[2.5rem] md:max-lg:leading-[2.625rem]">
                          0
                        </div>
                        <div className="block text-color-001 text-6xl font-medium leading-[4rem] tracking-[-1.2px] max-md:text-[2.1875rem] max-md:leading-[2.3125rem] md:max-lg:text-[2.5rem] md:max-lg:leading-[2.625rem]">
                          1
                        </div>
                        <div className="block text-color-001 text-6xl font-medium leading-[4rem] tracking-[-1.2px] max-md:text-[2.1875rem] max-md:leading-[2.3125rem] md:max-lg:text-[2.5rem] md:max-lg:leading-[2.625rem]">
                          2
                        </div>
                      </div>
                      <div className="flex flex-col gap-2.5 transform-[matrix(1,0,0,1,0,-210.781)] max-lg:block max-md:transform-[matrix(1,0,0,1,0,-111.281)] max-lg:[flex-direction:initial] max-lg:gap-[initial] md:max-lg:transform-[matrix(1,0,0,1,0,-127.219)] 2xl:justify-center">
                        <div className="block text-color-001 text-6xl font-medium leading-[4rem] tracking-[-1.2px] max-md:text-[2.1875rem] max-md:leading-[2.3125rem] md:max-lg:text-[2.5rem] md:max-lg:leading-[2.625rem]">
                          3
                        </div>
                        <div className="block text-color-001 text-6xl font-medium leading-[4rem] tracking-[-1.2px] max-md:text-[2.1875rem] max-md:leading-[2.3125rem] md:max-lg:text-[2.5rem] md:max-lg:leading-[2.625rem]">
                          1
                        </div>
                        <div className="block text-color-001 text-6xl font-medium leading-[4rem] tracking-[-1.2px] max-md:text-[2.1875rem] max-md:leading-[2.3125rem] md:max-lg:text-[2.5rem] md:max-lg:leading-[2.625rem]">
                          2
                        </div>
                      </div>
                    </div>
                    <div className="flex flex-col gap-2.5 max-lg:block max-lg:[flex-direction:initial] max-lg:gap-[initial]">
                      <div className="flex flex-col gap-2.5 transform-[matrix(1,0,0,1,0,-357.969)] max-lg:block max-md:transform-[matrix(1,0,0,1,0,-185.469)] max-lg:[flex-direction:initial] max-lg:gap-[initial] md:max-lg:transform-[matrix(1,0,0,1,0,-212.031)] 2xl:justify-center">
                        <div className="block text-color-001 text-6xl font-medium leading-[4rem] tracking-[-1.2px] max-md:text-[2.1875rem] max-md:leading-[2.3125rem] md:max-lg:text-[2.5rem] md:max-lg:leading-[2.625rem]">
                          0
                        </div>
                        <div className="block text-color-001 text-6xl font-medium leading-[4rem] tracking-[-1.2px] max-md:text-[2.1875rem] max-md:leading-[2.3125rem] md:max-lg:text-[2.5rem] md:max-lg:leading-[2.625rem]">
                          1
                        </div>
                        <div className="block text-color-001 text-6xl font-medium leading-[4rem] tracking-[-1.2px] max-md:text-[2.1875rem] max-md:leading-[2.3125rem] md:max-lg:text-[2.5rem] md:max-lg:leading-[2.625rem]" data-ditto-id="style-div-70">
                          2
                        </div>
                        <div className="block text-color-001 text-6xl font-medium leading-[4rem] tracking-[-1.2px] max-md:text-[2.1875rem] max-md:leading-[2.3125rem] md:max-lg:text-[2.5rem] md:max-lg:leading-[2.625rem]">
                          3
                        </div>
                        <div className="block text-color-001 text-6xl font-medium leading-[4rem] tracking-[-1.2px] max-md:text-[2.1875rem] max-md:leading-[2.3125rem] md:max-lg:text-[2.5rem] md:max-lg:leading-[2.625rem]">
                          4
                        </div>
                      </div>
                      <div className="flex flex-col gap-2.5 transform-[matrix(1,0,0,1,0,-357.969)] max-lg:block max-md:transform-[matrix(1,0,0,1,0,-185.469)] max-lg:[flex-direction:initial] max-lg:gap-[initial] md:max-lg:transform-[matrix(1,0,0,1,0,-212.031)] 2xl:justify-center">
                        <div className="block text-color-001 text-6xl font-medium leading-[4rem] tracking-[-1.2px] max-md:text-[2.1875rem] max-md:leading-[2.3125rem] md:max-lg:text-[2.5rem] md:max-lg:leading-[2.625rem]" data-ditto-id="style-div-71">
                          5
                        </div>
                        <div className="block text-color-001 text-6xl font-medium leading-[4rem] tracking-[-1.2px] max-md:text-[2.1875rem] max-md:leading-[2.3125rem] md:max-lg:text-[2.5rem] md:max-lg:leading-[2.625rem]">
                          1
                        </div>
                        <div className="block text-color-001 text-6xl font-medium leading-[4rem] tracking-[-1.2px] max-md:text-[2.1875rem] max-md:leading-[2.3125rem] md:max-lg:text-[2.5rem] md:max-lg:leading-[2.625rem]">
                          2
                        </div>
                        <div className="block text-color-001 text-6xl font-medium leading-[4rem] tracking-[-1.2px] max-md:text-[2.1875rem] max-md:leading-[2.3125rem] md:max-lg:text-[2.5rem] md:max-lg:leading-[2.625rem]">
                          3
                        </div>
                        <div className="block text-color-001 text-6xl font-medium leading-[4rem] tracking-[-1.2px] max-md:text-[2.1875rem] max-md:leading-[2.3125rem] md:max-lg:text-[2.5rem] md:max-lg:leading-[2.625rem]">
                          4
                        </div>
                      </div>
                    </div>
                  </div>
                  <div className="block -mt-[0.4rem] max-md:-mt-[0.1rem] md:max-lg:-mt-[0.3125rem]" data-ditto-id="style-div-72">
                    <div className="block text-color-004 [font-family:Merriweather,_serif] text-3xl leading-10 max-md:text-[1.375rem] max-md:leading-[1.8125rem] md:max-lg:text-[1.625rem] md:max-lg:leading-[2.1875rem]">
                      k
                    </div>
                  </div>
                </div>
                <div className="w-[4.0625rem] h-[4.0625rem] flex rounded-[100%] flex-col justify-center items-center bg-background max-md:w-12 max-md:h-12">
                  <div className="block">
                    <img className="w-full h-[2.1875rem] block max-w-full overflow-clip object-cover aspect-[auto_36/35] align-middle max-md:h-5" data-component="image" alt="" height="35" src="/assets/cloned/svg/8fa9ea6ee436.svg" width="36" />
                  </div>
                </div>
              </div>
              <div className="block max-w-60 pt-7.5 max-md:pt-2.5 2xl:max-w-68">
                <div className="block text-color-001 text-xl font-medium leading-6.5 tracking-[-0.4px] max-lg:text-lg max-lg:leading-[1.4375rem]">
                  Consultations successfully completed
                </div>
              </div>
            </div>
          </div>
        </div>
      </section>
      <section className="block relative">
        <div className="h-[552.1px] block relative overflow-hidden object-cover text-background max-md:h-[404.9px] md:max-lg:h-[22.4875rem]">
          <video className="w-320 h-138 block absolute top-[-552.1px] -left-320 -z-100 my-[552.1px] mx-320 overflow-clip object-cover bg-cover [background-position:50%_50%] max-md:w-[23.4375rem] max-md:h-[25.3125rem] max-md:top-[-404.9px] max-md:-left-[23.4375rem] max-md:my-[404.9px] max-md:mx-[23.4375rem] md:max-lg:w-192 md:max-lg:h-90 md:max-lg:-top-[22.4875rem] md:max-lg:-left-192 md:max-lg:my-[22.4875rem] md:max-lg:mx-192 2xl:w-480 2xl:-left-480 2xl:mx-480" style={{ backgroundImage: "url(\"/assets/cloned/images/39efc481f922.jpg\")" }} autoPlay id="1922aab1-d3c4-0e0b-20c8-9350f47edc50-video" loop muted playsInline>
            <source className="inline text-color-004 [font-family:'Times_New_Roman'] leading-4.5" src="/assets/cloned/videos/0fa572a32821.mp4" />
            <source className="inline text-color-004 [font-family:'Times_New_Roman'] leading-4.5" src="/assets/cloned/videos/17985cca7f95.webm" />
          </video>
          <div className="h-full block py-30 bg-clr-9 max-lg:py-15">
            <div className="h-full block max-w-407.5 px-[0.9375rem] mx-auto before:content-['_'] before:table before:w-0 before:h-0 before:text-background before:text-base before:leading-7 after:content-['_'] after:table after:w-0 after:h-0 after:text-background after:text-base after:leading-7">
              <div className="h-full flex relative z-2 pt-2.5 flex-col justify-start items-center gap-7.5 max-lg:gap-[0.9375rem] max-lg:pt-0">
                <div className="block" aria-live="polite">
                  <button className="h-10 inline-block right-4 bottom-4 text-center cursor-pointer max-md:top-[8%] max-md:left-[4%]" data-component="button" aria-controls="1922aab1-d3c4-0e0b-20c8-9350f47edc50-video" type="button">
                    <span className="inline">
                      <img className="w-full h-10 block max-w-full overflow-clip object-cover align-middle" data-component="image" alt="Pause video" src="/assets/cloned/svg/5eb5fbcbf2ae.svg" />
                    </span>
                  </button>
                </div>
                <div className="flex max-w-[41.9rem] flex-col justify-start items-center text-center max-md:max-w-none md:max-lg:max-w-159">
                  <h2 className="block mb-[1.5625rem] text-[2.625rem] font-semibold leading-[3rem] tracking-[-0.84px] max-lg:mb-[0.9375rem] max-md:text-[1.5625rem] max-md:leading-[1.8125rem] md:max-lg:text-3xl md:max-lg:leading-[2.125rem]" data-component="heading">
                    Need a personalized dermatology treatment quote?
                  </h2>
                  <div className="block mb-7.5 max-lg:mb-5">
                    Every skin condition needs personalized treatment and pricing.
                  </div>
                  <div className="block relative">
                    <a className="h-[2.775rem] flex relative z-0 max-w-full py-[0.6875rem] px-[1.3125rem] rounded-[50px] justify-between items-center gap-2.5 overflow-hidden text-foreground bg-surface-2 [backdrop-filter:blur(5px)] cursor-pointer" data-component="link" href="/contact">
                      <div className="h-[1.4rem] block relative z-1 overflow-hidden max-md:shrink-0">
                        <div className="block text-background leading-6 whitespace-nowrap">
                          Book an appointment
                        </div>
                        <div className="block text-background leading-6 whitespace-nowrap">
                          Book an appointment
                        </div>
                      </div>
                      <div className="w-[241.1px] h-[45.3px] flex absolute top-0 left-0 min-w-0 rounded-[50px] justify-center items-center bg-color-006 transform-[matrix(1,0,0,1,0,45.2656)] pointer-events-none" />
                      <div className="w-[0.5875rem] h-[0.6rem] flex relative z-1 mt-0.5 justify-center items-center max-md:shrink-0">
                        <img className="w-full h-2.5 block max-w-full overflow-clip object-cover aspect-[auto_9/9] align-middle" data-component="image" alt="button white arrow" height="9" src="/assets/cloned/svg/97bfaa7e2654.svg" width="9" />
                      </div>
                    </a>
                  </div>
                </div>
              </div>
            </div>
          </div>
        </div>
      </section>
      <section className="block py-30 overflow-hidden bg-surface max-lg:py-15">
        <div className="block max-w-407.5 px-[0.9375rem] mx-auto before:content-['_'] before:table before:w-0 before:h-0 before:text-foreground before:text-base before:leading-7 after:content-['_'] after:table after:w-0 after:h-0 after:text-foreground after:text-base after:leading-7">
          <div className="flex items-start">
            <div className="flex justify-start items-center gap-[0.4rem]">
              <div className="w-[0.3125rem] h-[0.3125rem] block bg-color-004" />
              <div className="block text-color-001 text-lg leading-[1.75rem] tracking-[-0.54px] max-md:leading-[1.5625rem] max-md:[font-size:inherit] md:max-lg:text-[1.0625rem] md:max-lg:leading-[1.625rem]">
                What our
              </div>
              <div className="block text-lg leading-[1.75rem] tracking-[-0.54px] max-md:leading-[1.5625rem] max-md:[font-size:inherit] md:max-lg:text-[1.0625rem] md:max-lg:leading-[1.625rem]">
                clients say
              </div>
            </div>
          </div>
          <div className="block pt-12.5 max-lg:pt-8">
            <div className="h-[34.4375rem] block relative clear-both text-center max-md:h-[868.1px] max-lg:flex max-lg:flex-col md:max-lg:h-[27.525rem]" aria-label="carousel" role="region">
              <div className="w-full max-w-267.5 h-full block relative z-1 whitespace-nowrap text-nowrap" id="w-slider-mask-0">
                <div className="w-full inline-block relative mr-12.5 align-top text-left whitespace-normal" aria-label="1 of 6" role="group">
                  <div className="flex justify-between items-center gap-12.5 max-md:grid max-lg:items-stretch max-lg:gap-7.5 max-md:grid-cols-[345px] max-md:[grid-auto-columns:1fr]">
                    <div className="block max-w-102.5 rounded-[5px] flex-1 overflow-hidden max-md:self-stretch max-md:max-w-none">
                      <img className="w-full h-[34.4375rem] block max-w-full overflow-clip object-cover aspect-[auto_410/551] align-middle max-md:h-116 md:max-lg:h-110" data-component="image" alt="client image two" height="551" sizes="(max-width: 479px) 100vw, 410px" src="/assets/cloned/images/90e528970344.webp" srcSet="/assets/cloned/images/b6e4b25036a7.webp 500w, /assets/cloned/images/6e996eb39a39.webp 800w, /assets/cloned/images/90e528970344.webp 820w" width="410" />
                    </div>
                    <div className="flex relative max-w-157.5 py-20 px-[3.5625rem] rounded-[5px] flex-col justify-center items-start self-stretch flex-1 bg-background max-lg:pt-10 max-lg:pb-8.5 max-md:px-5 md:max-lg:px-7.5">
                      <div className="w-[2.8125rem] block mb-13.5 max-lg:mb-6.5">
                        <img className="w-full h-9.5 block max-w-full overflow-clip object-cover aspect-[auto_45/38] align-middle" data-component="image" alt="" height="38" src="/assets/cloned/svg/9bef580093cb.svg" width="45" />
                      </div>
                      <div className="block mb-[2.9375rem] max-lg:mb-[1.1875rem]">
                        <h3 className="block text-color-001 text-3xl font-semibold leading-9 tracking-[-0.6px] max-md:text-[1.375rem] max-md:leading-[1.625rem] md:max-lg:text-[1.625rem] md:max-lg:leading-[1.9375rem]" data-component="heading">
                          “Noticeable improvement in pigmentation and texture after customized dermatology plan; truly outstanding clinical care.”
                        </h3>
                      </div>
                      <div className="flex flex-col items-start gap-[1.1875rem] max-md:gap-y-2.5 max-md:gap-x-4 md:max-lg:gap-4">
                        <div className="block text-color-001 text-lg font-medium leading-6 tracking-[-0.36px] whitespace-nowrap max-lg:text-[1.0625rem] max-lg:leading-[1.4375rem]">
                          Sophia Martinez
                        </div>
                        <div className="block -mb-[0.4rem] text-color-001 max-lg:-mb-[0.1rem]">
                          Los Angeles
                        </div>
                      </div>
                    </div>
                  </div>
                </div>
                <div className="w-full inline-block relative mr-12.5 align-top text-left whitespace-normal" aria-hidden="true" aria-label="2 of 6" role="group">
                  <div className="flex justify-between items-center gap-12.5 max-md:grid max-lg:items-stretch max-lg:gap-7.5 max-md:grid-cols-[345px] max-md:[grid-auto-columns:1fr]" aria-hidden="true">
                    <div className="block max-w-102.5 rounded-[5px] flex-1 overflow-hidden max-md:self-stretch max-md:max-w-none" aria-hidden="true">
                      <img className="w-full h-[34.4375rem] block max-w-full overflow-clip object-cover aspect-[auto_410/551] align-middle max-md:h-116 md:max-lg:h-110" data-component="image" alt="testimonial author image" aria-hidden="true" height="551" src="/assets/cloned/images/1d00a024552e.avif" width="410" />
                    </div>
                    <div className="flex relative max-w-157.5 py-20 px-[3.5625rem] rounded-[5px] flex-col justify-center items-start self-stretch flex-1 bg-background max-lg:pt-10 max-lg:pb-8.5 max-md:px-5 md:max-lg:px-7.5" aria-hidden="true">
                      <div className="w-[2.8125rem] block mb-13.5 max-lg:mb-6.5" aria-hidden="true">
                        <img className="w-full h-9.5 block max-w-full overflow-clip object-cover aspect-[auto_45/38] align-middle" alt="" aria-hidden="true" height="38" src="/assets/cloned/svg/9bef580093cb.svg" width="45" />
                      </div>
                      <div className="block mb-[2.9375rem] max-lg:mb-[1.1875rem]" aria-hidden="true">
                        <h3 className="block text-color-001 text-3xl font-semibold leading-9 tracking-[-0.6px] max-md:text-[1.375rem] max-md:leading-[1.625rem] md:max-lg:text-[1.625rem] md:max-lg:leading-[1.9375rem]" aria-hidden="true">
                          “Clear skin transformation after a tailored plan. The dermatologist’s guidance was precise, effective, and truly confidence-boosting."
                        </h3>
                      </div>
                      <div className="flex flex-col items-start gap-[1.1875rem] max-md:gap-y-2.5 max-md:gap-x-4 md:max-lg:gap-4" aria-hidden="true">
                        <div className="block text-color-001 text-lg font-medium leading-6 tracking-[-0.36px] whitespace-nowrap max-lg:text-[1.0625rem] max-lg:leading-[1.4375rem]" aria-hidden="true">
                          Liam Carter
                        </div>
                        <div className="block -mb-[0.4rem] text-color-001 max-lg:-mb-[0.1rem]" aria-hidden="true">
                          London
                        </div>
                      </div>
                    </div>
                  </div>
                </div>
                <div className="w-px h-px block absolute -m-px overflow-hidden" aria-atomic="true" aria-live="off" />
              </div>
              <div className="w-10 h-10 block absolute -top-15 right-0 z-4 justify-center items-center overflow-hidden text-background text-[2.5rem] bg-color-003 cursor-pointer max-lg:min-w-0" data-component="button" aria-controls="w-slider-mask-0" aria-label="next slide" role="button">
                <div className="w-10 h-full flex absolute top-0 left-0 p-[0.9rem] justify-center items-center">
                  <div className="w-2 h-full flex absolute top-0 right-3.5 z-1 min-w-0 max-w-2 flex-col justify-center items-center [filter:invert(0)]">
                    <div className="block">
                      <img className="w-full h-3.5 block max-w-full overflow-clip object-cover align-middle" data-component="image" alt="" src="/assets/cloned/svg/3e8b2fde4e1b.svg" />
                    </div>
                  </div>
                </div>
              </div>
            </div>
          </div>
        </div>
      </section>
    </>
  );
}
