import "./ditto.css";
import TextLink from "./components/text-link";
import Logo from "./components/logo";
import Logo2 from "./components/logo2";
// Generated by clone-site. Do not edit by hand.
const TextLink_data = [
    { href: "https://www.freepik.com/free-ai-image/beautiful-woman-with-long-wavy-brown-hair-makeup_418277330.htm", label: "Image1," },
    { href: "https://www.freepik.com/free-ai-image/applying-hair-serum-with-dropper_418346249.htm", label: "Image2," },
    { href: "https://www.freepik.com/free-photo/beautician-doing-injection-filler-female-client_12780841.htm", label: "Image3," },
    { href: "https://www.freepik.com/free-ai-image/woman-applying-shampoo-her-hair_416630106.htm", label: "Image4," },
    { href: "https://www.freepik.com/free-photo/dermatologist-removing-mole-from-womans-shoulder_8896360.htm", label: "Image5," },
    { href: "https://www.freepik.com/free-photo/man-getting-hair-loss-treatment_19966353.htm#", label: "Image6," },
    { href: "https://www.freepik.com/free-photo/front-view-smiley-woman-getting-prp-injections_24482034.htm", label: "Image7," },
    { href: "https://www.freepik.com/free-photo/front-view-senior-woman-with-melanoma_25128887.htm", label: "Image8," },
    { href: "https://www.freepik.com/free-ai-image/happy-woman-with-flowing-brown-hair-smiling_418277336.htm", label: "Image9," },
    { href: "https://www.freepik.com/free-ai-image/young-woman-tattooed-back-exudes-sensuality-elegance-generated-by-ai_47198983.htm", label: "Image10," },
    { href: "https://www.freepik.com/free-photo/woman-washes-face-with-brush-cleansing-foam-takes-care-complexion-skin_15104632.htm", label: "Image11," },
    { href: "https://www.freepik.com/free-photo/girl-posing-with-face-mask_4724350.htm", label: "Image12," },
    { href: "https://www.freepik.com/free-photo/female-hairdresser-making-hairstyle-redhead-woman-beauty-salon_7786275.htm", label: "Image13," },
    { href: "https://www.freepik.com/free-ai-image/woman-applying-cream-face_418346215.htm", label: "Image14," },
    { href: "https://www.freepik.com/free-ai-image/beautiful-woman-with-flowing-brown-hair-portrait_418277344.htm", label: "Image15," },
    { href: "https://www.freepik.com/free-photo/beautician-with-female-client-salon-face-care-routine_12780823.htm", label: "Image16," },
    { href: "https://www.freepik.com/free-photo/young-woman-with-moles-back-view_25128957.htm", label: "Image17," },
    { href: "https://www.freepik.com/free-photo/woman-cosmetologist-making-beauty-procedures_12178091.htm", label: "Image18," },
    { href: "https://www.freepik.com/free-photo/high-angle-patient-getting-prp-injection-alopecia_24482062.htm", label: "Image19," },
    { href: "https://www.freepik.com/free-photo/hand-with-glove-holding-magnifying-glass_25128945.htm", label: "Image20," },
    { href: "https://www.freepik.com/free-photo/woman-with-hyaluronic-acid-injection-medium-shot_24489945.htm", label: "Image21," },
    { href: "https://www.freepik.com/free-photo/high-angle-talented-tattoo-artist-working_27645245.htm", label: "Image22," },
    { href: "https://www.freepik.com/free-photo/antiaging-beauty-treatment_18992358.htm", label: "Image23," },
    { href: "https://www.freepik.com/free-photo/beautifull-caucasian-woman-with-curly-hair-smiles-isolated_12072692.htm", label: "Image24," },
    { href: "https://www.freepik.com/free-photo/young-determined-armenian-curlyhaired-female-university-student-listen-carefully-asignment-look-confident-ready-task-cross-hands-chest-smiling-selfassured-standing-white-background_34380832.htm", label: "Image25," },
    { href: "https://www.freepik.com/free-photo/waist-up-shot-attractive-young-girlfriend-with-dark-straight-hair-soft-healthy-skin_10747593.htm", label: "Image26," },
    { href: "https://www.freepik.com/free-photo/closeup-woman-having-facial-massage-beauty-treatment-spa_25630551.htm", label: "Image27," },
    { href: "https://www.freepik.com/free-photo/beautician-doing-injection-filler-female-client_12780810.htm", label: "Image28," },
    { href: "https://www.freepik.com/free-photo/mature-man-going-through-follicular-unit-extraction-process_18737164.htm", label: "Image29," },
    { href: "https://www.freepik.com/free-photo/high-angle-hand-measuring-mole_25128939.htm", label: "Image30," },
    { href: "https://www.freepik.com/free-photo/doctor-giving-woman-lip-fillers-high-angle_24396748.htm", label: "Image31" }
];
const Logo_data = [
    { alt: "home mission image three", imgSrc: "/assets/cloned/images/e50c3be7a8b1.avif" },
    { alt: "home mission image five", imgSrc: "/assets/cloned/images/dfbf813c5026.avif" },
    { alt: "", imgSrc: "/assets/cloned/images/2de51f5d41c7.webp", sizes: "100vw", srcSet: "/assets/cloned/images/86145a950d97.webp 500w, /assets/cloned/images/2de51f5d41c7.webp 740w" }
];
const TextLink_data2 = [
    { href: "https://www.lummi.ai/photo/delicate-pink-flowers-57rzp", label: "Image1," },
    { href: "https://www.lummi.ai/photo/woman-with-monstera-leaf-osbyt", label: "Image2," },
    { href: "https://www.lummi.ai/photo/hair-care-close-up-eqwpr", label: "Image3," },
    { href: "https://www.lummi.ai/photo/fashionable-red-bob-hairstyle-8etfz", label: "Image4," },
    { href: "https://www.lummi.ai/photo/elegant-portrait-0w-mb", label: "Image5," },
    { href: "https://www.lummi.ai/photo/serene-skincare-moment-lxnxb", label: "Image6," },
    { href: "https://www.lummi.ai/photo/skincare-routine-close-up-f4p6i", label: "Image7," },
    { href: "https://www.lummi.ai/photo/radiant-portrait-lfzi4", label: "Image8," },
    { href: "https://www.lummi.ai/photo/elegant-blonde-hairstyle-sfass", label: "Image9," },
    { href: "https://www.lummi.ai/photo/serene-skincare-moment-ooohd", label: "Image10," },
    { href: "https://www.lummi.ai/photo/serene-beauty-with-clay-mask-lzif9", label: "Image11," },
    { href: "https://www.lummi.ai/photo/portrait-of-a-man-with-glasses-jsft8", label: "Image12," },
    { href: "https://www.lummi.ai/photo/portrait-of-a-smiling-woman-bbdco", label: "Image13," },
    { href: "https://www.lummi.ai/photo/skincare-routine-close-up-f4p6i", label: "Image14," },
    { href: "https://www.lummi.ai/photo/skincare-routine-glow-bqkk0", label: "Image15," },
    { href: "https://www.lummi.ai/photo/woman-with-green-facial-mask-and-leaves-uwnlb", label: "Image16," },
    { href: "https://www.lummi.ai/photo/close-up-of-face-with-green-eye-and-leaf-neprs", label: "Image17," },
    { href: "https://www.lummi.ai/photo/elegant-hand-holding-skincare-product-apr0v", label: "Image18," },
    { href: "https://www.lummi.ai/photo/skincare-close-up-zz6vv", label: "Image19," },
    { href: "https://www.lummi.ai/photo/skincare-close-up-zz6vv", label: "Image20." }
];
const Logo2_data = [
    { alt: "client-image-one", sizes: "100vw", imgSrc: "/assets/cloned/images/f65d29f1d12e.webp", srcSet: "/assets/cloned/images/f930c3e70f90.webp 500w, /assets/cloned/images/d6b567b408fc.webp 800w, /assets/cloned/images/f65d29f1d12e.webp 820w" },
    { alt: "client image two", sizes: "100vw", imgSrc: "/assets/cloned/images/90e528970344.webp", srcSet: "/assets/cloned/images/b6e4b25036a7.webp 500w, /assets/cloned/images/6e996eb39a39.webp 800w, /assets/cloned/images/90e528970344.webp 820w" },
    { alt: "pricing rotate card image", imgSrc: "/assets/cloned/images/65be8e0e9c90.webp" }
];
const TextLink_meta: string[][] = [
    ["style-div-25"],
    ["style-button"],
    ["style-div-26"],
    ["style-image"],
    ["style-div-27"],
    ["style-div-28"],
    ["style-div-29"],
    ["style-div-30"],
    ["style-image-2"],
    ["style-div-31"],
    ["style-div-32"],
    ["style-div-3"],
    ["style-div-33"],
    ["style-heading"],
    ["style-div-10"],
    ["style-heading-2"],
    ["style-div-4"],
    ["style-div-34"],
    ["style-link"],
    ["style-image-3"],
    ["style-div-35"],
    ["style-div-36"],
    ["style-div-37"],
    ["style-div-38"],
    ["style-div-39"],
    ["style-div-40"],
    ["style-div-2"],
    ["style-div-41"],
    ["style-section"],
    ["style-div-42"],
    ["style-div-43"]
];
const Logo_meta: string[][] = [
    ["n79", "style-div-6"],
    ["n81", "style-div-7"],
    ["n83", "style-div-8"]
];
const TextLink_meta2: string[][] = [
    ["style-div-44"],
    ["style-div-45"],
    ["style-div-46"],
    ["style-div-12"],
    ["style-div-47"],
    ["style-div-48"],
    ["style-div-49"],
    ["style-div-50"],
    ["style-div-51"],
    ["style-div-9"],
    ["style-div-52"],
    ["style-div-53"],
    ["style-div-54"],
    ["style-div-55"],
    ["style-div-56"],
    ["style-div-57"],
    ["style-div-58"],
    ["style-div-59"],
    ["style-div-60"],
    ["style-div-61"]
];
const Logo2_meta: string[][] = [
    ["n112", "n113"],
    ["n114", "n115"],
    ["n116", "n117"]
];

export default function Page() {
  return (
    <>
      <section className="block pt-55 pb-35 bg-color-001 max-lg:pt-[10.3125rem] max-lg:pb-[5.9375rem]" data-ditto-id="style-div-5">
        <div className="block max-w-407.5 px-[0.9375rem] mx-auto before:content-['_'] before:table before:w-0 before:h-0 before:text-foreground before:text-base before:leading-7 after:content-['_'] after:table after:w-0 after:h-0 after:text-foreground after:text-base after:leading-7" data-ditto-id="style-div-13">
          <div className="flex flex-col justify-start items-center gap-2.5 text-center">
            <h1 className="block text-background text-6xl font-semibold leading-[4rem] tracking-[-1.2px] max-md:text-[2.1875rem] max-md:leading-[2.3125rem] md:max-lg:text-[2.5rem] md:max-lg:leading-[2.625rem]" data-component="heading">
              License
            </h1>
            <p className="block max-w-200 text-background max-md:max-w-none">
              All graphical assets in this template are licensed for personal and commercial use. If you'd like to use a specific asset, please check the license below
            </p>
          </div>
        </div>
      </section>
      <section className="block pt-30 pb-[7.0625rem] max-lg:pt-15 max-lg:pb-[3.3125rem]">
        <div className="block max-w-407.5 px-[0.9375rem] mx-auto before:content-['_'] before:table before:w-0 before:h-0 before:text-foreground before:text-base before:leading-7 after:content-['_'] after:table after:w-0 after:h-0 after:text-foreground after:text-base after:leading-7">
          <div className="border-b border-solid border-b-color-008 flex mb-7.5 pb-10 flex-col items-start">
            <h2 className="block mb-[1.5625rem] text-color-001 text-[2.625rem] font-semibold leading-[3rem] tracking-[-0.84px] max-lg:mb-[0.9375rem] max-md:text-[1.5625rem] max-md:leading-[1.8125rem] md:max-lg:text-3xl md:max-lg:leading-[2.125rem]" data-ditto-id="style-div" data-component="heading">
              Images
            </h2>
            <p className="block mb-5">
              All graphical assets in this template are licensed for personal and commercial use. If you'd like to use a specific asset, please check the license below
            </p>
            <div className="block mb-5 text-color-001 text-xl font-medium leading-6.5 tracking-[-0.4px] max-lg:text-lg max-lg:leading-[1.4375rem]" data-ditto-id="style-pass">
              Freepik
            </div>
            <div className="flex mb-10 flex-wrap justify-start items-start gap-2.5">
              {TextLink_data.map((d, i) => <TextLink key={i} d={d} />)}
            </div>
            <div className="grid mb-7.5 gap-12.5 [grid-auto-columns:1fr] grid-cols-3 max-lg:gap-7.5 max-md:grid-cols-1">
              {Logo_data.map((d, i) => <Logo key={i} d={d} />)}
            </div>
            <div className="block">
              {"Photography source from "}
              <span className="inline -mb-[0.4rem] text-color-001 max-lg:-mb-[0.1rem]" data-ditto-id="style-p">
                Freepik -
              </span>
              {" "}
              <a className="inline -mb-[0.4rem] text-color-001 cursor-pointer max-lg:-mb-[0.1rem]" data-ditto-id="style-div-24" data-component="link" href="https://www.freepikcompany.com/legal" target="_blank">
                Freepik License
              </a>
            </div>
          </div>
          <div className="border-b border-solid border-b-color-008 flex mb-7.5 pb-10 flex-col items-start" data-ditto-id="style-div-11">
            <div className="block mb-5 text-color-001 text-xl font-medium leading-6.5 tracking-[-0.4px] max-lg:text-lg max-lg:leading-[1.4375rem]">
              Lummi
            </div>
            <div className="flex mb-10 flex-wrap justify-start items-start gap-2.5">
              {TextLink_data2.map((d, i) => <TextLink key={i} d={d} />)}
            </div>
            <div className="grid mb-7.5 gap-12.5 [grid-auto-columns:1fr] grid-cols-3 max-lg:gap-7.5 max-md:grid-cols-1">
              {Logo2_data.map((d, i) => <Logo2 key={i} d={d} />)}
            </div>
            <div className="block">
              {"Photography source from "}
              <span className="inline -mb-[0.4rem] text-color-001 max-lg:-mb-[0.1rem]">
                Lummi -
              </span>
              {" "}
              <a className="inline -mb-[0.4rem] text-color-001 cursor-pointer max-lg:-mb-[0.1rem]" data-ditto-id="style-div-21" data-component="link" href="https://www.lummi.ai/license" target="_blank">
                Lummi License
              </a>
            </div>
          </div>
          <div className="border-b border-solid border-b-color-008 flex mb-7.5 pb-10 flex-col items-start">
            <h2 className="block mb-[1.5625rem] text-color-001 text-[2.625rem] font-semibold leading-[3rem] tracking-[-0.84px] max-lg:mb-[0.9375rem] max-md:text-[1.5625rem] max-md:leading-[1.8125rem] md:max-lg:text-3xl md:max-lg:leading-[2.125rem]" data-component="heading">
              Videos
            </h2>
            <p className="block mb-5">
              All graphical assets in this template are licensed for personal and commercial use. If you'd like to use a specific asset, please check the license below
            </p>
            <div className="block mb-5 text-color-001 text-xl font-medium leading-6.5 tracking-[-0.4px] max-lg:text-lg max-lg:leading-[1.4375rem]">
              Pexels
            </div>
            <div className="flex mb-10 flex-wrap justify-start items-start gap-2.5">
              <a className="block cursor-pointer" data-ditto-id="style-div-62" data-component="link" href="https://www.pexels.com/video/close-up-video-of-a-woman-getting-face-massage-9335788/" target="_blank">
                Video1,
              </a>
              <a className="block cursor-pointer" data-ditto-id="style-div-14" data-component="link" href="https://www.pexels.com/video/woman-getting-a-body-massage-9335791/" target="_blank">
                Video2
              </a>
            </div>
            <div className="w-full grid mb-7.5 gap-12.5 [grid-auto-columns:1fr] grid-cols-2 max-lg:gap-7.5 max-md:grid-cols-1">
              <div className="block">
                <div className="h-125 block relative rounded-[5px] overflow-hidden text-background">
                  <video className="w-150 h-125 block absolute -top-125 -left-150 -z-100 my-125 mx-150 overflow-clip object-cover bg-cover [background-position:50%_50%] max-md:w-[21.5625rem] max-md:-left-[21.5625rem] max-md:mx-[21.5625rem] md:max-lg:w-88.5 md:max-lg:-left-88.5 md:max-lg:mx-88.5 2xl:w-[48.4375rem] 2xl:-left-[48.4375rem] 2xl:mx-[48.4375rem]" style={{ backgroundImage: "url(\"/assets/cloned/images/785413b3ca18.jpg\")" }} autoPlay id="699611eb-ed68-8f07-3aeb-0dbb76f14dd5-video" loop muted playsInline poster="/assets/cloned/images/8da028852dd2.jpg">
                    <source className="inline text-color-004 [font-family:'Times_New_Roman'] leading-4.5" src="/assets/cloned/videos/e23b409c3d3a.mp4" />
                    <source className="inline text-color-004 [font-family:'Times_New_Roman'] leading-4.5" src="/assets/cloned/videos/260ff7679b30.webm" />
                  </video>
                  <div className="block" aria-live="polite">
                    <button className="w-10 h-10 block absolute bottom-[1.5625rem] left-3 text-center cursor-pointer max-md:left-[6.9px] md:max-lg:left-[0.4375rem] 2xl:left-[15.5px]" data-component="button" aria-controls="699611eb-ed68-8f07-3aeb-0dbb76f14dd5-video" type="button">
                      <span className="inline">
                        <img className="w-full h-10 block max-w-full overflow-clip object-cover align-middle" data-component="image" alt="Pause video" src="/assets/cloned/svg/5eb5fbcbf2ae.svg" />
                      </span>
                    </button>
                  </div>
                </div>
              </div>
              <div className="block">
                <div className="h-125 block relative rounded-[5px] overflow-hidden text-background">
                  <video className="w-150 h-125 block absolute -top-125 -left-150 -z-100 my-125 mx-150 overflow-clip object-cover bg-cover [background-position:50%_50%] max-md:w-[21.5625rem] max-md:-left-[21.5625rem] max-md:mx-[21.5625rem] md:max-lg:w-88.5 md:max-lg:-left-88.5 md:max-lg:mx-88.5 2xl:w-[48.4375rem] 2xl:-left-[48.4375rem] 2xl:mx-[48.4375rem]" style={{ backgroundImage: "url(\"/assets/cloned/images/29c7b6bb05dd.jpg\")" }} autoPlay id="55e46609-7198-76ea-f853-d1f2aaac929f-video" loop muted playsInline poster="/assets/cloned/images/ee8efdeff5dd.jpg">
                    <source className="inline text-color-004 [font-family:'Times_New_Roman'] leading-4.5" src="/assets/cloned/videos/e09472f58bbf.mp4" />
                    <source className="inline text-color-004 [font-family:'Times_New_Roman'] leading-4.5" src="/assets/cloned/videos/e8ec0db6eeff.webm" />
                  </video>
                  <div className="block" aria-live="polite">
                    <button className="w-10 h-10 block absolute bottom-[1.5625rem] left-3 text-center cursor-pointer max-md:left-[6.9px] md:max-lg:left-[0.4375rem] 2xl:left-[15.5px]" data-component="button" aria-controls="55e46609-7198-76ea-f853-d1f2aaac929f-video" type="button">
                      <span className="inline">
                        <img className="w-full h-10 block max-w-full overflow-clip object-cover align-middle" data-component="image" alt="Pause video" src="/assets/cloned/svg/5eb5fbcbf2ae.svg" />
                      </span>
                    </button>
                  </div>
                </div>
              </div>
            </div>
            <div className="block" data-ditto-id="style-div-64">
              {"Photography source from "}
              <span className="inline -mb-[0.4rem] text-color-001 max-lg:-mb-[0.1rem]">
                Pexels -
              </span>
              {" "}
              <a className="inline -mb-[0.4rem] text-color-001 cursor-pointer max-lg:-mb-[0.1rem]" data-ditto-id="style-div-22" data-component="link" href="https://www.pexels.com/license/" target="_blank">
                Pexels License
              </a>
            </div>
          </div>
          <div className="flex flex-col items-start">
            <h2 className="block mb-[1.5625rem] text-color-001 text-[2.625rem] font-semibold leading-[3rem] tracking-[-0.84px] max-lg:mb-[0.9375rem] max-md:text-[1.5625rem] max-md:leading-[1.8125rem] md:max-lg:text-3xl md:max-lg:leading-[2.125rem]" data-component="heading">
              Typography
            </h2>
            <p className="block">
              {"The font family used in "}
              <span className="inline -mb-[0.4rem] text-color-001 max-lg:-mb-[0.1rem]">
                Ixolyn
              </span>
              {" is "}
              <a className="inline -mb-[0.4rem] text-color-001 cursor-pointer max-lg:-mb-[0.1rem]" data-ditto-id="style-div-23" data-component="link" href="https://fonts.google.com/specimen/Parkinsans?preview.script=Latn" target="_blank">
                Parkinsans,
              </a>
              {" an open-source font from "}
              <span className="inline -mb-[0.4rem] text-color-001 max-lg:-mb-[0.1rem]">
                Google Fonts.
              </span>
            </p>
          </div>
        </div>
      </section>
    </>
  );
}
