import "./ditto.css";
import Tile from "./components/tile";
import ListRow from "./components/list-row";
import Logo from "./components/logo";
import Logo2 from "./components/logo2";
import ListRow2 from "./components/list-row2";
// Generated by clone-site. Do not edit by hand.
const Tile_data = [
    { text: "Deep Teal Green", text2: "#041a15" },
    { text: "Dark Olive Green", text2: "#3c4433" },
    { text: "Olive Drab", text2: "#48523d" },
    { text: "Dark Slate Green", text2: "#41534f" },
    { text: "Black", text2: "#000000" },
    { text: "Dark Gray", text2: "#4c4c4c" },
    { text: "Mist Green", text2: "#dee4d7" },
    { text: "Pale Sage", text2: "#d8dace" },
    { text: "Soft Warm Gray", text2: "#e6e0dc" },
    { text: "Light Gray", text2: "#d9d9d9" },
    { text: "Off White", text2: "#f2f3ee" },
    { text: "White", text2: "#ffffff" }
];
const ListRow_data = [
    { text: "List Item One" },
    { text: "List Item Two" },
    { text: "List Item Three" }
];
const Logo_data = [
    { alt: "facebook", imgSrc: "/assets/cloned/svg/52e8a5285ad5.svg" },
    { alt: "twitter", imgSrc: "/assets/cloned/svg/2a421a5fdbbc.svg" },
    { alt: "instagram", imgSrc: "/assets/cloned/svg/9b95bd270c7c.svg" },
    { alt: "LinkedIn", imgSrc: "/assets/cloned/svg/a59747fe88cd.svg" }
];
const Logo2_data = [
    { imgSrc: "/assets/cloned/svg/54de21dd9837.svg" },
    { imgSrc: "/assets/cloned/svg/2aba515c6c2d.svg" },
    { imgSrc: "/assets/cloned/svg/5e30b6944dae.svg" },
    { imgSrc: "/assets/cloned/svg/e671163a5021.svg" },
    { imgSrc: "/assets/cloned/svg/d73573491fdc.svg" },
    { imgSrc: "/assets/cloned/svg/3ab92b50e772.svg" },
    { imgSrc: "/assets/cloned/svg/e56150272e53.svg" },
    { imgSrc: "/assets/cloned/svg/8fa9ea6ee436.svg" }
];
const ListRow2_data = [
    { text: "Step-by-step guidance on cleansing, moisturizing, and protecting the skin for daily care." },
    { text: "Understanding different skin types and choosing the right products accordingly." },
    { text: "Importance of sun protection and hydration in maintaining skin health." },
    { text: "Tips for creating sustainable skincare habits for long-term skin improvement." }
];
const ListRow2_data2 = [
    { text: "Developed by skincare professionals and dermatology experts with practical experience in daily skin health management." },
    { text: "Medically reviewed to ensure accuracy, safety, and alignment with established skincare and dermatological standards." },
    { text: "Based on current skincare guidelines, scientific research, and evidence-based recommendations for routine skin care." }
];
const Tile_meta: string[][] = [
    ["style-div-26", "style-image", "style-div-27", "style-div-28", "style-div-29"],
    ["style-div-30", "style-image-2", "style-div-31", "style-div-32", "style-div-3"],
    ["style-div-33", "style-heading", "style-div-10", "style-heading-2", "style-div-4"],
    ["style-div-34", "style-link", "style-image-3", "style-div-35", "style-div-36"],
    ["style-div-37", "style-div-38", "style-div-39", "style-div-40", "style-div-2"],
    ["style-div-41", "style-section", "style-div-42", "style-div-43", "n78"],
    ["n79", "style-div-6", "n81", "style-div-7", "n83"],
    ["style-div-8", "n85", "style-p", "style-div-24", "style-div-11"],
    ["n89", "n90", "style-div-44", "style-div-45", "style-div-46"],
    ["style-div-12", "style-div-47", "style-div-48", "style-div-49", "style-div-50"],
    ["style-div-51", "style-div-9", "style-div-52", "style-div-53", "style-div-54"],
    ["style-div-55", "style-div-56", "style-div-57", "style-div-58", "style-div-59"]
];
const ListRow_meta: string[][] = [
    ["n245"],
    ["n246"],
    ["n247"]
];
const Logo_meta: string[][] = [
    ["n257", "n258"],
    ["n259", "n260"],
    ["n261", "n262"],
    ["style-div-69", "n264"]
];
const Logo2_meta: string[][] = [
    ["n268", "n269"],
    ["n270", "n271"],
    ["n272", "n273"],
    ["n274", "n275"],
    ["n276", "n277"],
    ["n278", "n279"],
    ["style-div-63", "n281"],
    ["n282", "n283"]
];
const ListRow2_meta: string[][] = [
    ["n333"],
    ["n334"],
    ["n335"],
    ["n336"]
];
const ListRow2_meta2: string[][] = [
    ["n344"],
    ["n345"],
    ["n346"]
];
const Tile_styles = [
    { className: "bg-color-001" },
    { className: "bg-color-003" },
    { className: "bg-clr-36" },
    { className: "bg-color-006" },
    { className: "bg-color-004" },
    { className: "bg-foreground" },
    { className: "bg-clr-6" },
    { className: "bg-color-010" },
    { className: "bg-surface-5" },
    { className: "bg-border" },
    { className: "bg-surface" },
    { className: "bg-background" }
];
const ListRow_styles = [
    {  },
    {  },
    { className: "whitespace-nowrap" }
];
const Logo_styles = [
    { className: "h-3.5" },
    { className: "h-3.5" },
    { className: "h-3.5" },
    { className: "h-[0.9375rem]" }
];
const Logo2_styles = [
    { className: "h-[1.8125rem]" },
    { className: "h-[1.8125rem]" },
    { className: "h-[1.4375rem]" },
    { className: "h-[1.4375rem]" },
    { className: "h-[1.1875rem]" },
    { className: "h-9.5" },
    { className: "h-[2.1875rem]" },
    { className: "h-[2.1875rem]" }
];

export default function Page() {
  return (
    <>
      <section className="block pt-55 pb-35 bg-color-001 max-lg:pt-[10.3125rem] max-lg:pb-[5.9375rem]" data-ditto-id="style-div-5">
        <div className="block max-w-407.5 px-[0.9375rem] mx-auto before:content-['_'] before:table before:w-0 before:h-0 before:text-foreground before:text-base before:leading-7 after:content-['_'] after:table after:w-0 after:h-0 after:text-foreground after:text-base after:leading-7" data-ditto-id="style-div-13">
          <div className="flex flex-col justify-start items-center gap-2.5 text-center">
            <h1 className="block text-background text-6xl font-semibold leading-[4rem] tracking-[-1.2px] max-md:text-[2.1875rem] max-md:leading-[2.3125rem] md:max-lg:text-[2.5rem] md:max-lg:leading-[2.625rem]" data-component="heading">
              Style guide
            </h1>
          </div>
        </div>
      </section>
      <section className="block pt-30 pb-[6.0625rem] max-lg:pt-15 max-lg:pb-12.5">
        <div className="block max-w-407.5 px-[0.9375rem] mx-auto before:content-['_'] before:table before:w-0 before:h-0 before:text-foreground before:text-base before:leading-7 after:content-['_'] after:table after:w-0 after:h-0 after:text-foreground after:text-base after:leading-7">
          <div className="flex flex-col items-start gap-12.5 max-lg:gap-7.5">
            <div className="w-full flex flex-col items-start">
              <div className="flex justify-start items-center gap-2.5" data-ditto-id="style-div">
                <div className="w-[2.8rem] block">
                  <img className="w-full h-[2.8125rem] block max-w-full overflow-clip object-cover align-middle" data-ditto-id="style-pass" data-component="image" alt="Icon" height="Auto" src="/assets/cloned/svg/8b0673ba0e60.svg" width="40" />
                </div>
                <div className="block text-color-001 text-xl font-medium leading-6.5 tracking-[-0.4px] max-lg:text-lg max-lg:leading-[1.4375rem]">
                  Colors
                </div>
              </div>
              <div className="w-full h-px block mt-5 mb-[2.1875rem] bg-color-008 max-lg:mb-5" data-ditto-id="style-div-25" />
              <div className="w-full grid gap-12.5 [grid-auto-columns:1fr] grid-cols-3 max-lg:gap-7.5 max-md:grid-cols-1" data-ditto-id="style-button">
                {Tile_data.map((d, i) => <Tile key={i} d={d} styles={Tile_styles[i]} />)}
              </div>
            </div>
            <div className="w-full flex flex-col items-start" data-ditto-id="style-div-60">
              <div className="flex justify-start items-center gap-2.5" data-ditto-id="style-div-61">
                <div className="w-[2.8rem] block">
                  <img className="w-full h-9.5 block max-w-full overflow-clip object-cover align-middle" data-component="image" alt="Icon" height="Auto" src="/assets/cloned/svg/2e4d8c04555b.svg" width="40" />
                </div>
                <div className="block text-color-001 text-xl font-medium leading-6.5 tracking-[-0.4px] max-lg:text-lg max-lg:leading-[1.4375rem]">
                  Typography
                </div>
              </div>
              <div className="w-full h-px block mt-5 mb-[2.1875rem] bg-color-008 max-lg:mb-5" />
              <div className="w-full flex flex-col items-start">
                <div className="w-full flex pb-2.5 justify-between items-center gap-10 max-md:gap-5">
                  <div className="block basis-1/2" />
                  <div className="grid items-start basis-1/2 gap-7.5 [grid-auto-columns:1fr] text-center grid-cols-[1fr_1fr_1fr] max-md:gap-5 max-md:grid-cols-[30.7188px_51.5625px_64.5px]">
                    <div className="block -mb-[0.4rem] text-color-001 max-lg:-mb-[0.1rem]">
                      Size
                    </div>
                    <div className="block -mb-[0.4rem] text-color-001 max-lg:-mb-[0.1rem]" data-ditto-id="style-div-21">
                      Line height
                    </div>
                    <div className="block -mb-[0.4rem] text-color-001 max-lg:-mb-[0.1rem]">
                      Weights
                    </div>
                  </div>
                </div>
                <div className="w-full border-b border-solid border-b-color-008 flex py-[1.5625rem] justify-between items-center gap-10 max-md:gap-5">
                  <div className="block basis-1/2">
                    <h1 className="block text-color-001 text-6xl font-semibold leading-[4rem] tracking-[-1.2px] max-md:text-[2.1875rem] max-md:leading-[2.3125rem] md:max-lg:text-[2.5rem] md:max-lg:leading-[2.625rem]" data-component="heading">
                      H1
                    </h1>
                  </div>
                  <div className="grid items-start basis-1/2 gap-7.5 [grid-auto-columns:1fr] text-center grid-cols-[1fr_1fr_1fr] max-md:gap-5 max-md:grid-cols-[64.0469px_71.4062px_40.0625px]">
                    <div className="block -mb-[0.4rem] text-color-001 max-lg:-mb-[0.1rem]" data-ditto-id="style-div-62">
                      3.75rem
                    </div>
                    <div className="block -mb-[0.4rem] text-color-001 max-lg:-mb-[0.1rem]" data-ditto-id="style-div-14">
                      106.666%
                    </div>
                    <div className="block -mb-[0.4rem] text-color-001 max-lg:-mb-[0.1rem]">
                      Semi Bold
                    </div>
                  </div>
                </div>
                <div className="w-full border-b border-solid border-b-color-008 flex py-[1.5625rem] justify-between items-center gap-10 max-md:gap-5">
                  <div className="block basis-1/2">
                    <h2 className="block text-color-001 text-[2.625rem] font-semibold leading-[3rem] tracking-[-0.84px] max-md:text-[1.5625rem] max-md:leading-[1.8125rem] md:max-lg:text-3xl md:max-lg:leading-[2.125rem]" data-component="heading">
                      H2
                    </h2>
                  </div>
                  <div className="grid items-start basis-1/2 gap-7.5 [grid-auto-columns:1fr] text-center grid-cols-[1fr_1fr_1fr] max-md:gap-5 max-md:grid-cols-[73.4688px_69.2344px_65.4062px]">
                    <div className="block -mb-[0.4rem] text-color-001 max-lg:-mb-[0.1rem]">
                      2.625rem
                    </div>
                    <div className="block -mb-[0.4rem] text-color-001 max-lg:-mb-[0.1rem]">
                      114.285%
                    </div>
                    <div className="block -mb-[0.4rem] text-color-001 max-lg:-mb-[0.1rem]">
                      Medium
                    </div>
                  </div>
                </div>
                <div className="w-full border-b border-solid border-b-color-008 flex py-[1.5625rem] justify-between items-center gap-10 max-md:gap-5">
                  <div className="block basis-1/2">
                    <h3 className="block text-color-001 text-3xl font-semibold leading-9 tracking-[-0.6px] max-md:text-[1.375rem] max-md:leading-[1.625rem] md:max-lg:text-[1.625rem] md:max-lg:leading-[1.9375rem]" data-component="heading">
                      H3
                    </h3>
                  </div>
                  <div className="grid items-start basis-1/2 gap-7.5 [grid-auto-columns:1fr] text-center grid-cols-[1fr_1fr_1fr] max-md:gap-5 max-md:grid-cols-[71.8594px_38.5156px_65.4062px]">
                    <div className="block -mb-[0.4rem] text-color-001 max-lg:-mb-[0.1rem]">
                      1.875rem
                    </div>
                    <div className="block -mb-[0.4rem] text-color-001 max-lg:-mb-[0.1rem]">
                      120%
                    </div>
                    <div className="block -mb-[0.4rem] text-color-001 max-lg:-mb-[0.1rem]">
                      Medium
                    </div>
                  </div>
                </div>
                <div className="w-full border-b border-solid border-b-color-008 flex py-[1.5625rem] justify-between items-center gap-10 max-md:gap-5">
                  <div className="block basis-1/2">
                    <h4 className="block text-color-001 text-2xl font-semibold leading-[1.75rem] tracking-[-0.48px] max-md:text-xl max-md:leading-[1.4375rem] md:max-lg:text-[1.375rem] md:max-lg:leading-[1.625rem]" data-component="heading">
                      H4
                    </h4>
                  </div>
                  <div className="grid items-start basis-1/2 gap-7.5 [grid-auto-columns:1fr] text-center grid-cols-[1fr_1fr_1fr] max-md:gap-5 max-md:grid-cols-[52.7031px_68.6094px_65.4062px]">
                    <div className="block" data-ditto-id="style-div-64">
                      1.5rem
                    </div>
                    <div className="block -mb-[0.4rem] text-color-001 max-lg:-mb-[0.1rem]">
                      116.666%
                    </div>
                    <div className="block -mb-[0.4rem] text-color-001 max-lg:-mb-[0.1rem]" data-ditto-id="style-div-22">
                      Medium
                    </div>
                  </div>
                </div>
                <div className="w-full border-b border-solid border-b-color-008 flex py-[1.5625rem] justify-between items-center gap-10 max-md:gap-5">
                  <div className="block basis-1/2">
                    <h5 className="block text-color-001 text-xl font-medium leading-6.5 tracking-[-0.4px] max-lg:text-lg max-lg:leading-[1.4375rem]" data-component="heading">
                      H5
                    </h5>
                  </div>
                  <div className="grid items-start basis-1/2 gap-7.5 [grid-auto-columns:1fr] text-center grid-cols-[1fr_1fr_1fr] max-md:gap-5 max-md:grid-cols-[62.0469px_38.2656px_65.4062px]">
                    <div className="block -mb-[0.4rem] text-color-001 max-lg:-mb-[0.1rem]" data-ditto-id="style-div-23">
                      1.25rem
                    </div>
                    <div className="block -mb-[0.4rem] text-color-001 max-lg:-mb-[0.1rem]">
                      130%
                    </div>
                    <div className="block -mb-[0.4rem] text-color-001 max-lg:-mb-[0.1rem]">
                      Medium
                    </div>
                  </div>
                </div>
                <div className="w-full border-b border-solid border-b-color-008 flex py-[1.5625rem] justify-between items-center gap-10 max-md:gap-5">
                  <div className="block basis-1/2">
                    <h6 className="block text-color-001 text-lg font-medium leading-6 tracking-[-0.36px] max-lg:text-[1.0625rem] max-lg:leading-[1.4375rem]" data-component="heading">
                      H6
                    </h6>
                  </div>
                  <div className="grid items-start basis-1/2 gap-7.5 [grid-auto-columns:1fr] text-center grid-cols-[1fr_1fr_1fr] max-md:gap-5 max-md:grid-cols-[69.3281px_68.5469px_65.4062px]">
                    <div className="block -mb-[0.4rem] text-color-001 max-lg:-mb-[0.1rem]">
                      1.125rem
                    </div>
                    <div className="block -mb-[0.4rem] text-color-001 max-lg:-mb-[0.1rem]">
                      133.333%
                    </div>
                    <div className="block -mb-[0.4rem] text-color-001 max-lg:-mb-[0.1rem]">
                      Medium
                    </div>
                  </div>
                </div>
                <div className="w-full border-b border-solid border-b-color-008 flex py-[1.5625rem] justify-between items-center gap-10 max-md:gap-5">
                  <div className="block basis-1/2">
                    <p className="block mb-2.5 max-md:mb-0 md:max-lg:mb-[0.3125rem]">
                      Body font
                    </p>
                  </div>
                  <div className="grid items-start basis-1/2 gap-7.5 [grid-auto-columns:1fr] text-center grid-cols-[1fr_1fr_1fr] max-md:gap-5 max-md:grid-cols-[38.8906px_37.5312px_62.0938px]">
                    <div className="block -mb-[0.4rem] text-color-001 max-lg:-mb-[0.1rem]">
                      1rem
                    </div>
                    <div className="block -mb-[0.4rem] text-color-001 max-lg:-mb-[0.1rem]">
                      175%
                    </div>
                    <div className="block -mb-[0.4rem] text-color-001 max-lg:-mb-[0.1rem]">
                      Regular
                    </div>
                  </div>
                </div>
                <div className="w-full border-b border-solid border-b-color-008 flex py-[1.5625rem] justify-between items-center gap-10 max-md:gap-5">
                  <div className="block basis-1/2">
                    <p className="block -mb-[0.4rem] text-color-001 leading-6 max-lg:-mb-[0.1rem]">
                      Menu font
                    </p>
                  </div>
                  <div className="grid items-start basis-1/2 gap-7.5 [grid-auto-columns:1fr] text-center grid-cols-[1fr_1fr_1fr] max-md:gap-5 max-md:grid-cols-[38.8906px_37.8438px_62.0938px]">
                    <div className="block -mb-[0.4rem] text-color-001 max-lg:-mb-[0.1rem]">
                      1rem
                      <br className="inline" />
                    </div>
                    <div className="block -mb-[0.4rem] text-color-001 max-lg:-mb-[0.1rem]">
                      150%
                    </div>
                    <div className="block -mb-[0.4rem] text-color-001 max-lg:-mb-[0.1rem]">
                      Regular
                    </div>
                  </div>
                </div>
                <div className="w-full border-b border-solid border-b-color-008 flex py-[1.5625rem] justify-between items-center gap-10 max-md:gap-5">
                  <div className="block basis-1/2">
                    <p className="block -mb-[0.4rem] text-color-001 leading-6 max-lg:-mb-[0.1rem]">
                      Button font
                    </p>
                  </div>
                  <div className="grid items-start basis-1/2 gap-7.5 [grid-auto-columns:1fr] text-center grid-cols-[1fr_1fr_1fr] max-md:gap-5 max-md:grid-cols-[38.8906px_37.8438px_62.0938px]" data-ditto-id="style-div-65">
                    <div className="block -mb-[0.4rem] text-color-001 max-lg:-mb-[0.1rem]">
                      1rem
                    </div>
                    <div className="block -mb-[0.4rem] text-color-001 max-lg:-mb-[0.1rem]">
                      150%
                    </div>
                    <div className="block -mb-[0.4rem] text-color-001 max-lg:-mb-[0.1rem]">
                      Regular
                    </div>
                  </div>
                </div>
              </div>
            </div>
            <div className="w-full flex flex-col items-start">
              <div className="flex justify-start items-center gap-2.5">
                <div className="w-[2.8rem] block">
                  <img className="w-full h-[2.8125rem] block max-w-full overflow-clip object-cover aspect-[auto_40/40] align-middle" data-component="image" alt="Icon" height="40" src="/assets/cloned/svg/a3793f71071c.svg" width="40" />
                </div>
                <div className="block text-color-001 text-xl font-medium leading-6.5 tracking-[-0.4px] max-lg:text-lg max-lg:leading-[1.4375rem]">
                  Shadows
                </div>
              </div>
              <div className="w-full h-px block mt-5 mb-[2.1875rem] bg-color-008 max-lg:mb-5" />
              <div className="w-full grid gap-7.5 [grid-auto-columns:1fr] grid-cols-3 max-md:grid-cols-1 md:max-lg:grid-cols-2">
                <div className="h-45 flex rounded-[10px] justify-center items-center bg-background shadow-[var(--clr-4)_0px_0px_40px_0px] max-lg:shadow-[var(--clr-17)_0px_40px_60px_0px]" data-ditto-id="style-div-66">
                  <div className="block -mb-[0.4rem] text-color-001 max-lg:-mb-[0.1rem]">
                    Small
                  </div>
                </div>
              </div>
            </div>
            <div className="w-full flex flex-col items-start">
              <div className="flex justify-start items-center gap-2.5">
                <div className="w-[2.8rem] block">
                  <img className="w-full h-[3.1875rem] block max-w-full overflow-clip object-cover align-middle" data-component="image" alt="Icons" height="Auto" src="/assets/cloned/svg/6aadb8639244.svg" width="40" />
                </div>
                <div className="block text-color-001 text-xl font-medium leading-6.5 tracking-[-0.4px] max-lg:text-lg max-lg:leading-[1.4375rem]">
                  Logo
                </div>
              </div>
              <div className="w-full h-px block mt-5 mb-[2.1875rem] bg-color-008 max-lg:mb-5" />
              <div className="w-full flex mb-10 flex-col items-start gap-[0.9375rem]">
                <div className="block text-color-001 text-lg font-medium leading-6 tracking-[-0.36px] max-lg:text-[1.0625rem] max-lg:leading-[1.4375rem]">
                  Favicons
                </div>
                <div className="flex flex-wrap justify-start items-center gap-5 grid-cols-[1fr_1fr] grid-rows-[auto] [grid-auto-columns:1fr]">
                  <div className="block max-w-8" data-ditto-id="style-div-67">
                    <img className="w-full h-8 block max-w-full overflow-clip object-cover aspect-[auto_32/32] align-middle" data-component="image" alt="32x32 Favicon" height="32" src="/assets/cloned/images/c218560ee1a1.png" width="32" />
                  </div>
                  <div className="block max-w-64">
                    <img className="w-full h-64 block max-w-full overflow-clip object-cover aspect-[auto_256/256] align-middle" data-component="image" alt="256x256 Favicon" height="256" src="/assets/cloned/images/2051afb036ba.png" width="256" />
                  </div>
                </div>
              </div>
              <div className="w-full flex flex-col items-start gap-[0.9375rem]">
                <div className="block text-color-001 text-lg font-medium leading-6 tracking-[-0.36px] max-lg:text-[1.0625rem] max-lg:leading-[1.4375rem]">
                  Brand logo
                </div>
                <div className="flex flex-wrap justify-start items-center gap-5 grid-cols-[1fr_1fr] grid-rows-[auto] [grid-auto-columns:1fr]">
                  <div className="block p-5 rounded-[10px] bg-background shadow-[var(--clr-17)_0px_10px_40px_0px]">
                    <img className="w-full h-8 block max-w-full overflow-clip object-cover aspect-[auto_108/32] align-middle" data-component="image" alt="" height="32" src="/assets/cloned/svg/06c57c8fa650.svg" width="108" />
                  </div>
                  <div className="block p-5 rounded-[10px] bg-color-001 shadow-[var(--clr-17)_0px_10px_40px_0px]">
                    <img className="w-full h-8 block max-w-full overflow-clip object-cover aspect-[auto_108/32] align-middle" data-component="image" alt="" height="32" src="/assets/cloned/svg/aac82e29caf4.svg" width="108" />
                  </div>
                </div>
              </div>
            </div>
            <div className="w-full flex flex-col items-start">
              <div className="flex justify-start items-center gap-2.5">
                <div className="w-[2.8rem] block">
                  <img className="w-full h-[3.5625rem] block max-w-full overflow-clip object-cover align-middle" data-component="image" alt="Icon" height="Auto" src="/assets/cloned/svg/88609ee158c0.svg" width="33" />
                </div>
                <div className="block text-color-001 text-xl font-medium leading-6.5 tracking-[-0.4px] max-lg:text-lg max-lg:leading-[1.4375rem]">
                  Buttons
                </div>
              </div>
              <div className="w-full h-px block mt-5 mb-[2.1875rem] bg-color-008 max-lg:mb-5" />
              <div className="flex flex-wrap justify-center items-center gap-5">
                <a className="h-[2.7125rem] border border-solid border-color-003 flex relative z-0 max-w-full pt-[0.5625rem] pb-2.5 px-5 rounded-[50px] justify-center items-center gap-2.5 overflow-hidden bg-color-003 cursor-pointer" data-component="link" href="/">
                  <div className="h-[1.4rem] block relative z-1 overflow-hidden max-md:shrink-0">
                    <div className="block text-background leading-6 whitespace-nowrap">
                      Button style v1
                    </div>
                    <div className="block text-background leading-6 whitespace-nowrap">
                      Button style v1
                    </div>
                  </div>
                  <div className="w-[178.1px] h-[2.6375rem] flex absolute top-0 left-0 min-w-0 rounded-[50px] justify-center items-center bg-color-006 transform-[matrix(1,0,0,1,0,42.2031)] pointer-events-none" />
                  <div className="w-[0.5875rem] h-[0.6rem] flex relative z-1 mt-0.5 justify-center items-center max-md:shrink-0">
                    <img className="w-full h-2.5 block max-w-full overflow-clip object-cover aspect-[auto_9/9] align-middle" data-component="image" alt="button white arrow" height="9" src="/assets/cloned/svg/97bfaa7e2654.svg" width="9" />
                  </div>
                </a>
                <a className="h-6.5 flex relative max-w-full justify-start items-center gap-2.5 cursor-pointer" data-component="link" href="/">
                  <div className="h-6.5 flex flex-col items-start overflow-hidden">
                    <div className="block -mb-[0.4rem] text-color-001 whitespace-nowrap max-lg:-mb-[0.1rem]">
                      Button style v2
                    </div>
                  </div>
                  <div className="w-3 h-3.5 flex flex-col items-start">
                    <div className="w-3 block">
                      <img className="w-full h-3.5 block max-w-full overflow-clip object-cover aspect-[auto_12/14] align-middle" data-component="image" alt="" height="14" src="/assets/cloned/svg/1f46cc0606a2.svg" width="12" />
                    </div>
                  </div>
                  <div className="w-[139.7px] h-px block absolute bottom-0 min-w-0 bg-color-008">
                    <div className="w-0 h-px block bg-color-004" />
                  </div>
                </a>
              </div>
            </div>
            <div className="w-full flex flex-col items-start">
              <div className="flex justify-start items-center gap-2.5">
                <img className="w-[2.3125rem] h-[2.3125rem] block max-w-full overflow-clip object-cover align-middle" data-component="image" alt="Icon" height="Auto" src="/assets/cloned/svg/afe095c85bae.svg" width="37" />
                <div className="block text-color-001 text-xl font-medium leading-6.5 tracking-[-0.4px] max-lg:text-lg max-lg:leading-[1.4375rem]">
                  Lists
                </div>
              </div>
              <div className="w-full h-px block mt-5 mb-[2.1875rem] bg-color-008 max-lg:mb-5" />
              <div className="flex items-start gap-12.5 max-md:flex-col max-md:gap-7.5" data-ditto-id="style-div-68">
                <div className="block before:content-['_'] before:table before:w-0 before:h-0 before:text-foreground before:text-base before:leading-7 after:content-['_'] after:table after:w-0 after:h-0 after:text-foreground after:text-base after:leading-7">
                  <ul className="block mb-2.5 pl-10 overflow-hidden [list-style-type:disc] list-outside max-lg:mb-0" role="list">
                    {ListRow_data.map((d, i) => <ListRow key={i} d={d} styles={ListRow_styles[i]} />)}
                  </ul>
                </div>
              </div>
            </div>
            <div className="w-full flex flex-col items-start">
              <div className="flex justify-start items-center gap-2.5">
                <div className="w-[2.8rem] block">
                  <img className="w-full h-[2.8125rem] block max-w-full overflow-clip object-cover align-middle" data-component="image" alt="Icon" height="Auto" src="/assets/cloned/svg/64175eb226e8.svg" width="40" />
                </div>
                <div className="block text-color-001 text-xl font-medium leading-6.5 tracking-[-0.4px] max-lg:text-lg max-lg:leading-[1.4375rem]">
                  Icons
                </div>
              </div>
              <div className="w-full h-px block mt-5 mb-[2.1875rem] bg-color-008 max-lg:mb-5" />
              <div className="w-full flex mb-10 flex-col items-start gap-[0.9375rem]">
                <div className="block text-color-001 text-xl font-medium leading-6.5 tracking-[-0.4px] max-lg:text-lg max-lg:leading-[1.4375rem]">
                  Social icons
                </div>
                <div className="flex p-5 rounded-[5px] flex-wrap justify-start items-center gap-5 grid-cols-[1fr_1fr] grid-rows-[auto] [grid-auto-columns:1fr] bg-color-001">
                  {Logo_data.map((d, i) => <Logo key={i} d={d} styles={Logo_styles[i]} />)}
                </div>
              </div>
              <div className="w-full flex flex-col items-start gap-[0.9375rem]">
                <div className="block text-color-001 text-xl font-medium leading-6.5 tracking-[-0.4px] max-lg:text-lg max-lg:leading-[1.4375rem]">
                  Line icons
                </div>
                <div className="flex flex-wrap justify-start items-center gap-5 grid-cols-[1fr_1fr] grid-rows-[auto] [grid-auto-columns:1fr]">
                  {Logo2_data.map((d, i) => <Logo2 key={i} d={d} styles={Logo2_styles[i]} />)}
                </div>
              </div>
            </div>
            <div className="w-full flex flex-col items-start">
              <div className="flex justify-start items-center gap-2.5">
                <div className="w-[2.8rem] block">
                  <img className="w-full h-[2.8125rem] block max-w-full overflow-clip object-cover align-middle" data-component="image" alt="Icon" height="Auto" src="/assets/cloned/svg/951b60939848.svg" width="40" />
                </div>
                <div className="block text-color-001 text-xl font-medium leading-6.5 tracking-[-0.4px] max-lg:text-lg max-lg:leading-[1.4375rem]">
                  Avatars
                </div>
              </div>
              <div className="w-full h-px block mt-5 mb-[2.1875rem] bg-color-008 max-lg:mb-5" />
              <div className="flex flex-wrap justify-start items-center gap-5 grid-cols-[1fr_1fr] grid-rows-[auto] [grid-auto-columns:1fr]">
                <div className="flex flex-col justify-center items-center gap-[0.4375rem]">
                  <div className="block">
                    <img className="w-full h-40 block max-w-full rounded-[100%] overflow-clip object-cover aspect-[auto_80/80] align-middle" data-component="avatar" alt="blog small image" height="80" src="/assets/cloned/images/b6a100e56184.webp" width="80" />
                  </div>
                  <div className="block -mb-[0.4rem] text-color-001 max-lg:-mb-[0.1rem]">
                    5rem
                  </div>
                </div>
              </div>
            </div>
            <div className="w-full flex flex-col items-start">
              <div className="flex justify-start items-center gap-2.5">
                <div className="w-[2.8rem] block">
                  <img className="w-full h-[2.8125rem] block max-w-full overflow-clip object-cover align-middle" data-component="image" alt="Icons" height="Auto" src="/assets/cloned/svg/c086892b1a51.svg" width="43" />
                </div>
                <div className="block text-color-001 text-xl font-medium leading-6.5 tracking-[-0.4px] max-lg:text-lg max-lg:leading-[1.4375rem]">
                  Placeholder
                </div>
              </div>
              <div className="w-full h-px block mt-5 mb-[2.1875rem] bg-color-008 max-lg:mb-5" />
              <div className="w-full flex mb-10 flex-col items-start gap-[0.9375rem]">
                <div className="block text-color-001 text-lg font-medium leading-6 tracking-[-0.36px] max-lg:text-[1.0625rem] max-lg:leading-[1.4375rem]">
                  Inputs
                </div>
                <div className="w-4/5 flex justify-start items-center gap-7.5 max-lg:w-full max-md:flex-col max-md:justify-center max-md:items-stretch">
                  <div className="w-full block">
                    <form className="block" aria-label="Style Guide Form" id="wf-form-Style-Guide-Form" name="wf-form-Style-Guide-Form">
                      <input className="w-full h-[2.6875rem] border border-solid border-color-010 block py-2 px-[1.5625rem] rounded-[60px] overflow-clip align-middle text-sm leading-5 bg-background cursor-text" data-ditto-id="style-div-70" data-component="input" id="Field-one" name="Field-one" placeholder="Placeholder" type="text" />
                    </form>
                  </div>
                  <div className="w-full block">
                    <form className="block" aria-label="Email Form three" id="wf-form-Email-Form-three" name="wf-form-Email-Form-three">
                      <div className="flex relative justify-end items-center max-md:flex-col max-md:items-stretch max-md:gap-[0.9375rem]">
                        <input className="w-full h-12.5 border-b border-solid border-b-border block py-2 pr-3 overflow-clip align-middle text-color-001 text-sm leading-5 bg-background cursor-text" data-ditto-id="style-div-71" data-component="input" id="Field-three" name="Field-three" placeholder="Placeholder" type="text" />
                      </div>
                    </form>
                  </div>
                </div>
              </div>
              <div className="w-full flex mb-10 flex-col items-start gap-[0.9375rem] max-md:pl-[0.9375rem]">
                <div className="block text-color-001 text-lg font-medium leading-6 tracking-[-0.36px] max-lg:text-[1.0625rem] max-lg:leading-[1.4375rem]">
                  Text area
                </div>
                <div className="w-full block">
                  <form className="block" aria-label="Style Guide Form Two" id="wf-form-Style-Guide-Form-Two" name="wf-form-Style-Guide-Form-Two">
                    <textarea className="w-full h-40 min-h-40 border-b border-solid border-b-border block min-w-full max-w-full py-2 pr-3 overflow-auto align-middle text-color-001 text-sm leading-5 whitespace-pre-wrap [overflow-wrap:break-word] bg-clr-27 cursor-text" data-ditto-id="style-div-72" data-component="textarea" id="Style-Guide-Textarea" name="Style-Guide-Textarea" placeholder="Placeholder" />
                  </form>
                </div>
              </div>
              <div className="w-full flex flex-col items-start gap-[0.9375rem]">
                <div className="block text-color-001 text-lg font-medium leading-6 tracking-[-0.36px] max-lg:text-[1.0625rem] max-lg:leading-[1.4375rem]">
                  States messages
                </div>
                <div className="w-full block p-5 text-center bg-clr-36">
                  <div className="block text-background">
                    Thank you! Your submission has been received!
                  </div>
                </div>
              </div>
            </div>
            <div className="flex flex-col items-start">
              <div className="flex justify-start items-center gap-2.5">
                <div className="w-[2.8rem] block">
                  <img className="w-full h-[2.8125rem] block max-w-full overflow-clip object-cover align-middle" data-component="image" alt="Icon" height="Auto" src="/assets/cloned/svg/c830c4b0d14d.svg" width="43" />
                </div>
                <div className="block text-color-001 text-xl font-medium leading-6.5 tracking-[-0.4px] max-lg:text-lg max-lg:leading-[1.4375rem]">
                  Rich text
                </div>
              </div>
              <div className="w-full h-px block mt-5 mb-[2.1875rem] bg-color-008 max-lg:mb-5" />
              <div className="block before:content-['_'] before:table before:w-0 before:h-0 before:text-foreground before:text-base before:leading-7 after:content-['_'] after:table after:w-0 after:h-0 after:text-foreground after:text-base after:leading-7">
                <h2 className="block mt-5 mb-2.5 text-color-001 text-[2.625rem] font-semibold leading-[3rem] tracking-[-0.84px] max-md:text-[1.5625rem] max-md:leading-[1.8125rem] md:max-lg:text-3xl md:max-lg:leading-[2.125rem]" data-component="heading">
                  Comprehensive dermatology knowledge from experienced skin specialists
                </h2>
                <p className="block mb-2.5 max-md:mb-0 md:max-lg:mb-[0.3125rem]">
                  ‍
                </p>
                <h5 className="block my-2.5 text-color-001 text-xl font-medium leading-6.5 tracking-[-0.4px] max-lg:text-lg max-lg:leading-[1.4375rem]" data-component="heading">
                  Introduction
                </h5>
                <p className="block mb-2.5 max-md:mb-0 md:max-lg:mb-[0.3125rem]">
                  This article provides practical guidance on building a simple yet effective daily skincare routine. It is designed to help individuals maintain healthy, radiant skin through consistent habits, suitable products, and dermatologist-recommended practices.
                </p>
                <h5 className="block my-2.5 text-color-001 text-xl font-medium leading-6.5 tracking-[-0.4px] max-lg:text-lg max-lg:leading-[1.4375rem]" data-component="heading">
                  What this article covers
                </h5>
                <ul className="block mb-2.5 pl-10 overflow-hidden [list-style-type:disc] list-outside max-lg:mb-0" role="list">
                  {ListRow2_data.map((d, i) => <ListRow2 key={i} d={d} />)}
                </ul>
                <p className="block mb-2.5 max-md:mb-0 md:max-lg:mb-[0.3125rem]">
                  ‍
                </p>
                <figure className="block relative clear-both max-w-full mb-2.5 text-center">
                  <div className="inline-block text-clr-8 text-[0rem]">
                    <img className="w-full h-[39.0625rem] block max-w-full overflow-clip object-cover align-middle max-md:h-[10.8125rem] md:max-lg:h-[23.0625rem] 2xl:h-200" data-component="image" alt="" src="/assets/cloned/images/406de4ed0246.webp" />
                  </div>
                </figure>
                <p className="block mb-2.5 max-md:mb-0 md:max-lg:mb-[0.3125rem]">
                  ‍
                </p>
                <h5 className="block my-2.5 text-color-001 text-xl font-medium leading-6.5 tracking-[-0.4px] max-lg:text-lg max-lg:leading-[1.4375rem]" data-component="heading">
                  Expertise behind the content
                </h5>
                <ul className="block mb-2.5 pl-10 overflow-hidden [list-style-type:disc] list-outside max-lg:mb-0" role="list">
                  {ListRow2_data2.map((d, i) => <ListRow2 key={i} d={d} />)}
                </ul>
              </div>
            </div>
          </div>
        </div>
      </section>
    </>
  );
}
