import "./ditto.css";
import ListRow from "./components/list-row";
import MediaTile from "./components/media-tile";
// Generated by clone-site. Do not edit by hand.
const ListRow_data = [
    { text: "Fundamentals of healthy skin structure and function explained for better understanding." },
    { text: "Common medical and cosmetic skin concerns addressed with clinical clarity." },
    { text: "Latest advancements in dermatology treatments using safe, evidence based technologies." },
    { text: "Preventive skin care strategies designed to support long term, healthy skin results." }
];
const ListRow_data2 = [
    { text: "Authored by qualified dermatologists with extensive clinical experience in medical and cosmetic skin care." },
    { text: "Medically reviewed to ensure accuracy, clinical relevance, and alignment with dermatology best practices." },
    { text: "Based on current dermatology guidelines, peer reviewed research, and evidence based clinical standards." }
];
const ListRow_data3 = [
    { text: "Acne, pigmentation, and chronic skin conditions managed through personalized, clinically proven dermatology treatments." },
    { text: "Hair and scalp disorders managed using advanced diagnostic evaluation and targeted medical therapies." },
    { text: "Cosmetic dermatology and aesthetic treatments designed to enhance appearance while maintaining natural skin balance." },
    { text: "Laser, injectable, and non-invasive procedures performed safely under expert dermatological supervision." }
];
const ListRow_data4 = [
    { text: "Better understanding of skin conditions and effective solutions through expert dermatology education and guidance." },
    { text: "Informed decision-making for dermatology treatments supported by clinically accurate information and professional advice." },
    { text: "Improved skin care routines guided by experienced professionals to maintain long-term skin health." }
];
const MediaTile_data = [
    { imgSrc: "/assets/cloned/images/da310c503f78.webp", srcSet: "/assets/cloned/images/a3e478af586e.webp 500w, /assets/cloned/images/809c1eda64ae.webp 800w, /assets/cloned/images/da310c503f78.webp 820w", text: "Sandra Bell", label: "Medically reviewed articles supporting effective skin treatment choices" },
    { imgSrc: "/assets/cloned/images/38867bde9333.webp", srcSet: "/assets/cloned/images/53fda489dd64.webp 500w, /assets/cloned/images/e8f18931b8a8.webp 800w, /assets/cloned/images/38867bde9333.webp 820w", text: "Jennifer Lindsay", label: "Practical skin care guidance from board certified dermatologists" },
    { imgSrc: "/assets/cloned/images/965d1f38bf3b.webp", srcSet: "/assets/cloned/images/5a5d8e812428.webp 500w, /assets/cloned/images/8b7d352fdc2e.webp 800w, /assets/cloned/images/965d1f38bf3b.webp 820w", text: "Martin Claypool", label: "Trusted dermatology information for informed skin care decisions" }
];
const ListRow_meta: string[][] = [
    ["style-div-4"],
    ["style-div-34"],
    ["style-link"],
    ["style-image-3"]
];
const ListRow_meta2: string[][] = [
    ["style-div-41"],
    ["style-section"],
    ["style-div-42"]
];
const ListRow_meta3: string[][] = [
    ["n81"],
    ["style-div-7"],
    ["n83"],
    ["style-div-8"]
];
const ListRow_meta4: string[][] = [
    ["style-div-45"],
    ["style-div-46"],
    ["style-div-12"]
];
const MediaTile_meta: string[][] = [
    ["style-div-56", "style-div-57", "style-div-58", "style-div-59", "style-div-60", "style-div-61", "n111", "n112", "n113", "n114", "n115", "n116"],
    ["n117", "n118", "n119", "style-div-21", "n121", "n122", "n123", "n124", "n125", "style-div-62", "style-div-14", "n128"],
    ["n129", "n130", "n131", "n132", "n133", "n134", "n135", "n136", "n137", "n138", "n139", "n140"]
];
const MediaTile_styles = [
    { className: "h-full" },
    {  },
    {  }
];

export default function Page() {
  return (
    <>
      <section className="block overflow-hidden" data-ditto-id="style-div-5">
        <div className="block" data-ditto-id="style-div-13">
          <img className="w-full h-[40.6875rem] block max-w-full overflow-clip object-cover align-middle max-md:h-[11.9375rem] md:max-lg:h-[24.4375rem] 2xl:h-244" data-component="image" alt="" sizes="100vw" src="/assets/cloned/images/81c90b3eb761.webp" srcSet="/assets/cloned/images/e2c588f63ad3.webp 500w, /assets/cloned/images/0845e63a6f54.webp 800w, /assets/cloned/images/7dd50ba01196.webp 1080w, /assets/cloned/images/ed2fb54ff150.webp 1600w, /assets/cloned/images/5368dfa4ec69.webp 2000w, /assets/cloned/images/00f87b5f7e69.webp 2600w, /assets/cloned/images/a00f36790dd4.webp 3200w, /assets/cloned/images/81c90b3eb761.webp 3748w" />
        </div>
      </section>
      <section className="block pt-[5.8125rem] pb-25 max-md:pt-15 max-lg:pb-[2.9375rem] md:max-lg:pt-[2.0625rem]">
        <div className="block max-w-330 px-[0.9375rem] mx-auto before:content-['_'] before:table before:w-0 before:h-0 before:text-foreground before:text-base before:leading-7 after:content-['_'] after:table after:w-0 after:h-0 after:text-foreground after:text-base after:leading-7">
          <div className="flex justify-between items-start gap-7.5 max-md:flex-col max-md:gap-[0.9375rem]">
            <div className="h-[20.5625rem] flex sticky top-28 max-w-65 mt-[1.6rem] py-10 px-5 rounded-md flex-col justify-start items-center flex-1 gap-7 bg-surface max-md:h-[15.9375rem] max-md:pt-7.5 max-md:pb-6 max-md:self-stretch max-lg:gap-[1.4375rem] max-md:static max-md:max-w-none max-md:mt-0 md:max-lg:h-[19.4375rem] md:max-lg:pb-8.5">
              <div className="block max-w-20 max-md:max-w-16">
                <img className="w-full h-20 block max-w-full overflow-clip object-cover aspect-[auto_80/80] align-middle max-md:h-16" data-ditto-id="style-div" data-component="image" alt="" height="80" src="/assets/cloned/images/b74b63744af4.webp" width="80" />
              </div>
              <div className="flex flex-col justify-start items-center gap-7 text-center max-md:self-stretch max-md:gap-4.5">
                <div className="border-b border-solid border-b-border flex pb-7 flex-col justify-start items-center max-md:pb-[0.6875rem] max-md:self-stretch md:max-lg:pb-[1.3125rem]" data-ditto-id="style-pass">
                  <div className="block text-color-001">
                    Mark Roseberry
                  </div>
                  <div className="block font-medium" data-ditto-id="style-div-25">
                    Broad Street, New York
                  </div>
                </div>
                <div className="flex justify-start items-center gap-2.5" data-ditto-id="style-button">
                  <div className="block max-w-4" data-ditto-id="style-div-26">
                    <div className="block" data-ditto-id="style-image">
                      <img className="w-full h-[1.0625rem] block max-w-full overflow-clip object-cover aspect-[auto_16/17] align-middle" data-ditto-id="style-div-27" data-component="image" alt="" height="17" src="/assets/cloned/svg/380c8da09335.svg" width="16" />
                    </div>
                  </div>
                  <div className="block" data-ditto-id="style-div-28">
                    April 12, 2026
                  </div>
                </div>
              </div>
            </div>
            <div className="block max-w-[60.5625rem] flex-1 max-md:max-w-none" data-ditto-id="style-div-29">
              <div className="border-b border-solid border-b-border block pb-10 max-lg:pb-7.5" data-ditto-id="style-div-30">
                <div className="block before:content-['_'] before:table before:w-0 before:h-0 before:text-foreground before:text-base before:leading-7 after:content-['_'] after:table after:w-0 after:h-0 after:text-foreground after:text-base after:leading-7" data-ditto-id="style-image-2">
                  <h2 className="block mt-5 mb-2.5 text-color-001 text-[2.625rem] font-semibold leading-[3rem] tracking-[-0.84px] max-md:text-[1.5625rem] max-md:leading-[1.8125rem] md:max-lg:text-3xl md:max-lg:leading-[2.125rem]" data-ditto-id="style-div-31" data-component="heading">
                    Comprehensive dermatology knowledge from experienced skin specialists
                  </h2>
                  <p className="block mb-2.5 max-md:mb-0 md:max-lg:mb-[0.3125rem]" data-ditto-id="style-div-32">
                    ‍
                  </p>
                  <h5 className="block my-2.5 text-color-001 text-xl font-medium leading-6.5 tracking-[-0.4px] max-lg:text-lg max-lg:leading-[1.4375rem]" data-ditto-id="style-div-3" data-component="heading">
                    Introduction
                  </h5>
                  <p className="block mb-2.5 max-md:mb-0 md:max-lg:mb-[0.3125rem]" data-ditto-id="style-div-33">
                    This article provides in-depth dermatology knowledge curated by experienced skin specialists. It is designed to educate patients on skin health, modern treatments, and evidence-based dermatological care practices.
                  </p>
                  <p className="block mb-2.5 max-md:mb-0 md:max-lg:mb-[0.3125rem]" data-ditto-id="style-heading">
                    ‍
                  </p>
                  <h5 className="block my-2.5 text-color-001 text-xl font-medium leading-6.5 tracking-[-0.4px] max-lg:text-lg max-lg:leading-[1.4375rem]" data-ditto-id="style-div-10" data-component="heading">
                    What this article covers
                  </h5>
                  <ul className="block mb-2.5 pl-10 overflow-hidden [list-style-type:disc] list-outside max-lg:mb-0" data-ditto-id="style-heading-2" role="list">
                    {ListRow_data.map((d, i) => <ListRow key={i} d={d} />)}
                  </ul>
                  <p className="block mb-2.5 max-md:mb-0 md:max-lg:mb-[0.3125rem]" data-ditto-id="style-div-35">
                    ‍
                  </p>
                  <figure className="block relative clear-both max-w-full mb-2.5 text-center" data-ditto-id="style-div-36">
                    <div className="inline-block text-clr-8 text-[0rem]" data-ditto-id="style-div-37">
                      <img className="w-full h-120 block max-w-full overflow-clip object-cover align-middle max-md:h-[10.8125rem] md:max-lg:h-56 2xl:h-[30.3125rem]" data-ditto-id="style-div-38" data-component="image" alt="" src="/assets/cloned/images/406de4ed0246.webp" />
                    </div>
                  </figure>
                  <p className="block mb-2.5 max-md:mb-0 md:max-lg:mb-[0.3125rem]" data-ditto-id="style-div-39">
                    ‍
                  </p>
                  <h5 className="block my-2.5 text-color-001 text-xl font-medium leading-6.5 tracking-[-0.4px] max-lg:text-lg max-lg:leading-[1.4375rem]" data-ditto-id="style-div-40" data-component="heading">
                    Expertise behind the content
                  </h5>
                  <ul className="block mb-2.5 pl-10 overflow-hidden [list-style-type:disc] list-outside max-lg:mb-0" data-ditto-id="style-div-2" role="list">
                    {ListRow_data2.map((d, i) => <ListRow key={i} d={d} />)}
                  </ul>
                </div>
              </div>
              <div className="block pt-10 max-lg:pt-7" data-ditto-id="style-div-43">
                <div className="block before:content-['_'] before:table before:w-0 before:h-0 before:text-foreground before:text-base before:leading-7 after:content-['_'] after:table after:w-0 after:h-0 after:text-foreground after:text-base after:leading-7">
                  <h5 className="block my-2.5 text-color-001 text-xl font-medium leading-6.5 tracking-[-0.4px] max-lg:text-lg max-lg:leading-[1.4375rem]" data-component="heading">
                    Key dermatology topics explained
                  </h5>
                  <ul className="block mb-2.5 pl-10 overflow-hidden [list-style-type:disc] list-outside max-lg:mb-0" data-ditto-id="style-div-6" role="list">
                    {ListRow_data3.map((d, i) => <ListRow key={i} d={d} />)}
                  </ul>
                  <p className="block mb-2.5 max-md:mb-0 md:max-lg:mb-[0.3125rem]">
                    ‍
                  </p>
                  <figure className="block relative clear-both max-w-full mb-2.5 text-center" data-ditto-id="style-p">
                    <div className="inline-block text-clr-8 text-[0rem]" data-ditto-id="style-div-24">
                      <img className="w-full h-120 block max-w-full overflow-clip object-cover align-middle max-md:h-[10.8125rem] md:max-lg:h-56 2xl:h-[30.3125rem]" data-ditto-id="style-div-11" data-component="image" alt="" src="/assets/cloned/images/c3d2e3bd5648.webp" />
                    </div>
                  </figure>
                  <p className="block mb-2.5 max-md:mb-0 md:max-lg:mb-[0.3125rem]">
                    ‍
                  </p>
                  <h5 className="block my-2.5 text-color-001 text-xl font-medium leading-6.5 tracking-[-0.4px] max-lg:text-lg max-lg:leading-[1.4375rem]" data-component="heading">
                    Benefits for readers
                  </h5>
                  <ul className="block mb-2.5 pl-10 overflow-hidden [list-style-type:disc] list-outside max-lg:mb-0" data-ditto-id="style-div-44" role="list">
                    {ListRow_data4.map((d, i) => <ListRow key={i} d={d} />)}
                  </ul>
                  <h5 className="block my-2.5 text-color-001 text-xl font-medium leading-6.5 tracking-[-0.4px] max-lg:text-lg max-lg:leading-[1.4375rem]" data-ditto-id="style-div-47" data-component="heading">
                    Conclusion
                  </h5>
                  <p className="block mb-2.5 max-md:mb-0 md:max-lg:mb-[0.3125rem]" data-ditto-id="style-div-48">
                    This blog serves as a trusted dermatology knowledge resource, empowering patients with expert insights to achieve healthier, well-managed skin through professional care.
                  </p>
                </div>
              </div>
            </div>
          </div>
        </div>
      </section>
      <section className="block pt-[7.0625rem] pb-30 bg-surface max-lg:pt-[3.3125rem] max-lg:pb-15" data-ditto-id="style-div-49">
        <div className="block max-w-407.5 px-[0.9375rem] mx-auto before:content-['_'] before:table before:w-0 before:h-0 before:text-foreground before:text-base before:leading-7 after:content-['_'] after:table after:w-0 after:h-0 after:text-foreground after:text-base after:leading-7" data-ditto-id="style-div-50">
          <div className="block" data-ditto-id="style-div-51">
            <div className="block pb-12.5 max-lg:pb-7.5" data-ditto-id="style-div-9">
              <h2 className="block text-color-001 text-[2.625rem] font-semibold leading-[3rem] tracking-[-0.84px] max-md:text-[1.5625rem] max-md:leading-[1.8125rem] md:max-lg:text-3xl md:max-lg:leading-[2.125rem]" data-ditto-id="style-div-52" data-component="heading">
                Recent articles
              </h2>
            </div>
            <div className="block" data-ditto-id="style-div-53">
              <div className="block" data-ditto-id="style-div-54">
                <div className="grid gap-7.5 [grid-auto-columns:1fr] grid-cols-3 max-md:grid-cols-1" data-ditto-id="style-div-55" role="list">
                  {MediaTile_data.map((d, i) => <MediaTile key={i} d={d} styles={MediaTile_styles[i]} />)}
                </div>
              </div>
            </div>
          </div>
        </div>
      </section>
    </>
  );
}
